import type { CounterDefinition, Machine } from "@/types";
import type { ControlManifestItem, SessionCapability } from "@/types/machineGuide";

export const CUSTOM_RECORDS_KEY="slot-companion-custom-records-v1";
export type CustomRecordDefinition={id:string;machineId:string;name:string;type:"counter"|"choice";choices:string[];quick:boolean};

export function loadCustomRecords(machineId:string):CustomRecordDefinition[]{if(typeof window==="undefined")return[];try{const all=JSON.parse(window.localStorage.getItem(CUSTOM_RECORDS_KEY)??"[]") as CustomRecordDefinition[];return all.filter(item=>item.machineId===machineId)}catch{return[]}}
export function saveCustomRecord(definition:CustomRecordDefinition){if(typeof window==="undefined")return false;try{const raw=window.localStorage.getItem(CUSTOM_RECORDS_KEY),all=raw?JSON.parse(raw) as CustomRecordDefinition[]:[],next=[...all.filter(item=>item.id!==definition.id),definition];window.localStorage.setItem(CUSTOM_RECORDS_KEY,JSON.stringify(next));return true}catch{return false}}
export function withCustomRecords(machine:Machine,definitions:CustomRecordDefinition[]):Machine{if(!definitions.length)return machine;const copy=structuredClone(machine),manifest=copy.profile.controlManifest??[];for(const definition of definitions){const key=`custom:${definition.id}`,choices=definition.type==="choice"?definition.choices.map((label,index)=>({value:`custom:${definition.id}:${index}`,labelZh:label,labelJa:label})):undefined,counter:CounterDefinition={id:key,machineId:copy.id,key,labelZh:definition.name,labelJa:definition.name,icon:"✦",description:"使用者自訂記錄",recognition:`看到「${definition.name}」時`,reason:"依自己的遊玩需求記錄。",type:definition.type==="choice"?"choice":"event",...(choices?.length?{choices}:{})},capability:SessionCapability={moduleId:`custom:${definition.id}`,moduleKind:"custom_event",controlType:definition.type==="choice"?"choice":"event",labelZh:definition.name,labelJa:definition.name,observationKey:key,writeTarget:{type:"counter",key},stateEffect:null,status:"operational",reason:null,estimatorUsable:false,choicesRequired:definition.type==="choice",choicesAvailable:definition.type==="counter"||Boolean(choices?.length),numeratorDependency:null,denominatorDependency:null,eventId:key,playerWhen:counter.recognition,sourceEvidence:["使用者自訂"],quickPriority:definition.quick?35:90,manifestControlType:definition.type==="choice"?"choice":"counter"};const item:ControlManifestItem={id:`control:${key}`,label:definition.name,eventType:"custom",controlType:definition.type==="choice"?"choice":"counter",playerWhen:counter.recognition,observationKey:key,stateEffect:null,estimatorUsable:false,numerator:null,denominator:null,sourceEvidence:["使用者自訂"],availability:"operational",unavailableReason:null,quickPriority:definition.quick?35:90,moduleKind:"custom_event",eventId:key,...(choices?{choices}:{})};copy.profile.smartCounters.push(counter);copy.profile.sessionCapabilities=[...(copy.profile.sessionCapabilities??[]),capability];manifest.push(item)}copy.profile.controlManifest=manifest;return copy}
