import type { CounterDefinition, GameState, Machine } from "@/types";
import type { SessionCapability, SessionQuickGuide } from "@/types/machineGuide";

export type SessionStateControl={value:GameState;label:string;ja:string};
export type SessionRecordControl={id:string;capability:SessionCapability;counter?:CounterDefinition;priority:number;sourceOrder:number};
export type SessionUiModel={legacy:boolean;capabilities:SessionCapability[];actionCapabilities:SessionCapability[];counterDefinitions:CounterDefinition[];recordControls:SessionRecordControl[];primaryRecordControls:SessionRecordControl[];overflowRecordControls:SessionRecordControl[];gameStates:SessionStateControl[];showGenericCz:boolean;showGenericAt:boolean};
const LEGACY_STATES:SessionStateControl[]=[{value:"normal",label:"通常",ja:"通常"},{value:"prelude",label:"前兆",ja:"前兆"},{value:"cz",label:"CZ",ja:"チャンスゾーン"},{value:"at",label:"AT",ja:"AT"},{value:"special",label:"特殊",ja:"特殊"}];
const STATE_LABELS:Record<GameState,[string,string]>={normal:["通常","通常"],prelude:["前兆","前兆"],cz:["CZ","チャンスゾーン"],at:["AT","AT"],art:["ART","ART"],bonus:["Bonus","ボーナス"],special:["特殊","特殊"],other:["其他","その他"]};
function usableCounter(counter:CounterDefinition){return counter.type!=="choice"||Boolean(counter.choices?.length)}
function recordPriority(kind:SessionCapability["moduleKind"]){if(kind==="named_cz")return 10;if(kind==="at"||kind==="art")return 20;if(kind==="big_reg_bonus")return 30;if(kind==="end_evidence")return 40;return 50}
export function buildSessionUiModel(machine:Machine):SessionUiModel{const snapshot=machine.profile.sessionCapabilities;if(!snapshot)return{legacy:true,capabilities:[],actionCapabilities:[],counterDefinitions:machine.profile.smartCounters.filter(usableCounter),recordControls:[],primaryRecordControls:[],overflowRecordControls:[],gameStates:LEGACY_STATES,showGenericCz:true,showGenericAt:true};
  const capabilities=snapshot.filter(capability=>capability.status==="operational"),byObservation=new Map(capabilities.map(capability=>[capability.observationKey,capability])),counterDefinitions=machine.profile.smartCounters.filter(counter=>usableCounter(counter)&&Boolean(byObservation.get(counter.key))),actionCapabilities=capabilities.filter(capability=>capability.controlType==="event"&&!capability.eventId&&(capability.moduleKind==="named_cz"||capability.moduleKind==="at"));
  const counterKeys=new Set(counterDefinitions.map(counter=>counter.key)),recordControls=capabilities.flatMap((capability,sourceOrder)=>{const counter=counterDefinitions.find(item=>item.key===capability.observationKey);if(counter)return[{id:counter.key,capability,counter,priority:recordPriority(capability.moduleKind),sourceOrder}];if(actionCapabilities.includes(capability)&&!counterKeys.has(capability.observationKey))return[{id:capability.moduleId,capability,priority:recordPriority(capability.moduleKind),sourceOrder}];return[]}).sort((a,b)=>a.priority-b.priority||a.sourceOrder-b.sourceOrder);
  const stateValues=new Set<GameState>(["normal"]);for(const capability of capabilities)if(capability.stateEffect)stateValues.add(capability.stateEffect);const gameStates=[...stateValues].map(value=>{const guideState=machine.profile.guideStates?.find(state=>(state.type==="chance_zone"?"cz":state.type)===value),fallback=STATE_LABELS[value];return{value,label:guideState?.displayNameZh??fallback[0],ja:guideState?.originalNameJa??fallback[1]}});
  return{legacy:false,capabilities,actionCapabilities,counterDefinitions,recordControls,primaryRecordControls:recordControls.slice(0,4),overflowRecordControls:recordControls.slice(4),gameStates,showGenericCz:actionCapabilities.some(capability=>capability.observationKey==="cz"),showGenericAt:actionCapabilities.some(capability=>capability.observationKey==="at")};
}

export function capabilityForCounter(model:SessionUiModel,key:string){return model.capabilities.find(capability=>capability.observationKey===key)}
export function guideEventsForState(guide:SessionQuickGuide|undefined,state:GameState){const categories=state==="cz"?["cz"]:state==="at"?["at"]:state==="art"?["art"]:state==="bonus"?["bonus"]:state==="special"?["indication","special"]:[];return guide?.events.filter(item=>categories.includes(item.category))??[]}
