import type { Machine, Session, SettingBenchmark } from "@/types";
const SETTINGS=[1,2,3,4,5,6] as const;
type Distribution=Record<(typeof SETTINGS)[number],number>;
export type EstimatorEvidence={id:string;label:string;observation:string;impact:number;direction:string};
export type EstimatorResult={status:"not_started"|"estimating";distribution:Distribution;groups:{low:number;mid:number;high:number};confidence:"low"|"medium"|"high";confidenceScore:number;evidence:EstimatorEvidence[]};
export type EstimatorReadiness={status:"no_benchmark"|"collecting"|"ready";title:string;summary:string;items:Array<{id:string;label:string;sample:string;next:string}>};
function metricValue(session:Session,machine:Machine,key:string){const definition=machine.profile.measurementMetrics.find(item=>item.key===key);if(!definition)return session.metrics[key]??0;const source=definition.source;if(source.type==="trackerDelta"){const baseline=session.trackerBaselines[source.trackerKey];return baseline===undefined?0:Math.max(0,(session.trackers[source.trackerKey]??0)-baseline)}if(source.type==="custom")return session.metrics[source.sessionMetricKey]??0;return session.metrics[source.type]??0}
function normalize(logScores:number[]):Distribution{const max=Math.max(...logScores),raw=logScores.map(score=>Math.exp(score-max)),total=raw.reduce((sum,value)=>sum+value,0);return Object.fromEntries(SETTINGS.map((setting,index)=>[setting,raw[index]/total])) as Distribution}
function distance(a:Distribution,b:Distribution){return SETTINGS.reduce((sum,s)=>sum+Math.abs(a[s]-b[s]),0)/2}
function counterNumber(session:Session,key:string){if(key==="cz")return session.czCount;if(key==="at")return session.atCount;const value=session.counters[key];return typeof value==="number"?value:0}
function evidenceLogLikelihood(benchmark:SettingBenchmark,session:Session,machine:Machine){const observation=benchmark.observation;if(observation.type==="rate"){const count=counterNumber(session,observation.numeratorKey),denominator=metricValue(session,machine,observation.denominatorMetricKey);if(count<=0||denominator<benchmark.minimumSample)return null;const strength=Math.min(1,denominator/benchmark.minimumSample),log=SETTINGS.map(setting=>{const expected=benchmark.settingValues[setting];if(!expected||expected<=0)return-30;const p=observation.valueMode==="oneIn"?1/expected:expected,lambda=Math.max(.000001,denominator*p);return strength*(count*Math.log(lambda)-lambda)});return{log,strength,observation:`${count} 次 / ${denominator}G → 1/${(denominator/count).toFixed(1)}`}}if(observation.type==="trialOutcome"){const records=(session.trials[observation.relationshipId]??[]).filter(item=>item.outcome!=="pending");if(records.length<benchmark.minimumSample)return null;const success=records.filter(item=>item.outcome==="success").length,strength=Math.min(1,records.length/benchmark.minimumSample),log=SETTINGS.map(setting=>{const p=Math.min(.999999,Math.max(.000001,benchmark.settingValues[setting]??.000001));return strength*(success*Math.log(p)+(records.length-success)*Math.log(1-p))});return{log,strength,observation:`${success} / ${records.length} → ${(success/records.length*100).toFixed(1)}%`}}if(session.counters[observation.counterKey]!==observation.equals)return null;return{log:SETTINGS.map(setting=>Math.log(Math.max(.000001,benchmark.settingValues[setting]??.000001))),strength:1,observation:benchmark.labelZh}}
function supportedByCapability(machine:Machine,benchmark:SettingBenchmark){const capabilities=machine.profile.sessionCapabilities,denominators=machine.profile.denominatorCapabilities;if(!capabilities)return true;const observation=benchmark.observation;if(observation.type==="rate")return capabilities.some(capability=>capability.status==="operational"&&capability.estimatorUsable&&(capability.observationKey===observation.numeratorKey||capability.writeTarget.key===observation.numeratorKey))&&Boolean(denominators?.some(denominator=>denominator.status==="operational"&&denominator.observationKey===observation.denominatorMetricKey));if(observation.type==="trialOutcome")return capabilities.some(capability=>capability.status==="operational"&&capability.writeTarget.type==="relationship"&&capability.writeTarget.key===observation.relationshipId);return capabilities.some(capability=>capability.status==="operational"&&capability.controlType==="choice"&&(capability.observationKey===observation.counterKey||capability.writeTarget.key===observation.counterKey))}
function observationSignature(benchmark:SettingBenchmark){const observation=benchmark.observation;if(observation.type==="rate")return`rate:${observation.numeratorKey}:${observation.denominatorMetricKey}:${observation.valueMode}`;if(observation.type==="trialOutcome")return`trial:${observation.relationshipId}`;return`choice:${observation.counterKey}:${observation.equals}`}
function theorySignature(benchmark:SettingBenchmark){return JSON.stringify([1,2,3,4,5,6].map(setting=>benchmark.settingValues[setting as 1|2|3|4|5|6]))}
function displayLabel(machine:Machine,benchmark:SettingBenchmark){const observation=benchmark.observation;if(observation.type!=="rate")return benchmark.labelZh;const capability=machine.profile.sessionCapabilities?.find(item=>item.status==="operational"&&(item.observationKey===observation.numeratorKey||item.writeTarget.key===observation.numeratorKey));return capability?`${capability.labelZh} 初當率`:benchmark.labelZh}
export function activeSettingBenchmarks(machine:Machine){const eligible=machine.profile.benchmarks.filter(item=>item.verified&&(machine.guideStatus?!item.testData:machine.profileStatus==="verified"?!item.testData:item.testData)&&supportedByCapability(machine,item)),groups=new Map<string,SettingBenchmark[]>();for(const benchmark of eligible){const signature=observationSignature(benchmark),items=groups.get(signature)??[];items.push(benchmark);groups.set(signature,items)}return[...groups.values()].flatMap(items=>{if(items.length===1)return[{...items[0],labelZh:displayLabel(machine,items[0])}];const theories=new Set(items.map(theorySignature));return theories.size===1?[{...items[0],labelZh:displayLabel(machine,items[0])}]:[]})}
export function getEstimatorReadiness(machine:Machine,session:Session):EstimatorReadiness{
  const benchmarks=activeSettingBenchmarks(machine);
  if(!benchmarks.length)return{status:"no_benchmark",title:"目前沒有可計算的設定資料",summary:"來源可能沒有完整設定 1～6 數值，或數值無法安全對應到這個 Session 的記錄按鈕。",items:[]};
  const items=benchmarks.map(benchmark=>{const observation=benchmark.observation;if(observation.type==="rate"){const count=counterNumber(session,observation.numeratorKey),denominator=metricValue(session,machine,observation.denominatorMetricKey),sample=`${denominator.toLocaleString()} / ${benchmark.minimumSample.toLocaleString()} G · ${count} 次`,next=denominator<=0?"先設定起始 G，遊玩後再更新目前 G":denominator<benchmark.minimumSample?`還需要 ${Math.max(0,benchmark.minimumSample-denominator).toLocaleString()} G`:count<=0?`尚未記錄「${benchmark.labelZh}」對應事件`:"已可參與設定參考";return{id:benchmark.id,label:benchmark.labelZh,sample,next}}if(observation.type==="trialOutcome"){const count=(session.trials[observation.relationshipId]??[]).filter(item=>item.outcome!=="pending").length;return{id:benchmark.id,label:benchmark.labelZh,sample:`${count} / ${benchmark.minimumSample} 次 trial`,next:count<benchmark.minimumSample?`還需要 ${benchmark.minimumSample-count} 次明確結果`:"已可參與設定參考"}}const selected=session.counters[observation.counterKey]===observation.equals;return{id:benchmark.id,label:benchmark.labelZh,sample:selected?"已記錄":"尚未記錄",next:selected?"已可參與設定參考":"等待對應的設定示唆選擇"}}),ready=items.some(item=>item.next==="已可參與設定參考");
  return{status:ready?"ready":"collecting",title:ready?"已有可用觀測資料":"正在累積可用樣本",summary:ready?"設定參考會使用已達條件的項目即時更新。":"依下方進度繼續記錄；未達條件前不會顯示假精準分布。",items};
}
export function estimateSettings(machine:Machine,session:Session):EstimatorResult{const benchmarks=activeSettingBenchmarks(machine);let scores=SETTINGS.map(()=>0);const evidence:EstimatorEvidence[]=[];let confidenceWeight=0;for(const benchmark of benchmarks){const result=evidenceLogLikelihood(benchmark,session,machine);if(!result)continue;const before=normalize(scores);scores=scores.map((score,index)=>score+result.log[index]);const after=normalize(scores),impact=distance(before,after)*100,lowDelta=(after[1]+after[2])-(before[1]+before[2]),highDelta=(after[5]+after[6])-(before[5]+before[6]),direction=Math.abs(highDelta)<.005&&Math.abs(lowDelta)<.005?"影響有限":highDelta>Math.abs(lowDelta)?"偏向高設定側":lowDelta>Math.abs(highDelta)?"偏向低設定側":"主要調整中間分布";evidence.push({id:benchmark.id,label:benchmark.labelZh,observation:result.observation,impact,direction});confidenceWeight+=result.strength}const distribution=normalize(scores),confidenceScore=Math.min(1,confidenceWeight/2.25),confidence=confidenceScore<.35?"low":confidenceScore<.75?"medium":"high";return{status:evidence.length?"estimating":"not_started",distribution,groups:{low:distribution[1]+distribution[2],mid:distribution[3]+distribution[4],high:distribution[5]+distribution[6]},confidence,confidenceScore,evidence}}
