import type { Machine, Session, SettingBenchmark } from "@/types";
const SETTINGS=[1,2,3,4,5,6] as const;
type Distribution=Record<(typeof SETTINGS)[number],number>;
export type EstimatorEvidence={id:string;label:string;observation:string;impact:number;direction:string};
export type EstimatorResult={distribution:Distribution;groups:{low:number;mid:number;high:number};confidence:"low"|"medium"|"high";confidenceScore:number;evidence:EstimatorEvidence[]};
function metricValue(session:Session,machine:Machine,key:string){const definition=machine.profile.measurementMetrics.find(item=>item.key===key);if(!definition)return session.metrics[key]??0;const source=definition.source;if(source.type==="trackerDelta"){const baseline=session.trackerBaselines[source.trackerKey];return baseline===undefined?0:Math.max(0,(session.trackers[source.trackerKey]??0)-baseline)}if(source.type==="custom")return session.metrics[source.sessionMetricKey]??0;return session.metrics[source.type]??0}
function normalize(logScores:number[]):Distribution{const max=Math.max(...logScores),raw=logScores.map(score=>Math.exp(score-max)),total=raw.reduce((sum,value)=>sum+value,0);return Object.fromEntries(SETTINGS.map((setting,index)=>[setting,raw[index]/total])) as Distribution}
function distance(a:Distribution,b:Distribution){return SETTINGS.reduce((sum,s)=>sum+Math.abs(a[s]-b[s]),0)/2}
function counterNumber(session:Session,key:string){if(key==="cz")return session.czCount;if(key==="at")return session.atCount;const value=session.counters[key];return typeof value==="number"?value:0}
function evidenceLogLikelihood(benchmark:SettingBenchmark,session:Session,machine:Machine){const observation=benchmark.observation;if(observation.type==="rate"){const count=counterNumber(session,observation.numeratorKey),denominator=metricValue(session,machine,observation.denominatorMetricKey);if(denominator<=0)return null;const strength=Math.min(1,denominator/benchmark.minimumSample),log=SETTINGS.map(setting=>{const expected=benchmark.settingValues[setting];if(!expected||expected<=0)return-30;const p=observation.valueMode==="oneIn"?1/expected:expected,lambda=Math.max(.000001,denominator*p);return strength*(count*Math.log(lambda)-lambda)});return{log,strength,observation:`${count} 次 / ${denominator}G${count>0?` → 1/${(denominator/count).toFixed(1)}`:" → 尚無比率"}`}}if(observation.type==="trialOutcome"){const records=(session.trials[observation.relationshipId]??[]).filter(item=>item.outcome!=="pending");if(records.length===0)return null;const success=records.filter(item=>item.outcome==="success").length,strength=Math.min(1,records.length/benchmark.minimumSample),log=SETTINGS.map(setting=>{const p=Math.min(.999999,Math.max(.000001,benchmark.settingValues[setting]??.000001));return strength*(success*Math.log(p)+(records.length-success)*Math.log(1-p))});return{log,strength,observation:`${success} / ${records.length} → ${(success/records.length*100).toFixed(1)}%`}}if(session.counters[observation.counterKey]!==observation.equals)return null;return{log:SETTINGS.map(setting=>Math.log(Math.max(.000001,benchmark.settingValues[setting]??.000001))),strength:1,observation:benchmark.labelZh}}
export function activeSettingBenchmarks(machine:Machine){return machine.profile.benchmarks.filter(item=>item.verified&&(machine.guideStatus?!item.testData:machine.profileStatus==="verified"?!item.testData:item.testData))}
export function estimateSettings(machine:Machine,session:Session):EstimatorResult{const benchmarks=activeSettingBenchmarks(machine);let scores=SETTINGS.map(()=>0);const evidence:EstimatorEvidence[]=[];let confidenceWeight=0;for(const benchmark of benchmarks){const result=evidenceLogLikelihood(benchmark,session,machine);if(!result)continue;const before=normalize(scores);scores=scores.map((score,index)=>score+result.log[index]);const after=normalize(scores),impact=distance(before,after)*100,lowDelta=(after[1]+after[2])-(before[1]+before[2]),highDelta=(after[5]+after[6])-(before[5]+before[6]),direction=Math.abs(highDelta)<.005&&Math.abs(lowDelta)<.005?"影響有限":highDelta>Math.abs(lowDelta)?"偏向高設定側":lowDelta>Math.abs(highDelta)?"偏向低設定側":"主要調整中間分布";evidence.push({id:benchmark.id,label:benchmark.labelZh,observation:result.observation,impact,direction});confidenceWeight+=result.strength}const distribution=normalize(scores),confidenceScore=Math.min(1,confidenceWeight/2.25),confidence=confidenceScore<.35?"low":confidenceScore<.75?"medium":"high";return{distribution,groups:{low:distribution[1]+distribution[2],mid:distribution[3]+distribution[4],high:distribution[5]+distribution[6]},confidence,confidenceScore,evidence}}
