import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import { estimateSettings } from "../src/lib/settingEstimator.ts";import { createSessionSnapshot } from "../src/lib/sessionModes.ts";
import { parsePWorldMachineGuide } from "../src/lib/machine-guide/pworld.ts";import { buildControlManifest } from "../src/lib/machine-guide/controlManifest.ts";import { machineFromGuide } from "../src/lib/machine-guide/session.ts";import { buildSessionUiModel } from "../src/lib/sessionUi.ts";import { withCustomRecords } from "../src/lib/customRecords.ts";import type { MachineCatalogRecord } from "../src/types/catalog.ts";
const fixture=(name:string)=>fs.readFileSync(new URL(`./fixtures/${name}`,import.meta.url),"utf8"),base:MachineCatalogRecord={id:"machine-test",officialNameJa:"TEST DATA",displayNameZh:"",manufacturer:"TEST",brand:"",seriesName:"",aliases:[],machineType:"パチスロ",introducedAt:null,sourceName:"P-WORLD",sourceUrl:"https://www.p-world.co.jp/machine/database/test",retrievedAt:"2026-08-29",verified:false,catalogStatus:"imported",sources:[]};
function guide(file:string,id:string,name:string){return parsePWorldMachineGuide(fixture(file),{...base,id,officialNameJa:name,sourceUrl:`https://www.p-world.co.jp/machine/database/${id}`} ,"2026-08-29T00:00:00Z")}
function manifest(file:string,id:string,name:string){const g=guide(file,id,name);return{g,items:buildControlManifest(g.sessionCapabilities,g.smartCounters,g.recordableEvents,g.states,g.sections.flatMap(section=>section.tables.map(table=>table.id)))}}
test("LB Triple Crown is evidence-classified A-type with separate BIG and REG",()=>{const {g,items}=manifest("pworld-10542-a-type-bonus.html","10542","LBトリプルクラウンX-300");assert.equal(g.machineType,"a_type");assert.match(g.familyClassification?.evidence[0]??"",/BB／RB/);assert.deepEqual(items.filter(item=>item.availability==="operational"&&item.controlType==="counter").map(item=>item.label).sort(),["BIG BONUS","REG BONUS"]);assert.equal(items.some(item=>item.eventType==="cz"||item.eventType==="at"),false);assert.equal(items.filter(item=>item.observationKey==="bonusTotal").length,1)});
test("derived bonus total is not another input or estimator observation",()=>{const {items}=manifest("pworld-10542-a-type-bonus.html","10542","LBトリプルクラウンX-300"),derived=items.find(item=>item.observationKey==="bonusTotal");assert.equal(derived?.controlType,"derived_metric");assert.equal(derived?.estimatorUsable,false)});
test("Yajikita exposes proven CZ AT choice and keeps mile data out of controls",()=>{const {g,items}=manifest("pworld-10489-zone-at.html","10489","スマスロ やじきた道中記参る!");assert.equal(g.machineType,"multi_zone_at");assert.ok(items.some(item=>item.eventType==="cz"&&item.availability==="operational"));assert.ok(items.some(item=>item.eventType==="at"&&item.availability==="operational"));assert.ok(items.some(item=>item.controlType==="choice"&&item.choices?.length===2));assert.equal(items.some(item=>/まいる/.test(item.label)&&item.availability==="operational"),false)});
test("unknown guide safely keeps total G and creates no generic CZ AT",()=>{const g=guide("pworld-10513-a-type.html","unknown","TEST DATA unknown"),m=machineFromGuide({...g,machineType:"generic",sessionCapabilities:g.sessionCapabilities.filter(item=>item.moduleKind==="total_games"||item.moduleKind==="normal_games"),smartCounters:[]});const ui=buildSessionUiModel(m);assert.equal(ui.basicMode,true);assert.equal(ui.recordControls.length,0);assert.equal(ui.showGenericCz||ui.showGenericAt,false)});
test("custom controls are reusable but never estimator-eligible",()=>{const g=guide("pworld-10513-a-type.html","10513","TEST DATA A-type"),m=withCustomRecords(machineFromGuide(g),[{id:"mine",machineId:`guide:${g.catalogId}`,name:"我的事件",type:"counter",choices:[],quick:true}]),custom=m.profile.sessionCapabilities?.find(item=>item.observationKey==="custom:mine");assert.equal(custom?.status,"operational");assert.equal(custom?.estimatorUsable,false);assert.equal(buildSessionUiModel(m).recordControls.some(item=>item.id==="custom:mine"),true)});
test("estimator waits for an observed numerator and minimum denominator sample",()=>{const g=guide("pworld-10542-a-type-bonus.html","10542","LBトリプルクラウンX-300"),m=machineFromGuide(g),session=createSessionSnapshot(m,"quick","",undefined,{sessionId:"s",eventId:"e",now:"2026-08-29T00:00:00Z"});session.metrics.observedTotalGame=599;assert.equal(estimateSettings(m,session).status,"not_started");session.counters["event:big-bonus"]=1;assert.equal(estimateSettings(m,session).status,"not_started");session.metrics.observedTotalGame=600;assert.equal(estimateSettings(m,session).status,"estimating")});
