import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import { estimateSettings } from "../src/lib/settingEstimator.ts";import { createSessionSnapshot } from "../src/lib/sessionModes.ts";
import { parsePWorldMachineGuide } from "../src/lib/machine-guide/pworld.ts";import { buildControlManifest } from "../src/lib/machine-guide/controlManifest.ts";import { machineFromGuide } from "../src/lib/machine-guide/session.ts";import { buildSessionUiModel } from "../src/lib/sessionUi.ts";import { CUSTOM_RECORDS_KEY, deleteCustomRecord, loadCustomRecords, replaceCustomRecord, saveCustomRecord, validateCustomRecord, withCustomRecords, type CustomRecordDefinition } from "../src/lib/customRecords.ts";import type { MachineCatalogRecord } from "../src/types/catalog.ts";
const fixture=(name:string)=>fs.readFileSync(new URL(`./fixtures/${name}`,import.meta.url),"utf8"),base:MachineCatalogRecord={id:"machine-test",officialNameJa:"TEST DATA",displayNameZh:"",manufacturer:"TEST",brand:"",seriesName:"",aliases:[],machineType:"パチスロ",introducedAt:null,sourceName:"P-WORLD",sourceUrl:"https://www.p-world.co.jp/machine/database/test",retrievedAt:"2026-08-29",verified:false,catalogStatus:"imported",sources:[]};
function guide(file:string,id:string,name:string){return parsePWorldMachineGuide(fixture(file),{...base,id,officialNameJa:name,sourceUrl:`https://www.p-world.co.jp/machine/database/${id}`} ,"2026-08-29T00:00:00Z")}
function manifest(file:string,id:string,name:string){const g=guide(file,id,name);return{g,items:buildControlManifest(g.sessionCapabilities,g.smartCounters,g.recordableEvents,g.states,g.sections.flatMap(section=>section.tables.map(table=>table.id)))}}
test("LB Triple Crown is evidence-classified A-type with separate BIG and REG",()=>{const {g,items}=manifest("pworld-10542-a-type-bonus.html","10542","LBトリプルクラウンX-300");assert.equal(g.machineType,"a_type");assert.match(g.familyClassification?.evidence[0]??"",/BB／RB/);assert.deepEqual(items.filter(item=>item.availability==="operational"&&item.controlType==="counter").map(item=>item.label).sort(),["BIG BONUS","REG BONUS"]);assert.equal(items.some(item=>item.eventType==="cz"||item.eventType==="at"),false);assert.equal(items.filter(item=>item.observationKey==="bonusTotal").length,1)});
test("derived bonus total is not another input or estimator observation",()=>{const {items}=manifest("pworld-10542-a-type-bonus.html","10542","LBトリプルクラウンX-300"),derived=items.find(item=>item.observationKey==="bonusTotal");assert.equal(derived?.controlType,"derived_metric");assert.equal(derived?.estimatorUsable,false)});
test("Yajikita exposes proven CZ AT choice and keeps mile data out of controls",()=>{const {g,items}=manifest("pworld-10489-zone-at.html","10489","スマスロ やじきた道中記参る!");assert.equal(g.machineType,"multi_zone_at");assert.ok(items.some(item=>item.eventType==="cz"&&item.availability==="operational"));assert.ok(items.some(item=>item.eventType==="at"&&item.availability==="operational"));assert.ok(items.some(item=>item.controlType==="choice"&&item.choices?.length===2));assert.equal(items.some(item=>/まいる/.test(item.label)&&item.availability==="operational"),false)});
test("unknown guide safely keeps total G and creates no generic CZ AT",()=>{const g=guide("pworld-10513-a-type.html","unknown","TEST DATA unknown"),m=machineFromGuide({...g,machineType:"generic",sessionCapabilities:g.sessionCapabilities.filter(item=>item.moduleKind==="total_games"||item.moduleKind==="normal_games"),smartCounters:[]});const ui=buildSessionUiModel(m);assert.equal(ui.basicMode,true);assert.equal(ui.recordControls.length,0);assert.equal(ui.showGenericCz||ui.showGenericAt,false)});
test("custom controls are reusable but never estimator-eligible",()=>{const g=guide("pworld-10513-a-type.html","10513","TEST DATA A-type"),m=withCustomRecords(machineFromGuide(g),[{id:"mine",machineId:`guide:${g.catalogId}`,name:"我的事件",type:"counter",choices:[],quick:true}]),custom=m.profile.sessionCapabilities?.find(item=>item.observationKey==="custom:mine");assert.equal(custom?.status,"operational");assert.equal(custom?.estimatorUsable,false);assert.equal(buildSessionUiModel(m).recordControls.some(item=>item.id==="custom:mine"),true)});
test("rate-only unknown machine enters basic mode without invented CZ or AT",()=>{const g=guide("pworld-10514-insufficient-events.html","10514","L ULTRAMAN 最終決戰"),ui=buildSessionUiModel(machineFromGuide(g));assert.equal(g.machineType,"cz_at");assert.equal(g.states.some(item=>item.type==="chance_zone"||item.type==="at"),false);assert.equal(g.sessionCapabilities.some(item=>item.moduleKind==="named_cz"||item.moduleKind==="at"),false);assert.equal(ui.basicMode,true);assert.equal(ui.recordControls.length,0);assert.equal(g.beginnerGuide.keyThings.some(item=>/CZ|AT/.test(item.labelJa)),false)});
test("custom counter and choice persist, update the current snapshot, and stay outside estimator",()=>{const memory=new Map<string,string>();Object.defineProperty(globalThis,"window",{configurable:true,value:{localStorage:{getItem:(key:string)=>memory.get(key)??null,setItem:(key:string,value:string)=>memory.set(key,value)}}});const machine=machineFromGuide(guide("pworld-10514-insufficient-events.html","custom-machine","TEST DATA custom")),counter:CustomRecordDefinition={id:"counter",machineId:machine.id,name:"特殊畫面",type:"counter",choices:[],quick:true},choice:CustomRecordDefinition={id:"choice",machineId:machine.id,name:"自訂示唆",type:"choice",choices:["A","B"],quick:false};assert.equal(saveCustomRecord(counter),true);assert.equal(saveCustomRecord(choice),true);assert.deepEqual(loadCustomRecords(machine.id).map(item=>item.id),["counter","choice"]);let snapshot=replaceCustomRecord(machine,counter);snapshot=replaceCustomRecord(snapshot,choice);const controls=buildSessionUiModel(snapshot).recordControls;assert.ok(controls.some(item=>item.id==="custom:counter"));assert.ok(controls.some(item=>item.id==="custom:choice"&&item.counter?.choices?.length===2));assert.equal(snapshot.profile.sessionCapabilities?.filter(item=>item.moduleKind==="custom_event").every(item=>!item.estimatorUsable),true);assert.equal(snapshot.profile.benchmarks.some(item=>item.metricKey.startsWith("custom:")),false);const edited={...counter,name:"特殊畫面（修改）"};snapshot=replaceCustomRecord(snapshot,edited);assert.equal(snapshot.profile.smartCounters.find(item=>item.key==="custom:counter")?.labelZh,edited.name);assert.equal(deleteCustomRecord(machine.id,counter.id),true);assert.equal(loadCustomRecords(machine.id).some(item=>item.id===counter.id),false);assert.ok(snapshot.profile.smartCounters.some(item=>item.key==="custom:counter"));memory.delete(CUSTOM_RECORDS_KEY);Reflect.deleteProperty(globalThis,"window")});
test("custom choice requires at least two options",()=>{assert.equal(validateCustomRecord({name:"畫面",type:"choice",choices:["A"]}),"Choice 至少需要兩個選項");assert.equal(validateCustomRecord({name:"畫面",type:"choice",choices:["A","B"]}),null)});
test("estimator waits for an observed numerator and minimum denominator sample",()=>{const g=guide("pworld-10542-a-type-bonus.html","10542","LBトリプルクラウンX-300"),m=machineFromGuide(g),session=createSessionSnapshot(m,"quick","",undefined,{sessionId:"s",eventId:"e",now:"2026-08-29T00:00:00Z"});session.metrics.observedTotalGame=599;assert.equal(estimateSettings(m,session).status,"not_started");session.counters["event:big-bonus"]=1;assert.equal(estimateSettings(m,session).status,"not_started");session.metrics.observedTotalGame=600;assert.equal(estimateSettings(m,session).status,"estimating")});
