import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {classifyPachinkoType,searchPachinkoCatalog} from "../src/lib/pachinko/catalog.ts";
import {parsePWorldPachinkoCalendar,parsePWorldPachinkoFullGuide,parsePWorldPachinkoGuide} from "../src/lib/pachinko/pworld.ts";
import {buildRuleBasedPachinkoGuide,pachinkoGuideSchema,validatePachinkoChineseGuide} from "../src/lib/pachinko/chineseGuide.ts";
import {pachinkoSessionSummary} from "../src/lib/pachinko/storage.ts";
import type {PachinkoCatalogRecord,PachinkoSession} from "../src/types/pachinko.ts";

const record:PachinkoCatalogRecord={id:"pachi-10504",officialNameJa:"e 甲鉄城のカバネリ2",displayNameZh:"甲鐵城的卡巴內里2",manufacturer:"サミー",seriesName:"甲鉄城のカバネリ",aliases:["卡巴內里"],machineType:"smart_pachinko",tags:["LT"],introducedAt:"2026-09-07",sourceName:"P-WORLD",sourceUrl:"https://www.p-world.co.jp/machine/database/10504",retrievedAt:"2026-09-21T00:00:00Z",catalogStatus:"imported"};

test("Pachinko catalog classifies independently and searches Chinese aliases",()=>{assert.equal(classifyPachinkoType("e 新台"),"smart_pachinko");assert.equal(classifyPachinkoType("PHはねもの ハネ釈迦"),"hanemono");assert.equal(searchPachinkoCatalog([record],"卡巴內里").length,1)});

test("P-WORLD calendar parser reads only the Pachinko grid",()=>{const html=`<div class="machineList js-machineList" data-yyyymmdd="20260907"><ul class="machineList-grid machineList-grid--pachi"><li class="machineList-item"><div class="machineList-item-title"><a href="/machine/database/10504">e 甲鉄城のカバネリ2</a></div><div class="machineList-item-maker">サミー</div><div class="machineList-item-thumb"><img src="/cover.jpg"></div></li></ul><ul class="machineList-grid machineList-grid--slot"><li class="machineList-item"><div class="machineList-item-title"><a href="/machine/database/99999">SLOT TEST</a></div></li></ul></div>`;const records=parsePWorldPachinkoCalendar(html,"https://www.p-world.co.jp/database/calendar","2026-09-21T00:00:00Z");assert.equal(records.length,1);assert.equal(records[0].id,"pachi-10504");assert.equal(records[0].introducedAt,"2026-09-07");assert.equal(records[0].catalogStatus,"imported")});

test("Pachinko guide extracts public spec facts without predictive claims",()=>{const html=`<table><tr><th>大当り確率</th><td>1/119.8</td></tr><tr><th>RUSH突入率</th><td>約50%</td></tr><tr><th>RUSH継続率</th><td>約80%</td></tr></table><span class="kisyuTag-pachiType">LT</span><p>右打</p>`;const guide=parsePWorldPachinkoGuide(html,record,"2026-09-21T00:00:00Z");assert.equal(guide.status,"usable");assert.ok(guide.facts.some(item=>item.labelZh==="大當機率"&&item.value.includes("1/119.8")));assert.ok(guide.gameFlow.some(item=>item.includes("Lucky Trigger")));assert.ok(guide.playNotes.every(item=>!item.includes("必中")))});

test("Pachinko summary calculates observed rotations only",()=>{const session:PachinkoSession={id:"test",catalogId:record.id,machineName:record.displayNameZh,machineNumber:"1",startedAt:"2026-09-21T00:00:00Z",status:"completed",playState:"normal",startSpins:80,currentSpins:280,investmentYen:10000,heldBalls:0,initialHits:1,rushEntries:1,rushHits:3,maxRushStreak:3,currentRushStreak:3,note:"TEST DATA"};assert.deepEqual(pachinkoSessionSummary(session),{spins:200,rotationsPerThousand:20})});

test("full Pachinko guide keeps sections, tables and official-scope images outside BBS",()=>{const html=`<h3>機種情報</h3><h4>基本スペック</h4><div class="articleBox-content"><p>大当り確率は約1/119.8。</p><table><tr><th>大当り確率</th><th>通常時</th></tr><tr><td>通常時</td><td>約1/119.8</td></tr></table></div><h4>ゲームフロー</h4><div class="articleBox-content"><p>初当り後にRUSH突入を判定する。</p><img width="590" height="800" alt="ゲームフロー" data-original="https://machine-image.p-world.co.jp/uploads/test-flow.jpg"></div><h4>大当り割合</h4><p>ヘソと電チューで割合が異なる。</p><h2>掲示板</h2><h4>ゲームフロー</h4><img width="590" height="800" src="https://idn.p-world.co.jp/kisyubbs/photo/post.jpg">`;const guide=parsePWorldPachinkoFullGuide(html,record,"2026-09-21T00:00:00Z");assert.equal(guide.schemaVersion,1);assert.ok(guide.sections.some(section=>section.key==="features"&&section.tables.length===1));assert.equal(guide.images.length,1);assert.match(guide.images[0].sourceImageUrl,/test-flow\.jpg/);assert.ok(!JSON.stringify(guide).includes("kisyubbs"))});

test("Pachinko Chinese guide fallback is grounded and validator rejects invented numbers",()=>{const guide=parsePWorldPachinkoFullGuide(`<h4>基本スペック</h4><p>大当り確率は約1/119.8。</p><h4>ゲームフロー</h4><p>初当り後にRUSH突入を判定する。</p><h4>大当り割合</h4><p>通常時は300個。</p>`,record,"2026-09-21T00:00:00Z"),fallback=buildRuleBasedPachinkoGuide(guide);assert.equal(fallback.generator,"rules");assert.equal(validatePachinkoChineseGuide({...fallback,generator:"openai",overview:"大當機率約1/999。"},guide),false)});
test("Pachinko Chinese guide accepts thousands separators without weakening numeric grounding",()=>{const guide=parsePWorldPachinkoFullGuide(`<h4>基本スペック</h4><p>右打ち中は1500個。</p>`,record,"2026-09-21T00:00:00Z"),fallback=buildRuleBasedPachinkoGuide(guide),candidate={...fallback,generator:"openai"as const,overview:"右打中為 1,500 玉。"};assert.equal(validatePachinkoChineseGuide(candidate,guide),true)});
test("Pachinko AI schema only permits sections present in the source",()=>{const schema=pachinkoGuideSchema(["features","flow"]),sectionKey=(schema.properties.sections.items.properties.key as{enum:string[]});assert.deepEqual(sectionKey.enum,["features","flow"]);assert.equal(sectionKey.enum.includes("play"),false)});

test("Pachinko architecture uses independent catalog, play log, guide cache and route",()=>{const repository=fs.readFileSync(new URL("../src/lib/pachinko/repository.server.ts",import.meta.url),"utf8"),storage=fs.readFileSync(new URL("../src/lib/pachinko/storage.ts",import.meta.url),"utf8"),guideStorage=fs.readFileSync(new URL("../src/lib/pachinko/guideStorage.ts",import.meta.url),"utf8"),detail=fs.readFileSync(new URL("../src/app/pachinko/[id]/page.tsx",import.meta.url),"utf8");assert.match(repository,/pachinko_catalog_records/);assert.match(storage,/pachinko-sessions-v1/);assert.match(guideStorage,/pachinko-guides/);assert.match(detail,/kind=pachinko/);assert.match(detail,/PachinkoGuideActions/)});
