import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { PLAYER_LIBRARY_KEY,loadPlayerLibrary,recordCatalogView,recentPlayedCatalogIds,setCatalogFavorite } from "../src/lib/playerLibrary.ts";
import {PACHINKO_PLAYER_LIBRARY_KEY,loadPachinkoPlayerLibrary,recordPachinkoCatalogView,recentPlayedPachinkoCatalogIds,setPachinkoCatalogFavorite} from "../src/lib/pachinko/playerLibrary.ts";
import { observedGame,recordSummary,sessionsInRange } from "../src/lib/records.ts";
import type { Session } from "../src/types/index.ts";
import type {PachinkoSession} from "../src/types/pachinko.ts";

function browserStorage(){const memory=new Map<string,string>();const descriptor=Object.getOwnPropertyDescriptor(globalThis,"window");Object.defineProperty(globalThis,"window",{configurable:true,value:{localStorage:{getItem:(key:string)=>memory.get(key)??null,setItem:(key:string,value:string)=>memory.set(key,value)}}});return{memory,restore(){if(descriptor)Object.defineProperty(globalThis,"window",descriptor);else Reflect.deleteProperty(globalThis,"window")}}}
function session(id:string,machineId:string,startedAt:string,patch:Partial<Session>={}):Session{return{id,machineId,machineNumber:"1",startedAt,startG:0,actualG:0,displayG:0,investmentYen:0,medals:0,czCount:0,atCount:0,gameState:"normal",trackers:{dataGame:0},trackerBaselines:{dataGame:0},metrics:{observedTotalGame:0,observedNormalGame:0},trials:{},status:"completed",counters:{},events:[],...patch}}

test("favorites and recent views stay browser-local and deduplicated",()=>{const mock=browserStorage();setCatalogFavorite("machine-a",true);setCatalogFavorite("machine-b",true);setCatalogFavorite("machine-a",false);recordCatalogView("machine-a","2026-08-29T01:00:00Z");recordCatalogView("machine-b","2026-08-29T02:00:00Z");recordCatalogView("machine-a","2026-08-29T03:00:00Z");const state=loadPlayerLibrary();assert.deepEqual(state.favoriteCatalogIds,["machine-b"]);assert.deepEqual(state.recentViews.map(item=>item.catalogId),["machine-a","machine-b"]);assert.ok(mock.memory.has(PLAYER_LIBRARY_KEY));mock.restore()});
test("recently played machines use catalog snapshot and never carry session counts",()=>{const sessions=[session("s1","guide:machine-a","2026-08-28T00:00:00Z"),session("s2","legacy-machine","2026-08-29T00:00:00Z",{profileSnapshot:{catalogId:"machine-b"} as Session["profileSnapshot"]}),session("s3","guide:machine-a","2026-08-30T00:00:00Z")];assert.deepEqual(recentPlayedCatalogIds(sessions),["machine-a","machine-b"])});
test("Pachinko favorites and recent play stay in their own browser-local library",()=>{const mock=browserStorage(),base={machineName:"TEST",machineNumber:"1",status:"completed"as const,playState:"normal"as const,startSpins:0,currentSpins:0,investmentYen:0,heldBalls:0,initialHits:0,rushEntries:0,rushHits:0,maxRushStreak:0,currentRushStreak:0,note:""},sessions=[{...base,id:"p1",catalogId:"pachi-a",startedAt:"2026-09-20T00:00:00Z"},{...base,id:"p2",catalogId:"pachi-b",startedAt:"2026-09-21T00:00:00Z"}]satisfies PachinkoSession[];setPachinkoCatalogFavorite("pachi-a",true);recordPachinkoCatalogView("pachi-b","2026-09-21T01:00:00Z");assert.deepEqual(loadPachinkoPlayerLibrary().favoriteCatalogIds,["pachi-a"]);assert.deepEqual(recentPlayedPachinkoCatalogIds(sessions),["pachi-b","pachi-a"]);assert.ok(mock.memory.has(PACHINKO_PLAYER_LIBRARY_KEY));assert.notEqual(PACHINKO_PLAYER_LIBRARY_KEY,PLAYER_LIBRARY_KEY);mock.restore()});
test("record range and summary use observed Session G",()=>{const now=new Date("2026-08-29T12:00:00+08:00"),sessions=[session("today","a","2026-08-29T03:00:00Z",{metrics:{observedTotalGame:320,observedNormalGame:300},investmentYen:5000,medals:200}),session("week","b","2026-08-25T03:00:00Z",{metrics:{observedTotalGame:180,observedNormalGame:180},investmentYen:2000,medals:80}),session("old","c","2026-08-01T03:00:00Z")];assert.equal(sessionsInRange(sessions,"today",now).length,1);assert.equal(sessionsInRange(sessions,"7days",now).length,2);assert.equal(sessionsInRange(sessions,"all",now).length,3);assert.equal(observedGame(sessions[0]),320);assert.deepEqual(recordSummary(sessions.slice(0,2)),{sessions:2,active:0,totalGame:500,investment:7000,medals:280})});
test("Catalog Library exposes lazy same-origin covers, favorites, recent play and player guide status",()=>{const source=fs.readFileSync(new URL("../src/app/catalog/CatalogLibraryClient.tsx",import.meta.url),"utf8"),cover=fs.readFileSync(new URL("../src/components/CatalogCoverImage.tsx",import.meta.url),"utf8");assert.match(source,/我的收藏/);assert.match(source,/最近打過/);assert.match(source,/已有指南/);assert.match(source,/catalog-card-grid/);assert.match(source,/setCatalogFavorite/);assert.match(source,/CatalogCoverImage/);assert.match(cover,/\/api\/catalog-covers\//);assert.match(cover,/loading="lazy"/);assert.match(cover,/onError/);assert.doesNotMatch(cover,/<img[^>]+sourceImageUrl/)});
test("Catalog detail and Machine Guide return through the Catalog hierarchy",()=>{const detail=fs.readFileSync(new URL("../src/app/catalog/[id]/page.tsx",import.meta.url),"utf8"),guide=fs.readFileSync(new URL("../src/app/guides/[catalogId]/page.tsx",import.meta.url),"utf8");assert.match(detail,/backHref="\/catalog"/);assert.match(detail,/返回機種資料庫/);assert.match(guide,/backHref=\{`\/catalog\/\$\{catalogId\}`\}/);assert.match(guide,/返回機種詳細/)});
test("full Machine Guide has quick navigation and shared glossary without exposing source images",()=>{const guide=fs.readFileSync(new URL("../src/components/MachineGuideView.tsx",import.meta.url),"utf8"),glossary=fs.readFileSync(new URL("../src/app/glossary/page.tsx",import.meta.url),"utf8");for(const anchor of ["guide-basics","guide-highlights","guide-records","guide-details"])assert.match(guide,new RegExp(anchor));for(const term of ["通常時","CZ","AT","ART","Bonus","天井","設定示唆"])assert.match(glossary,new RegExp(term));assert.doesNotMatch(glossary,/sourceImageUrl|<Image|<img/)});
