import assert from "node:assert/strict";
import test from "node:test";
import { machines } from "../src/data/machines.ts";
import { addSourceToDraft,applyExtraction,approveProfileDraft,createProfileDraft,missingMetrics,realEstimatorBenchmarks,resolveDraftMetric,reviewDraftEvidence,reviewSmartCounterSuggestion,unresolvedMetricCount } from "../src/lib/profile-builder/core.ts";
import type { SettingBenchmark } from "../src/types/index.ts";
import type { ExtractedProfileData,ProfileDraft } from "../src/types/profileBuilder.ts";

const empty=():ExtractedProfileData=>({gameFlow:null,czInitialRate:null,atInitialRate:null,smallRoleSettingDifferences:null,triggerSuccessRate:null,ceiling:null,zone:null,reset:null,endScreenIndications:null,trophySettingIndications:null,playGuide:null});
const extraction=(url:string,data:Partial<ExtractedProfileData>)=>({sourceName:"TEST SOURCE",sourceUrl:url,retrievedAt:"2026-08-27T00:00:00.000Z",confidence:.8,data:{...empty(),...data},labels:{}});
const withSource=(draft:ProfileDraft,url:string)=>addSourceToDraft(draft,url,"TEST SOURCE","2026-08-27T00:00:00.000Z");

test("Catalog only → 建立 draft",()=>{const draft=createProfileDraft("catalog-only",undefined,"2026-08-27");assert.equal(draft.status,"draft");assert.equal(draft.basedOnStatus,"catalog-only")});
test("placeholder → 重建 draft 且不刪現有 Profile",()=>{const machine=machines.find(item=>item.id==="tokyo-ghoul")!;const draft=createProfileDraft("tokyo-ghoul",machine,"2026-08-27");assert.equal(machine.profileStatus,"placeholder");assert.equal(draft.basedOnStatus,"placeholder");assert.equal(draft.machineId,machine.id)});
test("相同 Catalog 不產生不同 Profile identity",()=>{assert.equal(createProfileDraft("tokyo-ghoul").id,createProfileDraft("tokyo-ghoul").id)});
test("加入 source URL 且重複 URL 不重複",()=>{let draft=createProfileDraft("x");draft=addSourceToDraft(draft,"https://example.com/a");draft=addSourceToDraft(draft,"https://example.com/a");assert.equal(draft.sources.length,1)});
test("extraction 支援 partial data",()=>{let draft=withSource(createProfileDraft("x"),"https://example.com/a");draft=applyExtraction(draft,extraction("https://example.com/a",{czInitialRate:"1/TEST"}));assert.equal(draft.metrics.length,1);assert.equal(draft.metrics[0].metricKey,"czInitialRate")});
test("missing metric 維持 null",()=>{const data={...empty(),gameFlow:"通常 → CZ"};assert.ok(missingMetrics(data).includes("atInitialRate"));assert.equal(data.atInitialRate,null)});
test("two sources agree",()=>{let draft=withSource(createProfileDraft("x"),"https://a.example/a");draft=applyExtraction(draft,extraction("https://a.example/a",{czInitialRate:"1/TEST"}));draft=withSource(draft,"https://b.example/b");draft=applyExtraction(draft,extraction("https://b.example/b",{czInitialRate:"1/TEST"}));assert.equal(draft.metrics[0].verificationStatus,"agree")});
test("two sources conflict",()=>{let draft=withSource(createProfileDraft("x"),"https://a.example/a");draft=applyExtraction(draft,extraction("https://a.example/a",{atInitialRate:"1/TEST-A"}));draft=withSource(draft,"https://b.example/b");draft=applyExtraction(draft,extraction("https://b.example/b",{atInitialRate:"1/TEST-B"}));assert.equal(draft.metrics[0].verificationStatus,"conflict")});
test("conflict 不進 estimator",()=>{let draft=withSource(createProfileDraft("x"),"https://a.example/a");draft=applyExtraction(draft,extraction("https://a.example/a",{atInitialRate:"1/TEST-A"}));draft=withSource(draft,"https://b.example/b");draft=applyExtraction(draft,extraction("https://b.example/b",{atInitialRate:"1/TEST-B"}));draft=reviewDraftEvidence(draft,draft.evidence.map(item=>item.id),[]);const benchmark=realBenchmark(draft.evidence.map(item=>item.id));assert.equal(realEstimatorBenchmarks([benchmark],{...draft,status:"verified"},"verified").length,0)});
test("TEST DATA 不被當 real data",()=>{const draft={...createProfileDraft("x"),status:"verified" as const};const benchmark={...realBenchmark(["e1"]),testData:true};assert.equal(realEstimatorBenchmarks([benchmark],draft,"verified").length,0)});
test("Approve 後 status 正確",()=>{let draft=withSource(createProfileDraft("tokyo-ghoul"),"https://example.com/source");draft=applyExtraction(draft,extraction("https://example.com/source",{gameFlow:"TEST FLOW"}));draft=reviewDraftEvidence(draft,draft.evidence.map(item=>item.id),[]);assert.equal(approveProfileDraft(draft).status,"verified")});
test("Profile link / Catalog link 正確",()=>{const machine=machines.find(item=>item.id==="tokyo-ghoul")!,draft=createProfileDraft(machine.catalogId!,machine);assert.equal(draft.catalogId,machine.catalogId);assert.equal(draft.machineId,machine.id)});
test("未 verified Profile 或未 review evidence 不供應 real benchmark",()=>{let draft=withSource(createProfileDraft("x"),"https://example.com/a");draft=applyExtraction(draft,extraction("https://example.com/a",{czInitialRate:"1/TEST"}));const benchmark=realBenchmark([draft.evidence[0].id]);assert.equal(realEstimatorBenchmarks([benchmark],draft,"draft").length,0);assert.equal(realEstimatorBenchmarks([benchmark],draft,"verified").length,0)});
test("東京喰種 Golden Test：Catalog → Draft → URL → Extraction → Review → Approve",()=>{const machine=machines.find(item=>item.id==="tokyo-ghoul")!;let draft=createProfileDraft(machine.catalogId!,machine,"2026-08-27");draft=withSource(draft,"https://example.com/tokyo-ghoul");draft=applyExtraction(draft,extraction("https://example.com/tokyo-ghoul",{gameFlow:"通常 → CZ → AT",smallRoleSettingDifferences:["TEST ROLE"]}));assert.equal(draft.smartCounterSuggestions[0].approved,false);draft=reviewSmartCounterSuggestion(draft,draft.smartCounterSuggestions[0].id,true);draft=reviewDraftEvidence(draft,draft.evidence.map(item=>item.id),[]);draft=approveProfileDraft(draft);assert.equal(draft.catalogId,"tokyo-ghoul");assert.equal(draft.status,"verified");assert.equal(draft.smartCounterSuggestions[0].approved,true)});

function conflictDraft(){let draft=withSource(createProfileDraft("resolution"),"https://a.example/a");draft=applyExtraction(draft,extraction("https://a.example/a",{endScreenIndications:["A | 設定4以上"]}));draft=withSource(draft,"https://b.example/b");draft=applyExtraction(draft,extraction("https://b.example/b",{endScreenIndications:["B | 設定6"]}));return reviewDraftEvidence(draft,draft.evidence.map(item=>item.id),[])}
function tableConflictDraft(){const first={sourceName:"一撃",sourceUrl:"https://1geki.jp/a",retrievedAt:"2026-08-27",confidence:.9,status:"extracted" as const,sections:[{sectionTitle:"AT終了画面",metricKey:"endScreenIndications",sectionKey:"endScreenIndications",tableHeaders:["画面","示唆"],rows:[["A","設定4以上"]],note:null,extractedFrom:"table" as const,extractedValue:["画面 | 示唆","A | 設定4以上"],rawLabel:"AT終了画面"}]};const second={...first,sourceName:"なな徹",sourceUrl:"https://nana-press.com/b",sections:[{...first.sections[0],rows:[["B","設定6"]],extractedValue:["画面 | 示唆","B | 設定6"]}]};let draft=withSource(createProfileDraft("table-resolution"),first.sourceUrl);draft=applyExtraction(draft,first);draft=withSource(draft,second.sourceUrl);draft=applyExtraction(draft,second);return reviewDraftEvidence(draft,draft.evidence.map(item=>item.id),[])}

test("conflict blocks profile approval",()=>{const draft=conflictDraft();assert.equal(unresolvedMetricCount(draft),1);assert.throws(()=>approveProfileDraft(draft),/尚有 1 個未解決資料衝突/)});
test("incomparable blocks profile approval",()=>{const draft={...conflictDraft(),metrics:conflictDraft().metrics.map(item=>({...item,verificationStatus:"incomparable" as const}))};assert.throws(()=>approveProfileDraft(draft),/未解決資料衝突/)});
test("select source resolves conflict",()=>{const draft=conflictDraft(),selected=draft.evidence[0];const resolved=resolveDraftMetric(draft,"endScreenIndications","source_selected",[selected.id],[],"採用一撃","2026-08-27T01:00:00.000Z");assert.equal(unresolvedMetricCount(resolved),0);assert.equal(resolved.metrics[0].resolutionStatus,"source_selected");assert.deepEqual(resolved.metrics[0].selectedEvidenceIds,[selected.id]);assert.equal(resolved.metrics[0].resolvedAt,"2026-08-27T01:00:00.000Z")});
test("merge resolves conflict and records audit",()=>{const draft=tableConflictDraft(),ids=draft.evidence.map(item=>item.id);const resolved=resolveDraftMetric(draft,"endScreenIndications","merged",ids,[],"互補終了畫面");assert.equal(resolved.metrics[0].resolutionStatus,"merged");assert.deepEqual(resolved.metrics[0].mergedFromEvidenceIds,ids);assert.equal(resolved.metrics[0].mergedRows?.length,2);assert.equal(resolved.metrics[0].resolutionNote,"互補終了畫面")});
test("reject evidence resolves two-source conflict",()=>{const draft=conflictDraft(),rejected=draft.evidence[1];const resolved=resolveDraftMetric(draft,"endScreenIndications","rejected",[],[rejected.id],"來源內容不適用");assert.equal(resolved.metrics[0].resolutionStatus,"rejected");assert.equal(resolved.evidence.find(item=>item.id===rejected.id)?.reviewStatus,"rejected");assert.equal(unresolvedMetricCount(resolved),0)});
test("unresolved remains blocked",()=>{const draft=conflictDraft();assert.equal(draft.metrics[0].resolutionStatus,"unresolved");assert.throws(()=>approveProfileDraft(draft),/未解決資料衝突/)});
test("original evidence preserved after merge",()=>{const draft=tableConflictDraft(),before=structuredClone(draft.evidence),resolved=resolveDraftMetric(draft,"endScreenIndications","merged",draft.evidence.map(item=>item.id));assert.deepEqual(resolved.evidence,before)});
test("resolved metric does not alter unrelated metrics",()=>{let draft=conflictDraft();const beforeMetric={metricKey:"atInitialRate",value:"1/100",evidenceIds:[],verificationStatus:"single" as const,sourceCount:1,sourceNames:["TEST"]};draft={...draft,metrics:[...draft.metrics,beforeMetric]};const resolved=resolveDraftMetric(draft,"endScreenIndications","source_selected",[draft.evidence[0].id]);assert.deepEqual(resolved.metrics.find(item=>item.metricKey==="atInitialRate"),beforeMetric)});

function realBenchmark(evidenceIds:string[]):SettingBenchmark{return{id:"real-test",labelZh:"REAL TEST FIXTURE",labelJa:"TEST",metricKey:"czInitialRate",kind:"rate",observation:{type:"rate",numeratorKey:"cz",denominatorMetricKey:"observedTotalGame",valueMode:"oneIn"},settingValues:{1:100,2:100,3:100,4:100,5:100,6:100},minimumSample:100,source:"TEST SOURCE",updatedAt:"2026-08-27",verified:true,testData:false,evidenceIds}}
