import assert from "node:assert/strict";
import { mkdtemp,readFile,rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { machines } from "../src/data/machines.ts";
import { buildPublishPreview,createPublishedVersion } from "../src/lib/profile-promotion/core.ts";
import { JsonPublishedProfileRepository } from "../src/lib/profile-promotion/repository.server.ts";
import type { ProfileDraft,ProfileSourceEvidence } from "../src/types/profileBuilder.ts";

const base=()=>structuredClone(machines.find(item=>item.id==="tokyo-ghoul")!);
const rows=[["1","1/394.4"],["2","1/380.5"],["3","1/357.0"],["4","1/325.9"],["5","1/291.2"],["6","1/261.3"]];
function evidence(id:string,sourceName:string,sourceUrl:string,metricKey="atInitialRate",tableRows=rows):ProfileSourceEvidence{return{id,sourceName,sourceUrl,retrievedAt:"2026-08-27",metricKey,sectionKey:metricKey,extractedValue:tableRows.map(row=>row.join(" | ")),rawLabel:metricKey,sectionTitle:metricKey,tableHeaders:["設定","確率"],rows:tableRows,note:null,extractedFrom:"table",confidence:.9,reviewStatus:"approved"}}
function draft(status:ProfileDraft["status"]="verified"):ProfileDraft{const a=evidence("a","一撃","https://1geki.jp/a"),b=evidence("b","なな徹","https://nana-press.com/b"),screen=evidence("screen","なな徹","https://nana-press.com/b","endScreenIndications",[["金木","設定4以上"],["集合","設定6"]]);return{id:"draft-tokyo",catalogId:"tokyo-ghoul",machineId:"tokyo-ghoul",status,basedOnStatus:"placeholder",createdAt:"2026-08-27",updatedAt:"2026-08-27",sources:[],evidence:[a,b,screen],metrics:[{metricKey:"atInitialRate",value:a.extractedValue,evidenceIds:["a","b"],verificationStatus:"agree",sourceCount:2,sourceNames:["一撃","なな徹"]},{metricKey:"endScreenIndications",value:screen.extractedValue,evidenceIds:["screen"],verificationStatus:"single",sourceCount:1,sourceNames:["なな徹"]}],benchmarkDrafts:[],smartCounterSuggestions:[{id:"screen-counter",metricKey:"endScreenIndications",definition:{key:"endScreenIndications",labelZh:"終了畫面示唆",labelJa:"AT終了画面",type:"choice"},reason:"reviewed",approved:true}]}}

test("only verified Draft can publish",()=>{const preview=buildPublishPreview(base(),draft("reviewed"));assert.equal(preview.canPublish,false);assert.ok(preview.blockers.some(item=>item.code==="draft_not_verified"))});
test("publish preview diff",()=>{const preview=buildPublishPreview(base(),draft());assert.equal(preview.nextVersion,1);assert.ok(preview.disabledTestBenchmarkIds.length>0);assert.deepEqual(preview.addedCounterKeys,["endScreenIndications"]);assert.ok(preview.removedCounterKeys.includes("testSettingEvidence"))});
test("unresolved conflict blocks publish",()=>{const value=draft();value.metrics[0]={...value.metrics[0],verificationStatus:"conflict",resolutionStatus:"unresolved"};const preview=buildPublishPreview(base(),value);assert.equal(preview.canPublish,false);assert.ok(preview.blockers.some(item=>item.code==="unresolved_metric"))});
test("benchmark dependency validation",()=>{const machine=base();machine.profile.measurementMetrics=[];const preview=buildPublishPreview(machine,draft());assert.equal(preview.canPublish,false);assert.ok(preview.blockers.some(item=>item.code==="missing_denominator"))});
test("TEST DATA not active after publish",()=>{const preview=buildPublishPreview(base(),draft());assert.ok(preview.resultingMachine.profile.benchmarks.every(item=>!item.testData));assert.ok(preview.resultingMachine.profile.smartCounters.every(item=>item.key!=="testSettingEvidence"))});
test("approved Smart Counter promoted",()=>{const preview=buildPublishPreview(base(),draft());const counter=preview.resultingMachine.profile.smartCounters[0];assert.equal(counter.key,"endScreenIndications");assert.equal(counter.type,"choice");assert.equal(counter.choices?.length,2)});
test("placeholder replaced by verified Profile",()=>{const preview=buildPublishPreview(base(),draft());assert.equal(preview.resultingMachine.profileStatus,"verified");assert.equal(preview.resultingMachine.profileVersion,1)});
test("existing Session preserved",()=>{const existing={id:"old",machineId:"tokyo-ghoul",profileSnapshot:base()},before=structuredClone(existing);buildPublishPreview(base(),draft());assert.deepEqual(existing,before)});
test("new Session uses new Profile snapshot",()=>{const published=buildPublishPreview(base(),draft()).resultingMachine,snapshot=structuredClone(published);assert.equal(snapshot.profileStatus,"verified");assert.deepEqual(snapshot.profile.smartCounters.map(item=>item.key),["endScreenIndications"])});
test("rollback works",async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),"slot-profile-")),file=path.join(dir,"profiles.json"),repo=new JsonPublishedProfileRepository(file);try{const original=base(),first=buildPublishPreview(original,draft(),0,"2026-08-27T01:00:00Z"),v1=createPublishedVersion(first,"2026-08-27T01:00:00Z");await repo.publish("tokyo-ghoul",v1,original);const rolled=await repo.rollback("tokyo-ghoul");assert.equal(rolled.activeVersion,0);assert.equal(rolled.versions.length,2);assert.equal((await repo.active("tokyo-ghoul"))?.machine.profileStatus,"placeholder")}finally{await rm(dir,{recursive:true,force:true})}});
test("failed publish does not partially modify Profile",async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),"slot-profile-")),file=path.join(dir,"profiles.json"),repo=new JsonPublishedProfileRepository(file);try{const preview=buildPublishPreview(base(),draft("reviewed"));assert.throws(()=>createPublishedVersion(preview));assert.deepEqual(await repo.list(),[]);await assert.rejects(readFile(file,"utf8"))}finally{await rm(dir,{recursive:true,force:true})}});
