import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import { parsePWorldMachineGuide } from "../src/lib/machine-guide/pworld.ts";import { machineFromGuide } from "../src/lib/machine-guide/session.ts";import { buildSessionUiModel } from "../src/lib/sessionUi.ts";import { buildFirstTimeTutorial,changeSessionMode,controlsForSessionMode,createSessionSnapshot,loadLastSessionMode,normalizeSessionMode,saveLastSessionMode,SESSION_MODE_OPTIONS,SESSION_MODE_PREFERENCE_KEY } from "../src/lib/sessionModes.ts";import { loadSessions } from "../src/lib/storage.ts";import type { MachineCatalogRecord } from "../src/types/catalog.ts";import type { SessionMode } from "../src/types/index.ts";
const base:MachineCatalogRecord={id:"machine-mode-test",officialNameJa:"TEST DATA",displayNameZh:"",manufacturer:"TEST",brand:"",seriesName:"",aliases:[],machineType:"スマスロ",introducedAt:"2026-01-01",sourceName:"P-WORLD",sourceUrl:"https://www.p-world.co.jp/machine/database/10530",retrievedAt:"2026-08-27",verified:false,catalogStatus:"imported",sources:[]};
const html=fs.readFileSync(new URL("./fixtures/pworld-10530-bonus-art.html",import.meta.url),"utf8"),guide=parsePWorldMachineGuide(html,base,"2026-08-29T00:00:00Z"),machine=machineFromGuide(guide),ui=buildSessionUiModel(machine);
function storage(){const values=new Map<string,string>();const original=Object.getOwnPropertyDescriptor(globalThis,"window");Object.defineProperty(globalThis,"window",{value:{localStorage:{getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>values.set(key,value)}},configurable:true});return{values,restore(){if(original)Object.defineProperty(globalThis,"window",original);else delete (globalThis as {window?:unknown}).window}}}
const ids={sessionId:"session-test",eventId:"event-test",now:"2026-08-29T00:00:00Z"};
test("start entry exposes exactly three non-permanent usage modes",()=>{assert.deepEqual(SESSION_MODE_OPTIONS.map(option=>option.value),["first_time","quick","full"])});
test("all three modes create the same compatible Session shape",()=>{const sessions=(SESSION_MODE_OPTIONS.map(option=>createSessionSnapshot(machine,option.value,"128",undefined,{...ids,sessionId:`session-${option.value}`}))),shapes=sessions.map(session=>Object.keys(session).filter(key=>key!=="mode"&&key!=="id").sort());for(const session of sessions){assert.equal(session.machineId,machine.id);assert.equal(session.machineNumber,"128");session.counters[ui.recordControls[0].id]=1;assert.equal(session.counters[ui.recordControls[0].id],1);assert.deepEqual(session.metrics,{observedTotalGame:0,observedNormalGame:0});assert.ok(session.profileSnapshot?.profile.sessionCapabilities)}for(const shape of shapes)assert.deepEqual(shape,shapes[0])});
test("each machine remembers its own last mode",()=>{const mock=storage();assert.equal(loadLastSessionMode(machine.id),undefined);assert.equal(saveLastSessionMode(machine.id,"full"),true);assert.equal(saveLastSessionMode("another-machine","first_time"),true);assert.equal(loadLastSessionMode(machine.id),"full");assert.equal(loadLastSessionMode("another-machine"),"first_time");assert.ok(mock.values.has(SESSION_MODE_PREFERENCE_KEY));mock.restore()});
test("first-time tutorial uses guide and operational controls",()=>{const tutorial=buildFirstTimeTutorial(machine,ui);assert.ok(tutorial.cz.some(item=>item.label.includes("超自然災害")));assert.ok(tutorial.output.some(item=>/BIG|REG|喰霊|解放/.test(item.label)));assert.ok(tutorial.attention.length<=3);assert.equal(tutorial.records.length,ui.recordControls.length);assert.ok(tutorial.records.every(item=>/記錄 1 次|選擇對應項目|機台顯示/.test(item.detail)))});
test("quick and first-time modes show at most four primary controls with overflow",()=>{for(const mode of ["quick","first_time"] as SessionMode[]){const controls=controlsForSessionMode(ui,mode);assert.ok(controls.primary.length<=4);assert.equal(controls.primary.length+controls.overflow.length,ui.recordControls.length)}});
test("full mode shows every operational record control without overflow",()=>{const controls=controlsForSessionMode(ui,"full");assert.deepEqual(controls.primary.map(item=>item.id),ui.recordControls.map(item=>item.id));assert.deepEqual(controls.overflow,[]);assert.ok(controls.primary.every(item=>item.capability.status==="operational"));assert.ok(controls.primary.every(item=>item.counter?.type!=="choice"||Boolean(item.counter.choices?.length)))});
test("named CZ ART BIG REG and choice remain independent in every mode",()=>{const labels=ui.recordControls.map(item=>item.counter?.labelJa??item.capability.labelJa);for(const expected of ["超自然災害モード","解放の刻","喰霊CHANCE","BIG BONUS","REG BONUS"])assert.ok(labels.includes(expected));assert.equal(new Set(ui.recordControls.map(item=>item.id)).size,ui.recordControls.length)});
test("switching display mode preserves all Session observations",()=>{const original=createSessionSnapshot(machine,"quick","1",undefined,ids);original.trackers.dataGame=320;original.investmentYen=5000;original.medals=210;original.counters[ui.recordControls[0].id]=3;original.events.unshift({id:"count",sessionId:original.id,createdAt:ids.now,type:"counter",label:"TEST DATA"});const changed=changeSessionMode(original,"full");assert.equal(changed.mode,"full");assert.deepEqual({...changed,mode:original.mode},original)});
test("old v0.2.7.0 Session safely falls back to quick mode",()=>{const mock=storage(),old={...createSessionSnapshot(machine,"quick","1",undefined,ids)} as Record<string,unknown>;delete old.mode;mock.values.set("slot-companion-sessions-v1",JSON.stringify([old]));const loaded=loadSessions()[0];assert.equal(loaded.mode,"quick");assert.equal(normalizeSessionMode(undefined),"quick");mock.restore()});
test("mode and records survive JSON reload while guide remains available",()=>{const session=createSessionSnapshot(machine,"full","1",undefined,ids);session.counters[ui.recordControls[0].id]=2;const restored=JSON.parse(JSON.stringify(session));assert.equal(restored.mode,"full");assert.equal(restored.counters[ui.recordControls[0].id],2);assert.ok(restored.profileSnapshot.sessionGuide);for(const mode of SESSION_MODE_OPTIONS)assert.ok(machine.sessionGuide&&controlsForSessionMode(ui,mode.value))});
