import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { guideContextFromMachineGuide,japanSelectionMode,sanitizeSlotSelectionCandidates,sanitizeSlotSelectionGuides,sanitizeSlotSelectionMode,slotSelectionPrompt } from "../src/lib/ai/slotSelection.ts";
import { SELECTION_IMAGE_COMPRESSION } from "../src/lib/ai/imageLimits.ts";
import type { MachineGuide } from "../src/types/machineGuide.ts";

test("Japan time selects morning before 15:00 and evening afterwards",()=>{assert.equal(japanSelectionMode(new Date("2026-09-21T01:00:00Z")),"morning");assert.equal(japanSelectionMode(new Date("2026-09-21T08:00:00Z")),"evening");assert.equal(sanitizeSlotSelectionMode("pachinko"),"morning")});
test("morning accepts one candidate while evening accepts at most five unique candidates",()=>{const input=Array.from({length:8},(_,index)=>({catalogId:`machine-${index%6}`,currentGame:index*100,note:"x".repeat(900)}));assert.equal(sanitizeSlotSelectionCandidates(input,"morning").length,1);const evening=sanitizeSlotSelectionCandidates(input,"evening");assert.equal(evening.length,5);assert.equal(evening[0].note.length,600)});
test("selection prompt refuses invented reset and ceiling data",()=>{assert.match(slotSelectionPrompt("morning"),/沒有來源時絕對不能說有 Reset 優惠/);assert.match(slotSelectionPrompt("evening"),/不可硬選/);assert.match(slotSelectionPrompt("evening"),/不保證獲利/)});
test("guide context only exposes bounded selection-relevant sections",()=>{const guide={catalogId:"machine-1",status:"usable",sourceName:"P-WORLD",sourceUrl:"https://example.com",retrievedAt:"now",sections:[{key:"ceiling",titleZh:"天井",titleJa:"天井",summaryZh:"來源摘要",paragraphsJa:Array.from({length:20},()=>"a".repeat(300)),tables:[]},{key:"setting_rates",titleZh:"設定",titleJa:"設定",summaryZh:"不可送出",paragraphsJa:[],tables:[]}]} as unknown as MachineGuide,context=guideContextFromMachineGuide(guide);assert.equal(context.facts.length,1);assert.equal(context.facts[0].sectionKey,"ceiling");assert.equal(context.facts[0].details.length,5);assert.equal(context.facts[0].details[0].length,180);const sanitized=sanitizeSlotSelectionGuides([context],new Set(["machine-1"]));assert.equal(sanitized.length,1);assert.equal(sanitizeSlotSelectionGuides([context],new Set(["other"])).length,0)});
test("candidate photo policy keeps five images below the request ceiling",()=>{assert.equal(SELECTION_IMAGE_COMPRESSION.maxImages,5);assert.ok(SELECTION_IMAGE_COMPRESSION.hardMaxBytes*SELECTION_IMAGE_COMPRESSION.maxImages<4.2*1024*1024)});
test("SLOT catalog exposes a dedicated morning and evening assistant",()=>{const catalog=fs.readFileSync(new URL("../src/app/catalog/CatalogLibraryClient.tsx",import.meta.url),"utf8"),assistant=fs.readFileSync(new URL("../src/components/SlotSelectionAssistant.tsx",import.meta.url),"utf8"),route=fs.readFileSync(new URL("../src/app/api/ai/slot-selection/route.ts",import.meta.url),"utf8"),server=fs.readFileSync(new URL("../src/lib/ai/slotSelection.server.ts",import.meta.url),"utf8");assert.match(catalog,/\/catalog\/assistant/);assert.match(assistant,/朝一模式/);assert.match(assistant,/晚間撿台/);assert.match(assistant,/最多比較 5 台/);assert.match(route,/catalogRepository\.list/);assert.match(route,/multipart\/form-data/);assert.match(route,/maxRequestBytes/);assert.match(server,/store:false/);assert.match(server,/input_image/)});
