import type { MachineIdentificationResult } from "@/types";
import type { CatalogVisibleEvidence } from "@/types/catalog";
import type { MachineCatalogEntry } from "../matching.ts";
import { AIProviderError,type AIProvider,type IdentificationImage } from "../types.ts";

const identityBasis=["catalog_match","official_title_visible","multi_visual_evidence","visual_text","inferred","unknown"];
const resultSchema={type:"object",additionalProperties:false,required:["status","candidates"],properties:{status:{type:"string",enum:["identified","uncertain","unknown"]},candidates:{type:"array",maxItems:3,items:{type:"object",additionalProperties:false,required:["machineNameJa","machineNameZh","manufacturer","confidence","reason","visibleEvidence","matchedCatalogId","identityBasis"],properties:{machineNameJa:{type:"string"},machineNameZh:{type:"string"},manufacturer:{type:"string"},confidence:{type:"number",minimum:0,maximum:1},reason:{type:"string"},visibleEvidence:{type:"array",items:{type:"string"},maxItems:6},matchedCatalogId:{type:["string","null"]},identityBasis:{type:"string",enum:identityBasis}}}}}};
const evidenceSchema={type:"object",additionalProperties:false,required:["status","visibleText","manufacturerText","visualEvidence","searchTerms","visibleOfficialTitleCandidates","visibleFranchiseTerms","visibleModeOrStageTerms","visibleManufacturerMarks"],properties:{status:{type:"string",enum:["slot","uncertain","unknown"]},visibleText:{type:"array",items:{type:"string"},maxItems:12},manufacturerText:{type:"array",items:{type:"string"},maxItems:5},visualEvidence:{type:"array",items:{type:"string"},maxItems:8},searchTerms:{type:"array",items:{type:"string"},maxItems:10},visibleOfficialTitleCandidates:{type:"array",maxItems:5,items:{type:"object",additionalProperties:false,required:["text","confidence"],properties:{text:{type:"string"},confidence:{type:"number",minimum:0,maximum:1}}}},visibleFranchiseTerms:{type:"array",items:{type:"string"},maxItems:8},visibleModeOrStageTerms:{type:"array",items:{type:"string"},maxItems:8},visibleManufacturerMarks:{type:"array",items:{type:"string"},maxItems:5}}};
export function buildMachineIdentityPrompt(catalog:MachineCatalogEntry[]){return `依圖片與下列已縮小的 Catalog 候選驗證正式 Pachislot Machine Identity。證據優先順序：1 正式 title、2 版本／續作一致、3 Catalog title／alias、4 manufacturer、5 筐體視覺、6 franchise／IP、7 generic stage／mode。低順位證據不可覆蓋高順位衝突。Catalog 不是預設答案；若證據不足必須 uncertain。visibleOfficialTitleCandidates 有高信心項目時，候選必須與 officialNameJa 或 alias 高度一致。阿拉伯數字、Roman numeral、RE:2／RE:3、V／V-30、-30 與正式副標題都是重要 identity token；任何衝突禁止 identified。禁止把 IP、角色、stage、bonus、generic GOD/Bullet/Dream 或演出字幕當正式名稱。catalog_match 必須填有效 matchedCatalogId 並逐字使用 catalog 名稱與 manufacturer。official_title_visible 只適用清楚 title plate；multi_visual_evidence 至少兩項唯一證據。visual_text/inferred 不得 identified。manufacturer 無 catalog 或清楚 logo 證據時填「不明」。每張圖片獨立判斷。SHORTLIST CATALOG:\n${JSON.stringify(catalog)}`}
const extractPrompt="只抽取這張圖片可見的 Pachislot 身份線索，不要判定正式機種、不要使用先驗 catalog、不要補全名稱。將正式機種 title 候選放在 visibleOfficialTitleCandidates（附 0–1 confidence）；IP／系列詞放 visibleFranchiseTerms；演出、mode、stage 字樣放 visibleModeOrStageTerms；メーカー標誌放 visibleManufacturerMarks。版本數字、Roman numeral、RE:2／RE:3、V-30、-30 與副標題必須原樣保留。另回傳一般 visibleText、visualEvidence 與 searchTerms。非 Slot 圖片回 unknown。";
export class OpenAIProvider implements AIProvider{readonly name="openai" as const;private apiKey:string|undefined;private model:string;private request:typeof fetch;private catalog:MachineCatalogEntry[];constructor(apiKey:string|undefined,model:string,request:typeof fetch=fetch,catalog:MachineCatalogEntry[]=[]){this.apiKey=apiKey;this.model=model;this.request=request;this.catalog=catalog}
  private async call<T>(image:IdentificationImage,prompt:string,schema:object,name:string):Promise<T>{if(!this.apiKey)throw new AIProviderError("missing_api_key","尚未設定 OPENAI_API_KEY，無法進行真實 AI 辨識。",503);let response:Response;try{response=await this.request("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${this.apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:this.model,store:false,input:[{role:"user",content:[{type:"input_text",text:prompt},{type:"input_image",image_url:image.dataUrl,detail:"high"}]}],text:{format:{type:"json_schema",name,strict:true,schema}}})})}catch{throw new AIProviderError("request_failed","AI 辨識服務暫時無法連線，請稍後再試。",502)}if(!response.ok)throw new AIProviderError("request_failed",`AI 辨識失敗（${response.status}），請稍後再試。`,502);const payload=await response.json() as {output?:Array<{content?:Array<{type?:string;text?:string}>}>};const text=payload.output?.flatMap(item=>item.content??[]).find(item=>item.type==="output_text")?.text;if(!text)throw new AIProviderError("invalid_response","AI 未回傳可用的結構化結果。",502);try{return JSON.parse(text) as T}catch{throw new AIProviderError("invalid_response","AI 回傳格式無法解析。",502)}}
  extractVisibleEvidence(image:IdentificationImage){return this.call<CatalogVisibleEvidence>(image,extractPrompt,evidenceSchema,"machine_visible_evidence")}
  async verifyMachine(image:IdentificationImage,evidence:CatalogVisibleEvidence,catalog:MachineCatalogEntry[]){const result=await this.call<Omit<MachineIdentificationResult,"provider">>(image,`${buildMachineIdentityPrompt(catalog)}\nEXTRACTED EVIDENCE:\n${JSON.stringify(evidence)}`,resultSchema,"machine_identity_verification");return{...result,candidates:result.candidates.slice(0,3),provider:"openai" as const}}
  async identifyMachine(image:IdentificationImage){const evidence=await this.extractVisibleEvidence(image);return this.verifyMachine(image,evidence,this.catalog)}
}
