import type { Machine } from "@/types";
import type { ProfileDraft } from "@/types/profileBuilder";

export const metricLabels:Record<string,string>={atInitialRate:"AT 初當率",czInitialRate:"CZ 初當率",weakCherryCzSuccessRate:"弱櫻桃 CZ 當選率",within100GameHitRate:"100G 內 CZ 當選率",atDirectHitRate:"AT 直擊率",atReturnRate:"AT 引回率",lowerReplayRate:"下段 Replay 出現率",endScreenIndications:"AT 終了畫面示唆",czEndScreenIndications:"CZ 終了畫面示唆"};
export const verifiedOverviewSections=["遊戲流程","3 個觀察重點","重要節點","爽點","易誤會處"] as const;
export type MachineCardMetric={metricKey:string;label:string;statusLabel:string;headers:string[];rows:string[][];note?:string|null};
function tableFromValue(value:string|string[]){if(!Array.isArray(value))return{headers:["資料"],rows:[[value]]};const split=value.map(line=>line.split("|").map(cell=>cell.trim()));return{headers:split[0]??["資料"],rows:split.slice(1)}}
function evidenceForMetric(metricKey:string,draft:ProfileDraft|undefined,selectedIds:string[]|undefined){const metric=draft?.metrics.find(item=>item.metricKey===metricKey),ids=selectedIds?.length?selectedIds:metric?.selectedEvidenceIds?.length?metric.selectedEvidenceIds:metric?.evidenceIds??[];return draft?.evidence.filter(item=>ids.includes(item.id)&&item.reviewStatus==="approved")??[]}
function sourceLabel(metricKey:string,draft:ProfileDraft|undefined,fallbackNames:string[]){const metric=draft?.metrics.find(item=>item.metricKey===metricKey);if(metric?.resolutionStatus&&metric.resolutionStatus!=="unresolved"){const evidence=evidenceForMetric(metricKey,draft,metric.selectedEvidenceIds),names=[...new Set(evidence.map(item=>item.sourceName))];if(metric.resolutionStatus==="source_selected")return`已人工核准 · 採用${names.join(" + ")}`;if(metric.resolutionStatus==="merged")return`已人工核准 · 合併${names.join(" + ")}`;return"已人工核准 · 排除衝突來源"}if(metric?.verificationStatus==="single"||fallbackNames.length===1)return`單一來源 · ${fallbackNames[0]??"來源未標示"}`;if(metric?.verificationStatus==="agree")return`${metric.sourceCount??fallbackNames.length} 個來源一致 · ${(metric.sourceNames??fallbackNames).join(" + ")}`;return`已人工核准 · ${(metric?.sourceNames??fallbackNames).join(" + ")}`}
function structuredTable(metricKey:string,value:string|string[],draft:ProfileDraft|undefined){const metric=draft?.metrics.find(item=>item.metricKey===metricKey),evidence=evidenceForMetric(metricKey,draft,metric?.selectedEvidenceIds),primary=evidence[0];if(metric?.resolutionStatus==="merged"&&metric.mergedRows?.length)return{headers:metric.mergedTableHeaders??[],rows:metric.mergedRows,note:metric.resolutionNote};if(primary?.rows?.length)return{headers:primary.tableHeaders??[],rows:primary.rows,note:primary.note};return{...tableFromValue(value),note:null}}
export function buildMachineCardMetrics(machine:Machine,draft?:ProfileDraft):MachineCardMetric[]{return(machine.profile.verifiedMetrics??[]).map(metric=>{const table=structuredTable(metric.metricKey,metric.value,draft);return{metricKey:metric.metricKey,label:metricLabels[metric.metricKey]??"已驗證資料",statusLabel:sourceLabel(metric.metricKey,draft,metric.sourceNames),headers:table.headers,rows:table.rows,note:table.note}})}
export function isPublishedDraftMatch(machine:Machine,draft:ProfileDraft|null):draft is ProfileDraft{return Boolean(draft&&machine.sourceDraftId===draft.id)}
