import type { Machine,MachineProfileStatus,SettingBenchmark } from "@/types";
import type { DraftMetric,ExtractedProfileData,MetricResolutionType,ProfileDraft,ProfileMetricKey,ProfileSourceEvidence,SmartCounterSuggestion } from "@/types/profileBuilder";
import type { ProfileSourceExtraction,StructuredExtractedSection } from "./providers/types";
import { buildDraftMetrics,compareMetricEvidence } from "./comparison.ts";

const labelZh:Record<ProfileMetricKey,string>={gameFlow:"遊戲流程",czInitialRate:"CZ 初當率",atInitialRate:"AT 初當率",smallRoleSettingDifferences:"小役設定差",triggerSuccessRate:"契機成功率",ceiling:"天井",zone:"Zone",reset:"Reset",endScreenIndications:"結束畫面示唆",trophySettingIndications:"獎盃／設定示唆",playGuide:"打ち方"};
export function createProfileDraft(catalogId:string,machine?:Machine,now=new Date().toISOString()):ProfileDraft{return{id:`profile-draft-${catalogId}`,catalogId,machineId:machine?.id,status:"draft",basedOnStatus:machine?.profileStatus??"catalog-only",createdAt:now,updatedAt:now,sources:[],evidence:[],metrics:[],benchmarkDrafts:[],smartCounterSuggestions:[]}}
export function addSourceToDraft(draft:ProfileDraft,sourceUrl:string,sourceName="待抽取",now=new Date().toISOString()){if(draft.sources.some(item=>item.sourceUrl===sourceUrl))return draft;return{...draft,updatedAt:now,sources:[...draft.sources,{id:`source-${draft.sources.length+1}`,sourceName,sourceUrl,retrievedAt:now,status:"pending" as const}]}}
function buildSuggestions(metrics:DraftMetric[]):SmartCounterSuggestion[]{return metrics.flatMap((metric):SmartCounterSuggestion[]=>{if(metric.metricKey==="smallRoleSettingDifferences")return[{id:"suggest-small-role",metricKey:metric.metricKey,definition:{key:"verifiedSmallRole",labelZh:"設定差小役",labelJa:"設定差小役",type:"count"},reason:"來源資料顯示此小役具有設定差；需人工確認計數定義。",approved:false}];if(metric.metricKey==="triggerSuccessRate")return[{id:"suggest-trigger-trial",metricKey:metric.metricKey,definition:{key:"verifiedTrigger",labelZh:"契機成功",labelJa:"契機成功",type:"event"},reason:"來源資料包含契機成功率；建議建立 trial/outcome 關係。",approved:false}];if(metric.metricKey==="endScreenIndications"||metric.metricKey==="trophySettingIndications")return[{id:`suggest-${metric.metricKey}`,metricKey:metric.metricKey,definition:{key:metric.metricKey,labelZh:labelZh[metric.metricKey],labelJa:labelZh[metric.metricKey],type:"choice"},reason:"來源資料包含設定示唆；需人工確認選項或照片規則。",approved:false}];return[]})}
function legacySections(extraction:ProfileSourceExtraction):StructuredExtractedSection[]{if(extraction.sections)return extraction.sections;return(Object.entries(extraction.data??{}) as Array<[ProfileMetricKey,string|string[]|null]>).flatMap(([metricKey,value])=>value===null?[]:[{sectionTitle:extraction.labels?.[metricKey]??labelZh[metricKey],metricKey,sectionKey:metricKey,tableHeaders:[],rows:[],note:null,extractedFrom:"paragraph" as const,extractedValue:value,rawLabel:extraction.labels?.[metricKey]??labelZh[metricKey]}])}
export function applyExtraction(draft:ProfileDraft,extraction:ProfileSourceExtraction):ProfileDraft{const source=draft.sources.find(item=>item.sourceUrl===extraction.sourceUrl),sourceId=source?.id??`source-${draft.sources.length+1}`,sections=legacySections(extraction);const newEvidence=sections.map((section,index):ProfileSourceEvidence=>({id:`${sourceId}-${section.sectionKey}-${index}`,sourceName:extraction.sourceName,sourceUrl:extraction.sourceUrl,retrievedAt:extraction.retrievedAt,metricKey:section.metricKey,sectionKey:section.sectionKey,extractedValue:section.extractedValue,rawLabel:section.rawLabel,sectionTitle:section.sectionTitle,tableHeaders:section.tableHeaders,rows:section.rows,note:section.note,extractedFrom:section.extractedFrom,confidence:extraction.confidence,reviewStatus:"pending"}));const evidence=[...draft.evidence.filter(item=>item.sourceUrl!==extraction.sourceUrl),...newEvidence],metrics=buildDraftMetrics(evidence,draft.metrics),status=extraction.status??(newEvidence.length?"extracted":"no_evidence");const sources=draft.sources.some(item=>item.sourceUrl===extraction.sourceUrl)?draft.sources.map(item=>item.sourceUrl===extraction.sourceUrl?{...item,sourceName:extraction.sourceName,retrievedAt:extraction.retrievedAt,status,extractedEvidenceCount:newEvidence.length,error:undefined}:item):[...draft.sources,{id:sourceId,sourceName:extraction.sourceName,sourceUrl:extraction.sourceUrl,retrievedAt:extraction.retrievedAt,status,extractedEvidenceCount:newEvidence.length}];return{...draft,updatedAt:extraction.retrievedAt,sources,evidence,metrics,smartCounterSuggestions:buildSuggestions(metrics)}}
export function reviewDraftEvidence(draft:ProfileDraft,approvedIds:string[],rejectedIds:string[],now=new Date().toISOString()):ProfileDraft{return{...draft,status:"reviewed",updatedAt:now,evidence:draft.evidence.map(item=>({...item,reviewStatus:approvedIds.includes(item.id)?"approved":rejectedIds.includes(item.id)?"rejected":item.reviewStatus}))}}
export function reviewSmartCounterSuggestion(draft:ProfileDraft,suggestionId:string,approved:boolean,now=new Date().toISOString()):ProfileDraft{return{...draft,updatedAt:now,smartCounterSuggestions:draft.smartCounterSuggestions.map(item=>item.id===suggestionId?{...item,approved}:item)}}
const blockingStatuses=new Set(["conflict","duplicate_source","incomparable"]);
export function isMetricResolutionRequired(metric:DraftMetric){return blockingStatuses.has(metric.verificationStatus)&&(!metric.resolutionStatus||metric.resolutionStatus==="unresolved")}
export function unresolvedMetricCount(draft:ProfileDraft){return draft.metrics.filter(isMetricResolutionRequired).length}
function normalizedMergeCell(value:string){return value.normalize("NFKC").replace(/\s+/g,"").replace(/[／⁄]/g,"/").toLowerCase()}
function mergeEvidenceTables(items:ProfileSourceEvidence[]){if(items.length<2||items.some(item=>!item.rows?.length))throw new Error("此 Evidence 結構無法安全合併，請改為選擇單一來源");const widest=[...items].sort((a,b)=>(b.tableHeaders?.length??0)-(a.tableHeaders?.length??0))[0],headers=widest.tableHeaders??[],width=headers.length;if(width<2||items.some(item=>item.rows!.some(row=>row.length<2||row.length>width)))throw new Error("來源表格欄位無法安全對齊");const settingRows=items.every(item=>item.rows!.every(row=>/^(?:設定)?[1-6]$/.test(row[0].trim())));if(!settingRows){const seen=new Set<string>(),rows=items.flatMap(item=>item.rows!).filter(row=>{const key=row.map(normalizedMergeCell).join("|");if(seen.has(key))return false;seen.add(key);return true});return{headers,rows,value:[headers.join(" | "),...rows.map(row=>row.join(" | "))]}}const bySetting=new Map<string,string[]>();for(const item of items)for(const row of item.rows!){const key=row[0].replace("設定","").trim(),existing=bySetting.get(key)??Array(width).fill("");for(let index=0;index<row.length;index++){if(existing[index]&&normalizedMergeCell(existing[index])!==normalizedMergeCell(row[index]))throw new Error(`設定 ${key} 的來源數值不一致，無法自動 Merge`);existing[index]=existing[index]||row[index]}bySetting.set(key,existing)}const rows=[...bySetting.entries()].sort(([a],[b])=>Number(a)-Number(b)).map(([,row])=>row);return{headers,rows,value:[headers.join(" | "),...rows.map(row=>row.join(" | "))]}}
export function resolveDraftMetric(draft:ProfileDraft,metricKey:string,resolutionType:MetricResolutionType,selectedEvidenceIds:string[]=[],rejectedEvidenceIds:string[]=[],note="",now=new Date().toISOString()):ProfileDraft{const metric=draft.metrics.find(item=>item.metricKey===metricKey);if(!metric)throw new Error("找不到 Draft metric");if(!blockingStatuses.has(metric.verificationStatus))throw new Error("此 metric 不需要衝突處理");const metricEvidence=draft.evidence.filter(item=>metric.evidenceIds.includes(item.id)),validIds=new Set(metricEvidence.map(item=>item.id));if([...selectedEvidenceIds,...rejectedEvidenceIds].some(id=>!validIds.has(id)))throw new Error("Resolution 包含不屬於此 metric 的 Evidence");if(resolutionType==="source_selected"&&selectedEvidenceIds.length!==1)throw new Error("採用來源時必須選擇一筆 Evidence");if(resolutionType==="merged"&&selectedEvidenceIds.length<2)throw new Error("Merge 至少需要兩筆 Evidence");if(resolutionType==="rejected"&&!rejectedEvidenceIds.length)throw new Error("請選擇要排除的 Evidence");const selected=metricEvidence.filter(item=>selectedEvidenceIds.includes(item.id));let merged:ReturnType<typeof mergeEvidenceTables>|undefined;if(resolutionType==="merged")merged=mergeEvidenceTables(selected);const effectiveSelected=resolutionType==="rejected"?metricEvidence.filter(item=>!rejectedEvidenceIds.includes(item.id)).map(item=>item.id):selectedEvidenceIds;if(!effectiveSelected.length)throw new Error("至少需保留一筆 Evidence");const nextEvidence=draft.evidence.map(item=>rejectedEvidenceIds.includes(item.id)||(resolutionType==="source_selected"&&metric.evidenceIds.includes(item.id)&&!selectedEvidenceIds.includes(item.id))?{...item,reviewStatus:"rejected" as const}:item);if(resolutionType==="rejected"){const remaining=compareMetricEvidence(metricKey,nextEvidence);if(!remaining||blockingStatuses.has(remaining.verificationStatus))throw new Error("排除後仍有未解決衝突，請選擇來源或繼續排除")};const resolution={resolutionStatus:resolutionType,resolvedAt:now,resolutionType,selectedEvidenceIds:effectiveSelected,rejectedEvidenceIds:resolutionType==="source_selected"?metric.evidenceIds.filter(id=>!selectedEvidenceIds.includes(id)):rejectedEvidenceIds,mergedFromEvidenceIds:resolutionType==="merged"?selectedEvidenceIds:undefined,resolutionNote:note.trim()||undefined,mergedValue:merged?.value,mergedTableHeaders:merged?.headers,mergedRows:merged?.rows};const metrics=draft.metrics.map(item=>item.metricKey===metricKey?{...item,value:resolutionType==="source_selected"?selected[0].extractedValue:merged?.value??item.value,...resolution}:item);return{...draft,updatedAt:now,evidence:nextEvidence,metrics}}
export function evidenceEligibleBenchmark(benchmark:SettingBenchmark,draft:ProfileDraft,profileStatus:MachineProfileStatus){if(profileStatus!=="verified"||benchmark.testData||!benchmark.verified||!benchmark.evidenceIds?.length)return false;return benchmark.evidenceIds.every(id=>{const evidence=draft.evidence.find(item=>item.id===id),metric=evidence&&draft.metrics.find(item=>item.metricKey===evidence.metricKey);if(!evidence||!metric||evidence.reviewStatus!=="approved"||isMetricResolutionRequired(metric)||metric.resolutionStatus==="rejected")return false;if(metric.resolutionStatus==="source_selected"||metric.resolutionStatus==="merged")return metric.selectedEvidenceIds?.includes(id)??false;return true})}
export function realEstimatorBenchmarks(benchmarks:SettingBenchmark[],draft:ProfileDraft,profileStatus:MachineProfileStatus){return benchmarks.filter(item=>evidenceEligibleBenchmark(item,draft,profileStatus))}
export function approveProfileDraft(draft:ProfileDraft,now=new Date().toISOString()):ProfileDraft{const unresolved=unresolvedMetricCount(draft);if(unresolved)throw new Error(`尚有 ${unresolved} 個未解決資料衝突`);if(draft.evidence.some(item=>item.reviewStatus==="pending"))throw new Error("仍有未審核 evidence，無法核准 Profile");return{...draft,status:"verified",updatedAt:now,rejectionReason:undefined}}
export function rejectProfileDraft(draft:ProfileDraft,reason:string,now=new Date().toISOString()):ProfileDraft{return{...draft,status:"draft",updatedAt:now,rejectionReason:reason||"人工退回修改"}}
export const missingMetrics=(data:ExtractedProfileData)=>(Object.entries(data) as Array<[ProfileMetricKey,string|string[]|null]>).filter(([,value])=>value===null).map(([key])=>key);
