"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { getMachine } from "@/data/machines";
import { loadSessions } from "@/lib/storage";
import type { MetricDefinition, Session } from "@/types";

function duration(s:Session){const ms=new Date(s.endedAt??Date.now()).getTime()-new Date(s.startedAt).getTime();const min=Math.max(0,Math.floor(ms/60000));return `${Math.floor(min/60)} 小時 ${min%60} 分`}
const stateLabels = { normal: "通常", prelude: "前兆", cz: "CZ", at: "AT", special: "特殊" } as const;
function metricValue(session:Session,definition:MetricDefinition|undefined,key:string){if(!definition)return session.metrics[key]??0;const source=definition.source;if(source.type==="trackerDelta"){const baseline=session.trackerBaselines[source.trackerKey];return baseline===undefined?0:Math.max(0,(session.trackers[source.trackerKey]??0)-baseline)}if(source.type==="custom")return session.metrics[source.sessionMetricKey]??0;return session.metrics[source.type]??0}
export default function SummaryPage(){const {id}=useParams<{id:string}>();const [s,setS]=useState<Session>();useEffect(()=>setS(loadSessions().find(x=>x.id===id)),[id]);if(!s)return <main className="page"><div className="empty">找不到結算資料<Link href="/" className="secondary-button mt-5">回首頁</Link></div></main>;const m=s.profileSnapshot??getMachine(s.machineId);return <main className="page summary-page">
  <div className="summary-check">✓</div><p className="eyebrow text-center">SESSION COMPLETE</p><h1>結算完成</h1><p className="summary-machine">{m?.nameZh} · 台號 {s.machineNumber}</p>
  <section className="summary-score card"><div><span>遊戲時間</span><strong>{duration(s)}</strong></div>{m?.profile.measurementMetrics.map(metric=><div key={metric.key}><span>{metric.labelZh}</span><strong>{metricValue(s,metric,metric.key).toLocaleString()} G</strong></div>)}<div><span>投入</span><strong>¥{s.investmentYen.toLocaleString()}</strong></div><div><span>最終持枚</span><strong>{s.medals.toLocaleString()}</strong></div><div><span>CZ</span><strong>{s.czCount}</strong></div><div><span>AT</span><strong>{s.atCount}</strong></div><div><span>結算狀態</span><strong>{stateLabels[s.gameState]}</strong></div></section>
  <section className="section card machine-section"><h2>Smart Counter 統計</h2>{m?.profile.smartCounters.map(c=>{const value=s.counters[c.key];const count=typeof value==="number"?value:0;const metric=c.denominatorMetricKey?m.profile.measurementMetrics.find(item=>item.key===c.denominatorMetricKey):undefined;const denominator=c.denominatorMetricKey?metricValue(s,metric,c.denominatorMetricKey):undefined;const records=c.trialRelationshipId?s.trials[c.trialRelationshipId]??[]:[];const resolved=records.filter(record=>record.outcome!=="pending");const successes=resolved.filter(record=>record.outcome==="success").length;const display=typeof value==="number"?String(value):typeof value==="string"?(c.choices?.find(choice=>choice.value===value)?.labelZh??value):typeof value==="object"?"已記錄":"—";const stat=c.type==="count"&&c.denominatorMetricKey?(count>0&&(denominator??0)>0?`1 / ${((denominator??0)/count).toFixed(1)}`:"尚無比率"):c.type==="event"&&c.trialRelationshipId?(resolved.length>0?`${successes} / ${resolved.length} · ${(successes/resolved.length*100).toFixed(1)}%`:"尚無比率"):"—";return <div className="summary-counter" key={c.key}><span>{c.icon} {c.labelZh}<small>{c.labelJa} · {c.type}</small></span><b>{display}<small>{stat}</small></b></div>})}</section>
  <section className="section"><div className="section-title"><h2>簡單 Timeline</h2><span>最近 12 筆</span></div><div className="timeline">{[...s.events].slice(0,12).reverse().map(e=><div key={e.id}><i/><span>{new Intl.DateTimeFormat("zh-TW",{hour:"2-digit",minute:"2-digit"}).format(new Date(e.createdAt))}</span><strong>{e.label}</strong></div>)}</div></section>
  <Link href="/records" className="primary-button mt-6">查看今日紀錄</Link><Link href="/" className="secondary-button mt-2">回首頁</Link>
  </main>}
