import Link from "next/link";
import {notFound} from "next/navigation";
import {PageHeader} from "@/components/PageHeader";
import {PachinkoCoverImage} from "@/components/PachinkoCoverImage";
import {StartPachinkoSession} from "@/components/StartPachinkoSession";
import {pachinkoCatalogRepository} from "@/lib/pachinko/repository.server";
import {loadPachinkoGuide} from "@/lib/pachinko/guide.server";
const typeLabels={smart_pachinko:"智慧柏青哥",digital:"數位柏青哥",hanemono:"羽根物",other:"其他"}as const;
export default async function PachinkoDetailPage({params}:{params:Promise<{id:string}>}){const{id}=await params,record=(await pachinkoCatalogRepository.list()).find(item=>item.id===id);if(!record)notFound();const guide=await loadPachinkoGuide(record);return<><PageHeader title="柏青哥機種詳細" eyebrow="Pachinko Catalog" backHref="/pachinko" backLabel="返回柏青哥資料庫"/><main className="page catalog-detail pachinko-detail"><section className="catalog-detail-hero card"><div className="pachinko-detail-cover"><PachinkoCoverImage record={record}/></div><span className="badge">{typeLabels[record.machineType]}</span><h1>{record.displayNameZh||record.officialNameJa}</h1>{record.displayNameZh&&<p>{record.officialNameJa}</p>}<div className="profile-ready">🔴 獨立 Pachinko Catalog</div></section><section className="card pachinko-guide"><div className="section-title"><h2>機台說明</h2><span>{guide.status==="usable"?"規格可用":"部分資料"}</span></div>{guide.facts.length?<div className="pachinko-fact-grid">{guide.facts.map(fact=><dl key={fact.labelZh}><dt>{fact.labelZh}<small>{fact.labelJa}</small></dt><dd>{fact.value}</dd></dl>)}</div>:<p>目前尚未取得結構化規格，可先查看 P-WORLD 來源。</p>}{guide.gameFlow.length>0&&<div className="pachinko-flow"><h3>遊戲流程</h3><ol>{guide.gameFlow.map(item=><li key={item}>{item}</li>)}</ol></div>}<div className="notice">{guide.playNotes.map(item=><p key={item}>{item}</p>)}</div><a className="secondary-button mt-3" href={record.sourceUrl} target="_blank" rel="noreferrer">查看 P-WORLD 原始資料 ↗</a></section><section className="card catalog-detail-list"><h2>機台身分</h2><dl><dt>メーカー</dt><dd>{record.manufacturer}</dd></dl><dl><dt>導入日</dt><dd>{record.introducedAt??"未設定"}</dd></dl><dl><dt>類型</dt><dd>{typeLabels[record.machineType]}</dd></dl><dl><dt>資料狀態</dt><dd>{record.catalogStatus}</dd></dl></section><Link className="primary-button mt-3" href={`/halls?machine=${encodeURIComponent(record.officialNameJa)}&kind=pachinko`}>附近哪裡有這台</Link><StartPachinkoSession record={record}/></main></>}
