import type { MachineCatalogCandidate } from "@/types/catalog";
import { CatalogSourceError,type CatalogSourceProvider } from "./types.ts";

const text=(html:string)=>html.replace(/<[^>]+>/g,"").replace(/&nbsp;|&#160;/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").trim();
const field=(html:string,className:string)=>{const match=html.match(new RegExp(`<[^>]+class=["'][^"']*${className}[^"']*["'][^>]*>([\\s\\S]*?)<\\/[^>]+>`));return match?text(match[1]):""};
export class PWorldCatalogProvider implements CatalogSourceProvider{
  readonly sourceName="P-WORLD";
  private request:typeof fetch;
  constructor(request:typeof fetch=fetch){this.request=request}
  supports(url:URL){return url.protocol==="https:"&&(url.hostname==="www.p-world.co.jp"||url.hostname==="p-world.co.jp")&&url.pathname==="/database/machine/introduce_calendar.cgi"}
  async fetchCandidates(sourceUrl:string){let url:URL;try{url=new URL(sourceUrl)}catch{throw new CatalogSourceError("invalid_url","URL 格式不正確。")}if(!this.supports(url))throw new CatalogSourceError("unsupported_url","目前只支援 P-WORLD 公開新台日曆 URL。");let response:Response;try{response=await this.request(url,{headers:{"User-Agent":"SlotCompanionCatalogImporter/0.2.2.1 (manual development import)"},signal:AbortSignal.timeout(15000)})}catch{throw new CatalogSourceError("request_failed","無法讀取 P-WORLD，請稍後再試。")}if(!response.ok)throw new CatalogSourceError("request_failed",`P-WORLD 回應 ${response.status}。`);return this.parse(await response.text(),url.toString(),new Date().toISOString())}
  parse(html:string,sourceUrl:string,retrievedAt:string){const results:MachineCatalogCandidate[]=[];const blocks=[...html.matchAll(/<div class="machineList js-machineList"[^>]*data-yyyymmdd="(\d{8})"[^>]*>([\s\S]*?)(?=<div class="machineList js-machineList"|<h2 class="pageTitle">導入機種一覧|$)/g)];for(const block of blocks){const date=block[1];const slot=block[2].match(/<ul class="machineList-grid machineList-grid--slot">([\s\S]*?)<\/ul>/)?.[1]??"";for(const item of slot.matchAll(/<li class="machineList-item">([\s\S]*?)<\/li>/g)){const body=item[1];const officialNameJa=field(body,"machineList-item-title");const manufacturer=field(body,"machineList-item-maker")||"不明";const href=body.match(/machineList-item-title[^>]*>[\s\S]*?<a href="([^"]+)"/)?.[1]??"";const imageSrc=body.match(/machineList-item-thumb[^>]*>[\s\S]*?<img[^>]+src=["']([^"']+)["']/)?.[1];if(!officialNameJa)continue;results.push({sourceId:href||`${date}-${results.length}`,officialNameJa,displayNameZh:"",manufacturer,brand:"",seriesName:"",aliases:[],machineType:officialNameJa.match(/^(L|スマスロ|スマート)/i)?"スマスロ":"パチスロ",introducedAt:`${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}`,sourceName:this.sourceName,sourceUrl:new URL(href||sourceUrl,sourceUrl).toString(),sourceImageUrl:imageSrc?new URL(imageSrc,sourceUrl).toString():undefined,retrievedAt})}}if(results.length===0)throw new CatalogSourceError("malformed_page","頁面中找不到可匯入的パチスロ機種。");return results}
}
