import type { StructuredExtractedSection } from "./types";

const entities:Record<string,string>={amp:"&",nbsp:" ",lt:"<",gt:">",quot:'"',apos:"'"};
function decode(value:string){return value.replace(/&#x([\da-f]+);|&#(\d+);|&([a-z]+);/gi,(_,hex,decimal,named)=>hex?String.fromCodePoint(parseInt(hex,16)):decimal?String.fromCodePoint(Number(decimal)):entities[String(named).toLowerCase()]??" ")}
function text(value:string){return decode(value.replace(/<br\s*\/?>/gi," ").replace(/<img\b[^>]*alt=["']([^"']*)["'][^>]*>/gi," $1 ").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim()}
function cleanHtml(html:string){let clean=html.replace(/<(script|style|template|noscript|header|nav|footer|aside)\b[\s\S]*?<\/\1\s*>/gi," ");for(const tag of ["div","section","ul"]){const noise=new RegExp(`<${tag}\\b[^>]*(?:class|id)=["'][^"']*(?:sidebar|related|ranking|recommend|breadcrumb|advert|sponsor|sns|share|toc)[^"']*["'][^>]*>[\\s\\S]*?<\\/${tag}\\s*>`,"gi");clean=clean.replace(noise," ")}return clean}
type Cell={value:string;rowspan:number;colspan:number;header:boolean};
function parseTable(html:string){const pending=new Map<number,{value:string;remaining:number}>(),rows:Array<{values:string[];header:boolean}>=[];for(const rowMatch of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr\s*>/gi)){const cells=[...rowMatch[1].matchAll(/<(th|td)\b([^>]*)>([\s\S]*?)<\/\1\s*>/gi)].map((match):Cell=>({value:text(match[3]),rowspan:Math.max(1,Number(match[2].match(/rowspan=["']?(\d+)/i)?.[1]??1)),colspan:Math.max(1,Number(match[2].match(/colspan=["']?(\d+)/i)?.[1]??1)),header:match[1].toLowerCase()==="th"||/class=["'][^"']*c-m/i.test(match[2])}));if(!cells.length)continue;const values:string[]=[],nextPending=new Map<number,{value:string;remaining:number}>();for(const[col,item]of pending){values[col]=item.value;if(item.remaining>1)nextPending.set(col,{value:item.value,remaining:item.remaining-1})}let col=0;for(const cell of cells){while(values[col]!==undefined)col++;for(let span=0;span<cell.colspan;span++){values[col+span]=cell.value;if(cell.rowspan>1)nextPending.set(col+span,{value:cell.value,remaining:cell.rowspan-1})}col+=cell.colspan}pending.clear();for(const entry of nextPending)pending.set(...entry);rows.push({values:Array.from({length:values.length},(_,index)=>values[index]??""),header:cells.every(cell=>cell.header)})}const firstData=rows.findIndex(row=>/^([1-6]|設定[1-6])$/.test(row.values[0]??"")),headerRows=firstData>=0?rows.slice(0,firstData):rows.filter(row=>row.header),headerRow=headerRows.at(-1)??(firstData<0&&rows[0]?.values.length>1?rows[0]:undefined),headers=(headerRow?.values??[]).filter(Boolean),headerIndex=headerRow?rows.indexOf(headerRow):-1,dataRows=(firstData>=0?rows.slice(firstData):rows.slice(headerIndex+1)).map(row=>row.values);return{headers,rows:dataRows}}
export type ProfileHeadingMapping=readonly[RegExp,string];
export const defaultProfileMappings:ProfileHeadingMapping[]=[
  [/AT初当り確率/,"atInitialRate"],[/CZ出現率/,"czInitialRate"],[/弱チェリー.*CZ当選率/,"weakCherryCzSuccessRate"],[/規定ゲーム数.*100G以内/,"within100GameHitRate"],[/AT直撃当選率/,"atDirectHitRate"],[/AT引き戻し当選率/,"atReturnRate"],[/下段リプレイ.*出現率/,"lowerReplayRate"],[/AT終了画面/,"endScreenIndications"],
];
export function parseStructuredProfileHtml(html:string,mappings:ProfileHeadingMapping[]=defaultProfileMappings):StructuredExtractedSection[]{const clean=cleanHtml(html),headings=[...clean.matchAll(/<h([1234])\b[^>]*>([\s\S]*?)<\/h\1\s*>/gi)];const sections:StructuredExtractedSection[]=[];for(let index=0;index<headings.length;index++){const heading=headings[index],sectionTitle=text(heading[2]),mapping=mappings.find(([pattern])=>pattern.test(sectionTitle));if(!mapping)continue;const start=(heading.index??0)+heading[0].length,end=headings[index+1]?.index??clean.length,body=clean.slice(start,end),tableMatch=body.match(/<table\b[^>]*>([\s\S]*?)<\/table\s*>/i),paragraphs=[...body.matchAll(/<p\b[^>]*>([\s\S]*?)<\/p\s*>/gi)].map(item=>text(item[1])).filter(item=>item&&!/広告|関連記事|ランキング/.test(item)),note=paragraphs.length?paragraphs.join(" "):null;if(tableMatch){const table=parseTable(tableMatch[0]);if(!table.headers.length||!table.rows.length)continue;sections.push({sectionTitle,metricKey:mapping[1],sectionKey:mapping[1],tableHeaders:table.headers,rows:table.rows,note,extractedFrom:"table",extractedValue:[table.headers,...table.rows].map(row=>row.join(" | ")),rawLabel:sectionTitle});continue}if(note)sections.push({sectionTitle,metricKey:mapping[1],sectionKey:mapping[1],tableHeaders:[],rows:[],note,extractedFrom:"paragraph",extractedValue:note,rawLabel:sectionTitle})}return sections}
