"use client";
import { useEffect,useRef,useState } from "react";
import Image from "next/image";
import type { SessionCompanionContext } from "@/lib/ai/companion";
import { formatCompanionAnswer } from "@/lib/ai/companionFormat";
import { compressIdentificationImage,type CompressedImage } from "@/lib/ai/imageCompression";
import { formatImageBytes } from "@/lib/ai/imageLimits";
import { requestSessionScene } from "@/lib/ai/sceneClient";
import type { SessionSceneContext,SessionSceneResult } from "@/lib/ai/scene";

type Message={role:"user"|"assistant";text:string};
type SceneAction="record"|"state";
const suggestions=["我現在最該注意什麼？","這台的 CZ、AT 怎麼辨認？","哪些按鈕需要記錄？"];
function Answer({text}:{text:string}){return <>{formatCompanionAnswer(text).map((block,index)=><div className={`ai-answer-${block.kind}`} key={index}>{block.kind==="bullet"&&<span aria-hidden="true">•</span>}<p>{block.segments.map((segment,segmentIndex)=>segment.bold?<strong key={segmentIndex}>{segment.text}</strong>:<span key={segmentIndex}>{segment.text}</span>)}</p></div>)}</>}
function imageError(value:unknown){const message=value instanceof Error?value.message:"";if(message==="heic_decode_failed")return"這台裝置暫時無法讀取 HEIC，請改用 JPEG 或截圖。";if(message==="compressed_too_large")return"壓縮後圖片仍超過上限，請重新拍攝。";if(message==="unsupported_image")return"請選擇 JPEG、PNG、WebP 或裝置可解碼的 HEIC 圖片。";return message||"無法處理這張圖片，請重新拍攝。"}

export function AICompanionDrawer({context,sceneContext,onConfirmScene,onClose}:{context:SessionCompanionContext;sceneContext?:SessionSceneContext;onConfirmScene?:(controlId:string,action:SceneAction)=>void;onClose:()=>void}){
  const [question,setQuestion]=useState(""),[messages,setMessages]=useState<Message[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
  const [sceneLoading,setSceneLoading]=useState(false),[sceneError,setSceneError]=useState(""),[sceneImage,setSceneImage]=useState<CompressedImage>(),[sceneResult,setSceneResult]=useState<SessionSceneResult>(),[previewUrl,setPreviewUrl]=useState("");
  const cameraInput=useRef<HTMLInputElement>(null),albumInput=useRef<HTMLInputElement>(null);
  useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl)},[previewUrl]);
  async function send(next=question){const clean=next.trim();if(!clean||loading)return;setMessages(items=>[...items,{role:"user",text:clean}]);setQuestion("");setError("");setLoading(true);try{const response=await fetch("/api/ai/session-companion",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:clean,context})}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"AI 暫時無法回答");setMessages(items=>[...items,{role:"assistant",text:payload.answer}])}catch(value){setError(value instanceof Error?value.message:"AI 暫時無法回答")}finally{setLoading(false)}}
  async function recognize(file?:File){if(!file||!sceneContext||sceneLoading)return;setSceneError("");setSceneResult(undefined);setSceneLoading(true);try{const compressed=await compressIdentificationImage(file);setSceneImage(compressed);setPreviewUrl(current=>{if(current)URL.revokeObjectURL(current);return URL.createObjectURL(compressed.file)});setSceneResult(await requestSessionScene(compressed,sceneContext))}catch(value){setSceneError(imageError(value))}finally{setSceneLoading(false);if(cameraInput.current)cameraInput.current.value="";if(albumInput.current)albumInput.current.value=""}}
  function confirm(controlId:string,action:SceneAction){onConfirmScene?.(controlId,action);onClose()}
  return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer ai-companion-drawer" onClick={event=>event.stopPropagation()}><div className="drawer-handle"/><div className="drawer-head"><div><span>AI COMPANION</span><h2>陪你看懂現在這局</h2></div><button onClick={onClose}>×</button></div><div className="ai-summary"><span>{context.machineName}</span><b>{context.observedGame.toLocaleString()} G</b><span>狀態 {context.currentState}</span><span>投入 ¥{context.investmentYen.toLocaleString()} · 持枚 {context.medals}</span></div>
  {sceneContext&&<section className="scene-recognition"><div className="scene-recognition-head"><div><small>PHOTO CHECK</small><h3>拍畫面，辨認現在場景</h3></div></div><p>AI 只會比對這個 Session 已有的記錄項目；確認後才會寫入。</p><div className="scene-photo-actions"><label className="primary-button">📷 拍現在畫面<input ref={cameraInput} hidden type="file" accept="image/*,.heic,.heif" capture="environment" onChange={event=>void recognize(event.target.files?.[0])}/></label><label className="secondary-button">從相簿選擇<input ref={albumInput} hidden type="file" accept="image/*,.heic,.heif" onChange={event=>void recognize(event.target.files?.[0])}/></label></div>{sceneLoading&&<div className="scene-loading">壓縮並辨識畫面中…</div>}{sceneError&&<p className="ai-error">{sceneError}</p>}{sceneImage&&previewUrl&&<div className="scene-preview"><Image unoptimized width={sceneImage.width} height={sceneImage.height} src={previewUrl} alt="等待確認的遊戲畫面"/><small>原始 {formatImageBytes(sceneImage.originalBytes)} → 壓縮後 {formatImageBytes(sceneImage.compressedBytes)} · {sceneImage.width} × {sceneImage.height}</small></div>}{sceneResult&&<div className={`scene-result ${sceneResult.status}`}><h4>{sceneResult.status==="matched"?"找到可能對應的場景":sceneResult.status==="uncertain"?"目前無法可靠確認":"沒有找到對應場景"}</h4><p>{sceneResult.summaryZh}</p>{sceneResult.visibleText.length>0&&<small>畫面文字：{sceneResult.visibleText.join("・")}</small>}{sceneResult.candidates.map(candidate=>{const control=sceneContext.controls.find(item=>item.id===candidate.controlId);if(!control)return null;return <article key={candidate.controlId}><strong>{control.labelZh}</strong><small>{candidate.confidence==="high"?"高":candidate.confidence==="medium"?"中":"低"}信心 · {candidate.reason}</small><button className="primary-button" onClick={()=>confirm(control.id,"record")}>{control.controlType==="choice"?"確認並開啟選項":`確認並記錄「${control.labelZh}」+1`}</button>{control.stateEffect&&<button className="secondary-button" onClick={()=>confirm(control.id,"state")}>只切換為 {control.stateEffect.toUpperCase()}</button>}</article>})}</div>}</section>}
  <div className="ai-chat">{messages.length===0&&<div className="mock-reply">也可以直接問我現在該注意什麼。</div>}{messages.map((message,index)=><article className={message.role} key={`${message.role}-${index}`}>{message.role==="assistant"?<Answer text={message.text}/>:message.text}</article>)}{loading&&<article className="assistant">整理指南與目前紀錄中…</article>}{error&&<p className="ai-error">{error}</p>}</div><div className="suggestions">{suggestions.map(item=><button key={item} onClick={()=>void send(item)}>{item}</button>)}</div><form className="ai-input" onSubmit={event=>{event.preventDefault();void send()}}><input maxLength={300} value={question} onChange={event=>setQuestion(event.target.value)} placeholder="輸入想問的問題…"/><button disabled={loading||!question.trim()}>送出</button></form></aside></div>
}
