"use client";
import { useEffect,useRef,useState } from "react";
import Image from "next/image";
import { buildCompanionDecision,DEFAULT_COMPANION_PREFERENCES,type SessionCompanionContext,type SessionCompanionMessage,type SessionCompanionMode,type SessionCompanionPreferences } from "@/lib/ai/companion";
import { loadCompanionPreferences,saveCompanionPreferences } from "@/lib/ai/companionPreferences";
import { formatCompanionAnswer } from "@/lib/ai/companionFormat";
import { compressIdentificationImage,type CompressedImage } from "@/lib/ai/imageCompression";
import { formatImageBytes } from "@/lib/ai/imageLimits";
import { requestSessionScene } from "@/lib/ai/sceneClient";
import type { SessionSceneContext,SessionSceneResult } from "@/lib/ai/scene";

type SceneAction="record"|"state";
const modeLabels:Record<SessionCompanionMode,string>={live:"🎮 陪玩",decision:"🧭 冷靜判斷",review:"📊 小回顧"};
const suggestions:Record<SessionCompanionMode,string[]>={live:["我現在走到哪一段？","現在最該注意什麼？","這台的爽點在哪裡？"],decision:["現在還適合繼續嗎？","幫我檢查有沒有沉沒成本","依我的預算重新判斷"],review:["整理這局走過的路線","哪些決策合理？","下次最值得改善什麼？"]};
function Answer({text}:{text:string}){return <>{formatCompanionAnswer(text).map((block,index)=><div className={`ai-answer-${block.kind}`} key={index}>{block.kind==="bullet"&&<span aria-hidden="true">•</span>}<p>{block.segments.map((segment,segmentIndex)=>segment.bold?<strong key={segmentIndex}>{segment.text}</strong>:<span key={segmentIndex}>{segment.text}</span>)}</p></div>)}</>}
function imageError(value:unknown){const message=value instanceof Error?value.message:"";if(message==="heic_decode_failed")return"這台裝置暫時無法讀取 HEIC，請改用 JPEG 或截圖。";if(message==="compressed_too_large")return"壓縮後圖片仍超過上限，請重新拍攝。";if(message==="unsupported_image")return"請選擇 JPEG、PNG、WebP 或裝置可解碼的 HEIC 圖片。";return message||"無法處理這張圖片，請重新拍攝。"}
function japanLocalTime(){return new Intl.DateTimeFormat("zh-TW",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date())}

export function AICompanionDrawer({context,sceneContext,onConfirmScene,onClose}:{context:SessionCompanionContext;sceneContext?:SessionSceneContext;onConfirmScene?:(controlId:string,action:SceneAction)=>void;onClose:()=>void}){
  const [mode,setMode]=useState<SessionCompanionMode>("live"),[question,setQuestion]=useState(""),[messages,setMessages]=useState<SessionCompanionMessage[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
  const [preferences,setPreferences]=useState<SessionCompanionPreferences>(DEFAULT_COMPANION_PREFERENCES);
  const [sceneLoading,setSceneLoading]=useState(false),[sceneError,setSceneError]=useState(""),[sceneImage,setSceneImage]=useState<CompressedImage>(),[sceneResult,setSceneResult]=useState<SessionSceneResult>(),[previewUrl,setPreviewUrl]=useState("");
  const cameraInput=useRef<HTMLInputElement>(null),albumInput=useRef<HTMLInputElement>(null);
  useEffect(()=>setPreferences(loadCompanionPreferences()),[]);
  useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl)},[previewUrl]);
  const liveContext:SessionCompanionContext={...context,japanLocalTime:japanLocalTime(),preferences,decision:buildCompanionDecision(context.investmentYen,context.peakMedals,preferences)};
  function updatePreferences(next:SessionCompanionPreferences){setPreferences(next);saveCompanionPreferences(next)}
  async function send(next=question){const clean=next.trim();if(!clean||loading)return;const history=[...messages],userMessage:SessionCompanionMessage={role:"user",text:sceneImage?`📷 ${clean}`:clean};setMessages(items=>[...items,userMessage]);setQuestion("");setError("");setLoading(true);try{
    let response:Response;
    if(sceneImage){const form=new FormData();form.set("question",clean);form.set("mode",mode);form.set("context",JSON.stringify(liveContext));form.set("history",JSON.stringify(history));form.set("image",sceneImage.file);response=await fetch("/api/ai/session-companion",{method:"POST",body:form})}
    else response=await fetch("/api/ai/session-companion",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:clean,context:liveContext,history,mode})});
    const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"AI 暫時無法回答");setMessages(items=>[...items,{role:"assistant",text:payload.answer}])
  }catch(value){setError(value instanceof Error?value.message:"AI 暫時無法回答")}finally{setLoading(false)}}
  async function selectPhoto(file?:File){if(!file)return;setSceneError("");setSceneResult(undefined);try{const compressed=await compressIdentificationImage(file);setSceneImage(compressed);setPreviewUrl(current=>{if(current)URL.revokeObjectURL(current);return URL.createObjectURL(compressed.file)})}catch(value){setSceneError(imageError(value))}finally{if(cameraInput.current)cameraInput.current.value="";if(albumInput.current)albumInput.current.value=""}}
  async function recognizeSelected(){if(!sceneImage||!sceneContext||sceneLoading)return;setSceneError("");setSceneResult(undefined);setSceneLoading(true);try{setSceneResult(await requestSessionScene(sceneImage,sceneContext))}catch(value){setSceneError(imageError(value))}finally{setSceneLoading(false)}}
  function clearPhoto(){setSceneImage(undefined);setSceneResult(undefined);setPreviewUrl(current=>{if(current)URL.revokeObjectURL(current);return""})}
  function confirm(controlId:string,action:SceneAction){onConfirmScene?.(controlId,action);onClose()}
  const decision=liveContext.decision;
  return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer ai-companion-drawer" onClick={event=>event.stopPropagation()}><div className="drawer-handle"/><div className="drawer-head"><div><span>SLOT AI COMPANION</span><h2>陪你看懂現在這局</h2></div><button aria-label="關閉 AI 助手" onClick={onClose}>×</button></div>
    <div className="ai-mode-tabs" aria-label="AI 陪打模式">{(Object.keys(modeLabels) as SessionCompanionMode[]).map(item=><button className={mode===item?"active":""} aria-pressed={mode===item} key={item} onClick={()=>setMode(item)}>{modeLabels[item]}</button>)}</div>
    <div className="ai-summary"><span>{context.machineName}</span><b>{context.observedGame.toLocaleString()} G</b><span>狀態 {context.currentState}</span><span>投入 ¥{context.investmentYen.toLocaleString()} · 持枚 {context.medals}</span></div>
    {context.journey.length>0&&<div className="ai-journey" aria-label="目前遊戲流程">{context.journey.map((item,index)=><span className={item.includes(context.currentState)||context.currentState.includes(item)?"active":""} key={`${item}-${index}`}>{item}</span>)}</div>}
    {mode==="decision"&&<div className={`ai-decision-status ${decision.investmentStatus}`}><strong>{decision.investmentStatus==="hard_stop"?"已達單台停止線":decision.investmentStatus==="decision_point"?"已到重新判斷點":"尚未到預算判斷點"}</strong><small>{decision.protectedMedals!==null?`Profit Lock 保護線 ${decision.protectedMedals.toLocaleString()} 枚`:`最高持枚 ${context.peakMedals.toLocaleString()} 枚`}</small></div>}
    <section className="scene-recognition"><div className="scene-recognition-head"><div><small>PHOTO COMPANION</small><h3>拍給我看，先一起看懂</h3></div></div><p>照片預設只用來解釋畫面；只有你另外確認後，系統才會記錄。</p><div className="scene-photo-actions"><label className="primary-button">📷 拍現在畫面<input ref={cameraInput} hidden type="file" accept="image/*,.heic,.heif" capture="environment" onChange={event=>void selectPhoto(event.target.files?.[0])}/></label><label className="secondary-button">從相簿選擇<input ref={albumInput} hidden type="file" accept="image/*,.heic,.heif" onChange={event=>void selectPhoto(event.target.files?.[0])}/></label></div>{sceneError&&<p className="ai-error">{sceneError}</p>}{sceneImage&&previewUrl&&<div className="scene-preview"><Image unoptimized width={sceneImage.width} height={sceneImage.height} src={previewUrl} alt="準備詢問 AI 的遊戲畫面"/><small>原始 {formatImageBytes(sceneImage.originalBytes)} → 壓縮後 {formatImageBytes(sceneImage.compressedBytes)} · {sceneImage.width} × {sceneImage.height}</small><div className="scene-preview-actions"><button className="primary-button" disabled={loading} onClick={()=>void send("這是什麼畫面？現在代表什麼，接下來看什麼？")}>問這張畫面</button>{sceneContext&&<button className="secondary-button" disabled={sceneLoading} onClick={()=>void recognizeSelected()}>{sceneLoading?"檢查中…":"檢查可記錄項目"}</button>}<button className="scene-clear" onClick={clearPhoto}>移除照片</button></div></div>}{sceneResult&&<div className={`scene-result ${sceneResult.status}`}><h4>{sceneResult.status==="matched"?"找到可能對應的記錄":sceneResult.status==="uncertain"?"目前無法可靠確認":"沒有找到對應記錄"}</h4><p>{sceneResult.summaryZh}</p>{sceneResult.visibleText.length>0&&<small>畫面文字：{sceneResult.visibleText.join("・")}</small>}{sceneResult.candidates.map(candidate=>{const control=sceneContext?.controls.find(item=>item.id===candidate.controlId);if(!control)return null;return <article key={candidate.controlId}><strong>{control.labelZh}</strong><small>{candidate.confidence==="high"?"高":candidate.confidence==="medium"?"中":"低"}信心 · {candidate.reason}</small><button className="primary-button" onClick={()=>confirm(control.id,"record")}>{control.controlType==="choice"?"確認並開啟選項":`確認並記錄「${control.labelZh}」+1`}</button>{control.stateEffect&&<button className="secondary-button" onClick={()=>confirm(control.id,"state")}>只切換為 {control.stateEffect.toUpperCase()}</button>}</article>})}</div>}</section>
    <div className="ai-chat">{messages.length===0&&<div className="mock-reply">{mode==="live"?"傳畫面或直接問，我會先陪你看懂現在這段。":mode==="decision"?"這裡會把演出熱度和續打理由分開判斷。":"我會整理路線，並分開看決策品質與最後結果。"}</div>}{messages.map((message,index)=><article className={message.role} key={`${message.role}-${index}`}>{message.role==="assistant"?<Answer text={message.text}/>:message.text}</article>)}{loading&&<article className="assistant">{sceneImage?"正在看畫面與目前進度…":"整理指南與目前紀錄中…"}</article>}{error&&<p className="ai-error">{error}</p>}</div>
    <div className="suggestions">{suggestions[mode].map(item=><button key={item} onClick={()=>void send(item)}>{item}</button>)}</div>
    <details className="ai-preferences"><summary>我的陪打設定</summary><div><label>玩法偏好<select value={preferences.playStyle} onChange={event=>updatePreferences({...preferences,playStyle:event.target.value as SessionCompanionPreferences["playStyle"]})}><option value="balanced">平衡</option><option value="conditions">偏條件</option><option value="entertainment">偏娛樂</option></select></label><label>重新判斷<input inputMode="numeric" value={preferences.decisionPointYen} onChange={event=>updatePreferences({...preferences,decisionPointYen:Number(event.target.value)})}/><span>円</span></label><label>單台停止線<input inputMode="numeric" value={preferences.hardStopYen} onChange={event=>updatePreferences({...preferences,hardStopYen:Number(event.target.value)})}/><span>円</span></label><label>最大回吐<input inputMode="numeric" value={preferences.maxGivebackPercent} onChange={event=>updatePreferences({...preferences,maxGivebackPercent:Number(event.target.value)})}/><span>%</span></label></div></details>
    <form className="ai-input" onSubmit={event=>{event.preventDefault();void send()}}><input maxLength={300} value={question} onChange={event=>setQuestion(event.target.value)} placeholder={sceneImage?"針對這張畫面提問…":"輸入想問的問題…"}/><button disabled={loading||!question.trim()}>送出</button></form>
  </aside></div>
}
