"use client";
import { useEffect, useState } from "react";
import { deleteCustomRecord, saveCustomRecord, validateCustomRecord, type CustomRecordDefinition } from "@/lib/customRecords";
import styles from "./CustomRecordEditor.module.css";

export function CustomRecordEditor({machineId,definitions,onChange,onClose}:{machineId:string;definitions:CustomRecordDefinition[];onChange:(definitions:CustomRecordDefinition[],saved?:CustomRecordDefinition,deleted?:CustomRecordDefinition)=>void;onClose:()=>void}){
  const[items,setItems]=useState(definitions),[editing,setEditing]=useState<CustomRecordDefinition>(),[name,setName]=useState(""),[type,setType]=useState<"counter"|"choice">("counter"),[choices,setChoices]=useState(""),[quick,setQuick]=useState(true),[error,setError]=useState("");
  useEffect(()=>setItems(definitions),[definitions]);
  function reset(){setEditing(undefined);setName("");setType("counter");setChoices("");setQuick(true);setError("")}
  function edit(item:CustomRecordDefinition){setEditing(item);setName(item.name);setType(item.type);setChoices(item.choices.join(", "));setQuick(item.quick);setError("")}
  function save(){const trimmed=name.trim(),parsed=choices.split(/[,、\n]/).map(item=>item.trim()).filter(Boolean);const definition:CustomRecordDefinition={id:editing?.id??crypto.randomUUID(),machineId,name:trimmed,type,choices:type==="choice"?parsed:[],quick},validation=validateCustomRecord(definition);if(validation){setError(validation);return}if(!saveCustomRecord(definition)){setError("保存失敗，請確認瀏覽器空間");return}const next=[...items.filter(item=>item.id!==definition.id),definition];setItems(next);onChange(next,definition);reset()}
  function remove(item:CustomRecordDefinition){if(!deleteCustomRecord(machineId,item.id)){setError("刪除失敗");return}const next=items.filter(value=>value.id!==item.id);setItems(next);onChange(next,undefined,item);if(editing?.id===item.id)reset()}
  return <><p className="eyebrow">CUSTOM RECORD</p><h2>自訂記錄</h2><p className="conflict-copy">依機台保存在這個瀏覽器；不會參與設定推測，也不會冒充 P-WORLD 資料。</p>{items.length>0&&<div className="counter-stack mt-3">{items.map(item=><div className={styles.item} key={item.id}><div><strong>{item.name}</strong><small>{item.type==="choice"?`Choice · ${item.choices.length} 選項`:"Counter"}{item.quick?" · 快速記錄":""}</small></div><button onClick={()=>edit(item)}>修改</button><button onClick={()=>remove(item)}>刪除</button></div>)}</div>}<label className="mt-3">名稱</label><input className="input mt-2" value={name} onChange={event=>setName(event.target.value)} placeholder="例如：特殊畫面"/><label className="mt-3">類型</label><select className="input mt-2" value={type} onChange={event=>setType(event.target.value as "counter"|"choice")}><option value="counter">Counter</option><option value="choice">Choice</option></select>{type==="choice"&&<><label className="mt-3">選項（至少兩個，以逗號分隔）</label><input className="input mt-2" value={choices} onChange={event=>setChoices(event.target.value)} placeholder="選項 A, 選項 B"/></>}<label className="mt-3"><input type="checkbox" checked={quick} onChange={event=>setQuick(event.target.checked)}/> 顯示於快速記錄</label>{error&&<p className={`${styles.error} mt-2`}>{error}</p>}<button className="primary-button mt-3" onClick={save}>{editing?"保存修改":"新增並立即使用"}</button>{editing&&<button className="secondary-button mt-2" onClick={reset}>取消修改</button>}<button className="secondary-button mt-2" onClick={onClose}>完成</button></>
}
