"use client";
import Link from "next/link";
import Image from "next/image";
import { useEffect,useState } from "react";
import type { MachineCatalogRecord } from "@/types/catalog";
import type { MachineGuide } from "@/types/machineGuide";
import { getGuideCacheState,loadCachedGuideAsync,type GuideCacheState } from "@/lib/machine-guide/storage";
import { refreshCachedMachineGuide } from "@/lib/machine-guide/refresh";
import { GuideFeedback } from "@/components/GuideFeedback";
import { machineFromGuide } from "@/lib/machine-guide/session";
import { buildVisualGuideDisplaySections } from "@/lib/machine-guide/visualPresentation";
import { StartSession } from "./StartSession";

const statusLabel={usable:"可使用",partial:"部分資料",no_data:"尚無資料"} as const;
export function MachineGuideView({record}:{record:MachineCatalogRecord}){
  const[guide,setGuide]=useState<MachineGuide|null>(null),[cacheState,setCacheState]=useState<GuideCacheState>("missing"),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{let active=true;loadCachedGuideAsync(record.id).then(cachedGuide=>{if(active){setGuide(cachedGuide?.guide??null);setCacheState(cachedGuide?"current":getGuideCacheState(record.id));setReady(true)}});return()=>{active=false}},[record.id]);
  async function refresh(){setBusy(true);setError("");try{const next=await refreshCachedMachineGuide(record.id);setGuide(next);setCacheState("current")}catch(reason){setError(reason instanceof Error?reason.message:"機台指南建立失敗。")}finally{setBusy(false)}}
  if(!ready)return <main className="page"><div className="empty">正在讀取此裝置的機台指南…</div></main>;
  if(!guide)return <main className="page"><div className="empty card"><strong>{cacheState==="stale"?"此裝置的舊版指南已失效":"此裝置尚無機台指南"}</strong><p>{cacheState==="stale"?"舊版快取不會冒充最新整理結果。重新建立只會更新本機指南，不影響既有 Session。":"會以 P-WORLD 為主，並在已支援的機種加入補充攻略來源。"}</p><button className="primary-button mt-5" disabled={busy} onClick={refresh}>{busy?"正在重新建立…":cacheState==="stale"?"重新建立機台指南":"建立機台指南"}</button>{error&&<div className="guide-error mt-3" role="alert">{error}<p>既有 Session 與遊玩紀錄不受影響。</p></div>}<Link href={`/catalog/${encodeURIComponent(record.id)}`} className="secondary-button mt-3">回機種詳細頁</Link></div></main>;
  const machine=machineFromGuide(guide),player=guide.playerGuideZh,displaySections=buildVisualGuideDisplaySections(guide);
  return <main className="page guide-page">
    <section className="catalog-detail-hero card"><div className="guide-hero-badges"><span className="badge">{statusLabel[guide.status]}</span>{guide.images?.length?<span className="badge visual-guide-badge">圖文指南</span>:null}</div><h1>{guide.displayNameZh||guide.officialNameJa}</h1><p>{guide.officialNameJa}</p><small>{guide.manufacturer} · {guide.machineType}</small></section>
    <div className="notice mt-3">已整理成繁體中文玩家重點；需要查證時再展開原始日文。</div>
    <nav className="guide-quick-nav" aria-label="機台指南快速導覽"><a href="#guide-basics">快速看懂</a><a href="#guide-highlights">三個重點</a><a href="#guide-records">記錄項目</a><a href="#guide-details">完整內容</a><Link href="/glossary">新手術語</Link></nav>
    <section id="guide-basics" className="section card guide-section"><header><div><h2>60 秒看懂這台</h2><small>繁體中文玩家版</small></div><span>{guide.availability.sessionTemplate==="available"?"可開始記錄":"部分資料"}</span></header><p className="guide-summary">{player?.overview??"目前尚無簡化說明。"}</p>{player?.goals.length?<ul>{player.goals.map((goal,index)=><li key={index}>{goal}</li>)}</ul>:<p>目前尚無遊玩重點。</p>}</section>
    <section id="guide-highlights" className="section card guide-section"><header><div><h2>今天先記住這三件事</h2><small>看到什麼 → 按哪個記錄</small></div></header>{player?.highlights.length?player.highlights.map(item=><article key={item.id} className="guide-paragraph"><strong>{item.label}</strong><p>{item.meaning}</p><p>{item.recordWhen}</p></article>):<p>目前沒有可靠的具名事件，先記錄總遊玩 G；需要時可新增自訂記錄。</p>}</section>
    <section id="guide-records" className="section card guide-section"><header><div><h2>本機可記錄項目</h2><small>SESSION TEMPLATE</small></div><span>{guide.sessionModules.length} 項</span></header>{guide.sessionModules.map(module=><p className="guide-paragraph" key={module.id}>{module.labelZh}<small> {module.labelJa}</small></p>)}</section>
    <div id="guide-details">{displaySections.map(section=><section className="section card guide-section" key={section.key}><header><div><h2>{section.title}</h2><small>中文重點</small></div>{section.images.length?<span>{section.images.length} 張圖解</span>:null}</header><p className="guide-summary">{section.summary||"目前尚無可靠說明。"}</p>{section.points.length>0&&<ul>{section.points.map((point,index)=><li key={index}>{point}</li>)}</ul>}{section.images.length?<div className="visual-guide-gallery">{section.images.map(image=><figure key={image.id}><Image src={image.displayUrl} alt={image.captionZh} width={image.width??590} height={image.height??331} sizes="(max-width: 520px) calc(100vw - 70px), 450px" unoptimized loading="lazy"/><figcaption><strong>{image.captionZh}</strong><small>{image.altJa}</small></figcaption></figure>)}</div>:null}</section>)}</div>
    <details className="section card guide-section"><summary><strong>查看原始日文與表格</strong><small> 查證用・預設收合</small></summary>{guide.sections.map(section=><section className="mt-5" key={section.key}><header><div><h2>{section.titleZh}</h2><small>{section.titleJa}</small></div><span>{section.tables.length?`${section.tables.length} 表格`:section.paragraphsJa.length?"公開說明":"尚無資料"}</span></header>{section.paragraphsJa.slice(0,4).map((paragraph,index)=><p className="guide-paragraph" key={index}>{paragraph}</p>)}{section.tables.map(table=><article className="guide-table" key={table.id}><strong>{table.title}</strong><div><table><thead><tr>{table.headers.map((header,index)=><th key={index}>{header}</th>)}</tr></thead><tbody>{table.rows.map((row,rowIndex)=><tr key={rowIndex}>{table.headers.map((_,cellIndex)=><td key={cellIndex}>{row[cellIndex]||"尚無資料"}</td>)}</tr>)}</tbody></table></div></article>)}</section>)}</details>
    <section className="section card guide-missing"><h2>尚未取得的資料</h2>{guide.missingSections.length?<p>{guide.missingSections.join("、")}</p>:<p>本指南主要欄位均有可顯示內容。</p>}</section>
    <section id="guide-source" className="section card guide-source"><h2>來源與快取</h2><dl><dt>來源</dt><dd>{(guide.sources??[{name:guide.sourceName,url:guide.sourceUrl,status:"available" as const}]).map((source,index)=><span key={source.url}>{index>0?" · ":""}{source.status==="available"?<a href={source.url} target="_blank" rel="noreferrer">{source.name} ↗</a>:<>{source.name}（本次未取得）</>}</span>)}</dd><dt>擷取時間</dt><dd>{new Date(guide.retrievedAt).toLocaleString("zh-TW")}</dd><dt>指南保存</dt><dd>此瀏覽器 IndexedDB（不跨裝置同步）</dd>{guide.images?.length?<><dt>圖文素材</dt><dd>{guide.images.length} 張 · {(guide.images.reduce((sum,image)=>sum+(image.byteSize??0),0)/1024/1024).toFixed(1)} MB · {guide.images.some(image=>image.storageStatus==="stored")?"私人雲端資產":"來源即時讀取"}</dd></>:null}</dl>{guide.conflicts?.length?<div className="notice mt-3">有 {guide.conflicts.length} 組來源數值不一致；只暫停相關設定推測，其他指南內容仍可使用。</div>:null}{guide.sourceWarnings?.length?<details className="mt-3"><summary>補充來源狀態</summary>{guide.sourceWarnings.map(warning=><p key={warning}>{warning}</p>)}</details>:null}<button className="secondary-button mt-3" disabled={busy} onClick={refresh}>{busy?"正在重新整理…":"重新整理機台指南"}</button>{error&&<div className="guide-error mt-3" role="alert"><strong>重新整理失敗</strong><p>{error}</p><p>目前這份有效指南及所有既有 Session 均已保留。</p></div>}<GuideFeedback catalogId={record.id}/></section>
    <div className="notice mt-3">{guide.availability.settingEstimator==="unavailable"?"目前沒有可安全參與設定推測的資料。":"設定可能性只使用具完整設定值、明確分母且能由 Session 實際觀測的資料；結果一律為參考推測。"}</div>
    <StartSession machine={machine}/>
  </main>;
}
