"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import type { MachineCatalogRecord } from "@/types/catalog";
import type { MachineGuide } from "@/types/machineGuide";
import { loadCachedGuide } from "@/lib/machine-guide/storage";
import { machineFromGuide } from "@/lib/machine-guide/session";
import { StartSession } from "./StartSession";

const statusLabel={usable:"可使用",partial:"部分資料",no_data:"尚無資料"} as const;
export function MachineGuideView({record}:{record:MachineCatalogRecord}){const[guide,setGuide]=useState<MachineGuide|null>(null),[ready,setReady]=useState(false);useEffect(()=>{setGuide(loadCachedGuide(record.id)?.guide??null);setReady(true)},[record.id]);if(!ready)return<main className="page"><div className="empty">正在讀取此裝置的機台指南…</div></main>;if(!guide)return<main className="page"><div className="empty card"><strong>此裝置尚無機台指南</strong><p>請先回到機種詳細頁，從 P-WORLD 建立指南。</p><Link href={`/catalog/${encodeURIComponent(record.id)}`} className="primary-button mt-5">回機種詳細頁</Link></div></main>;const machine=machineFromGuide(guide);return<main className="page guide-page"><section className="catalog-detail-hero card"><span className="badge">{statusLabel[guide.status]}</span><h1>{guide.displayNameZh||guide.officialNameJa}</h1><p>{guide.officialNameJa}</p><small>{guide.manufacturer} · {guide.machineType}</small></section><div className="notice mt-3">本指南整理 P-WORLD 公開參考資料，可能不完整或隨來源更新；不是權威攻略、準確設定判定或獲利保證。</div>{guide.sections.map(section=><section className="section card guide-section" key={section.key}><header><div><h2>{section.titleZh}</h2><small>{section.titleJa}</small></div><span>{section.tables.length?`${section.tables.length} 表格`:section.paragraphsJa.length?"公開說明":"尚無資料"}</span></header>{section.summaryZh&&<p className="guide-summary">{section.summaryZh}</p>}{section.paragraphsJa.slice(0,4).map((paragraph,index)=><p className="guide-paragraph" key={index}>{paragraph}</p>)}{section.tables.map(table=><article className="guide-table" key={table.id}><strong>{table.title}</strong><div><table><thead><tr>{table.headers.map((header,index)=><th key={index}>{header}</th>)}</tr></thead><tbody>{table.rows.map((row,rowIndex)=><tr key={rowIndex}>{table.headers.map((_,cellIndex)=><td key={cellIndex}>{row[cellIndex]||"尚無資料"}</td>)}</tr>)}</tbody></table></div></article>)}</section>)}<section className="section card guide-missing"><h2>尚未取得的資料</h2>{guide.missingSections.length?<p>{guide.missingSections.join("、")}</p>:<p>本指南主要欄位均有可顯示內容。</p>}</section><section className="section card guide-source"><h2>來源與快取</h2><dl><dt>來源</dt><dd><a href={guide.sourceUrl} target="_blank" rel="noreferrer">P-WORLD ↗</a></dd><dt>擷取時間</dt><dd>{new Date(guide.retrievedAt).toLocaleString("zh-TW")}</dd><dt>保存位置</dt><dd>此瀏覽器 localStorage</dd></dl></section><div className="notice mt-3">設定可能性只使用來源中可完整解析、且能由 Session 實際觀測的設定 1～6 數值；結果一律為參考推測。</div><StartSession machine={machine}/></main>}
