"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { getMachine } from "@/data/machines";
import { loadSessions, saveSession } from "@/lib/storage";
import type { CounterDefinition, GameState, Session, SessionEvent, SessionMode } from "@/types";
import type { SessionCapability } from "@/types/machineGuide";
import { buildSessionUiModel, capabilityForCounter, type SessionRecordControl } from "@/lib/sessionUi";
import { CounterCard } from "./CounterCard";
import { SettingEstimator } from "./SettingEstimator";
import { SessionGuideDrawer } from "./SessionGuideDrawer";
import { changeSessionMode, controlsForSessionMode, loadLastSessionMode, normalizeSessionMode, saveLastSessionMode } from "@/lib/sessionModes";
import { SessionModePicker } from "./SessionModePicker";
import { loadCachedGuide } from "@/lib/machine-guide/storage";
import { loadCustomRecords, replaceCustomRecord, type CustomRecordDefinition } from "@/lib/customRecords";
import { CustomRecordEditor } from "./CustomRecordEditor";

type EditTarget = { kind: "tracker"; key: string } | { kind: "medals" } | null;
const time = (iso:string) => new Intl.DateTimeFormat("zh-TW",{hour:"2-digit",minute:"2-digit"}).format(new Date(iso));
export function SessionScreen({ id }: { id: string }) {
  const [session,setSession]=useState<Session>(); const [drawer,setDrawer]=useState(false); const [guideOpen,setGuideOpen]=useState(false); const [modeOpen,setModeOpen]=useState(false); const [customOpen,setCustomOpen]=useState(false); const [customs,setCustoms]=useState<CustomRecordDefinition[]>([]); const [lastMode,setLastMode]=useState<SessionMode>(); const [moreOpen,setMoreOpen]=useState(false); const [choiceTarget,setChoiceTarget]=useState<CounterDefinition>(); const [edit,setEdit]=useState<EditTarget>(null); const [editValue,setEditValue]=useState(""); const [help,setHelp]=useState<CounterDefinition>(); const [toast,setToast]=useState(""); const router=useRouter();
  const [guideUpdated,setGuideUpdated]=useState(false);
  useEffect(()=>setSession(loadSessions().find(item=>item.id===id)),[id]);
  const machine=useMemo(()=>session?.profileSnapshot??(session?getMachine(session.machineId):undefined),[session]);
  const machineId=machine?.id;
  useEffect(()=>{if(machineId){setLastMode(loadLastSessionMode(machineId));setCustoms(loadCustomRecords(machineId))}},[machineId]);
  useEffect(()=>{const catalogId=machine?.catalogId,retrievedAt=machine?.sessionGuide?.retrievedAt;if(!catalogId||!retrievedAt){setGuideUpdated(false);return}const current=loadCachedGuide(catalogId)?.guide;setGuideUpdated(Boolean(current&&current.retrievedAt!==retrievedAt))},[machine]);
  const uiModel=useMemo(()=>machine?buildSessionUiModel(machine):undefined,[machine]);
  const sessionMode=normalizeSessionMode(session?.mode),modeControls=uiModel?controlsForSessionMode(uiModel,sessionMode):undefined;
  function persist(next:Session){setSession(next);if(!saveSession(next)){setToast("儲存失敗，請確認瀏覽器空間");return;} setToast("已儲存");window.setTimeout(()=>setToast(""),900)}
  function event(type:SessionEvent["type"],label:string,value?:number):SessionEvent{return{id:crypto.randomUUID(),sessionId:id,createdAt:new Date().toISOString(),type,label,value}}
  function update(patch:Partial<Session>,ev?:SessionEvent){if(!session)return;persist({...session,...patch,events:ev?[ev,...session.events]:session.events})}
  const trackerDefinitions=machine?.profile.gameTrackers??[];
  const primaryTracker=trackerDefinitions.find(item=>item.primary)??trackerDefinitions[0];
  function trackerValue(key:string){return session?.trackers[key]??0}
  function metricValue(key:string){if(!session)return 0;const definition=machine?.profile.measurementMetrics.find(item=>item.key===key);if(!definition)return session.metrics[key]??0;const source=definition.source;if(source.type==="trackerDelta"){const baseline=session.trackerBaselines[source.trackerKey];return baseline===undefined?0:Math.max(0,trackerValue(source.trackerKey)-baseline)}if(source.type==="custom")return session.metrics[source.sessionMetricKey]??0;return session.metrics[source.type]??0}
  function initialHitStat(counterKey:"cz"|"at",count:number){const metric=machine?.profile.initialHitMetrics.find(item=>item.counterKey===counterKey);if(!metric)return undefined;const denominator=metricValue(metric.denominatorMetricKey);return {label:metric.labelZh,denominator,ratio:count>0&&denominator>0?`1 / ${(denominator/count).toFixed(1)}`:"尚無比率"}}
  function trackerPatch(key:string,value:number):Partial<Session>{if(!session)return{};const definition=trackerDefinitions.find(item=>item.key===key);const baseline=session.trackerBaselines[key];const isBaseline=baseline===undefined;const delta=isBaseline?0:Math.max(0,value-trackerValue(key));const metrics={...session.metrics};if(definition?.primary&&delta>0){metrics.observedTotalGame=(metrics.observedTotalGame??0)+delta;if(session.gameState==="normal")metrics.observedNormalGame=(metrics.observedNormalGame??0)+delta}return {trackers:{...session.trackers,[key]:value},trackerBaselines:isBaseline?{...session.trackerBaselines,[key]:value}:session.trackerBaselines,metrics,...(key==="dataGame"?{actualG:value}:{}),...(key==="lcdGame"?{displayG:value}:{})}}
  function addTracker(key:string,delta:number){if(!session)return;const definition=trackerDefinitions.find(item=>item.key===key);const value=Math.max(0,trackerValue(key)+delta);update(trackerPatch(key,value),event("game",`${definition?.labelZh??key} +${delta}`,value))}
  function setGameState(gameState:GameState){if(!session||session.gameState===gameState)return;const state=uiModel?.gameStates.find(item=>item.value===gameState);update({gameState},event("state",`狀態切換：${state?.label??gameState}`))}
  function adjustCounter(def:CounterDefinition,delta:number){if(!session)return;const raw=session.counters[def.key];const current=typeof raw==="number"?raw:0;const next=Math.max(0,current+delta);if(next===current)return;const relationship=machine?.profile.trialRelationships.find(item=>item.trialCounterKey===def.key);const counters={...session.counters,[def.key]:next};const trials={...session.trials};if(relationship){const records=[...(trials[relationship.id]??[])];if(delta>0)records.push({id:crypto.randomUUID(),relationshipId:relationship.id,createdAt:new Date().toISOString(),outcome:"pending"});else{const removed=records.pop();if(removed?.outcome==="success"){const outcomeRaw=counters[relationship.outcomeCounterKey];counters[relationship.outcomeCounterKey]=Math.max(0,(typeof outcomeRaw==="number"?outcomeRaw:0)-1)}}trials[relationship.id]=records}const capability=uiModel?capabilityForCounter(uiModel,def.key):undefined,state=delta>0?(capability?.stateEffect??def.eventState):undefined;update({counters,trials,...(state?{gameState:state}:{})},event("counter",`${def.labelZh} ${delta>0?"+1（新增 trial）":"-1 修正"}`,next))}
  function recordCounterEvent(def:CounterDefinition){if(!session)return;const raw=session.counters[def.key];const next=(typeof raw==="number"?raw:0)+1,capability=uiModel?capabilityForCounter(uiModel,def.key):undefined,state=capability?.stateEffect??def.eventState;update({counters:{...session.counters,[def.key]:next},...(state?{gameState:state}:{})},event("counter",`${def.labelZh}：記錄事件`,next))}
  function recordTrialOutcome(def:CounterDefinition,outcome:"success"|"failure"){if(!session||!def.trialRelationshipId)return;const records=[...(session.trials[def.trialRelationshipId]??[])];const index=records.map(record=>record.outcome).lastIndexOf("pending");if(index<0){setToast("請先記錄一次 parent trial");window.setTimeout(()=>setToast(""),1200);return}records[index]={...records[index],outcome,resolvedAt:new Date().toISOString()};const successes=records.filter(record=>record.outcome==="success").length;update({trials:{...session.trials,[def.trialRelationshipId]:records},counters:{...session.counters,[def.key]:successes},...(outcome==="success"&&def.eventState?{gameState:def.eventState}:{})},event("counter",`${def.labelZh}：${outcome==="success"?"成功":"失敗"}`))}
  function chooseCounter(def:CounterDefinition,value:string,label:string){if(!session)return;update({counters:{...session.counters,[def.key]:value}},event("counter",`${def.labelZh}：${label}`))}
  function addCounterPhoto(def:CounterDefinition,file:File){if(!session)return;update({counters:{...session.counters,[def.key]:{fileName:file.name,capturedAt:new Date().toISOString()}},...(def.eventState?{gameState:def.eventState}:{})},event("counter",`${def.labelZh}：已記錄圖片`))}
  function openTrackerEdit(key:string,value:number){setEdit({kind:"tracker",key});setEditValue(String(value))}
  function openMedalsEdit(){setEdit({kind:"medals"});setEditValue(String(session?.medals??0))}
  function commitEdit(){if(!session||!edit)return;const value=Math.max(0,Number.parseInt(editValue)||0);if(edit.kind==="medals")update({medals:value},event("medals","持枚修正",value));else{const definition=trackerDefinitions.find(item=>item.key===edit.key);const isBaseline=session.trackerBaselines[edit.key]===undefined;update(trackerPatch(edit.key,value),event("game",isBaseline?`${definition?.labelZh??edit.key} baseline：${value}`:`${definition?.labelZh??edit.key}更新`,value))}setEdit(null)}
  function recordMode(kind:"cz"|"at"){if(!session)return;const isCz=kind==="cz";const next=(isCz?session.czCount:session.atCount)+1;update({...(isCz?{czCount:next}:{atCount:next}),gameState:kind},event(kind,`${kind.toUpperCase()} +1 · 自動切換狀態`,next))}
  function recordCapability(capability:SessionCapability){if(capability.observationKey==="cz"){recordMode("cz");return}if(capability.observationKey==="at"){recordMode("at");return}if(!session)return;const raw=session.counters[capability.writeTarget.key],next=(typeof raw==="number"?raw:0)+1;update({counters:{...session.counters,[capability.writeTarget.key]:next},...(capability.stateEffect?{gameState:capability.stateEffect}:{})},event("counter",`${capability.labelZh}：記錄事件`,next))}
  function capabilityCount(capability:SessionCapability){if(capability.observationKey==="cz")return session?.czCount??0;if(capability.observationKey==="at")return session?.atCount??0;const value=session?.counters[capability.writeTarget.key];return typeof value==="number"?value:0}
  function recordControl(control:SessionRecordControl){const def=control.counter;if(!def){recordCapability(control.capability);return}if(def.type==="choice"){setChoiceTarget(def);return}if(def.type==="count"){adjustCounter(def,1);return}if(def.type==="event")recordCounterEvent(def)}
  function correctControl(control:SessionRecordControl){const def=control.counter;if(def){if(def.type==="count")adjustCounter(def,-1);else if(def.type==="event"&&session){const current=session.counters[def.key],next=Math.max(0,(typeof current==="number"?current:0)-1);update({counters:{...session.counters,[def.key]:next}},event("counter",`${def.labelZh} -1 修正`,next))}return}if(!session)return;const capability=control.capability;if(capability.observationKey==="cz"){const next=Math.max(0,session.czCount-1);update({czCount:next},event("cz","CZ -1 修正",next));return}if(capability.observationKey==="at"){const next=Math.max(0,session.atCount-1);update({atCount:next},event("at","AT -1 修正",next))}}
  function controlValue(control:SessionRecordControl){const def=control.counter;if(!def)return `${capabilityCount(control.capability)} 次`;const value=session?.counters[def.key];if(def.type==="choice")return typeof value==="string"?(def.choices?.find(choice=>choice.value===value)?.labelZh??value):"尚未選擇";return `${typeof value==="number"?value:0} 次`}
  function controlType(control:SessionRecordControl){const kind=control.capability.moduleKind;if(kind==="named_cz")return"CZ";if(kind==="at")return"AT";if(kind==="art")return"ART";if(kind==="big_reg_bonus")return"BONUS";if(kind==="end_evidence")return"CHOICE";return control.capability.controlType.toUpperCase()}
  function recordSpecial(){if(!session)return;update({gameState:"special"},event("special","記錄特殊畫面 · 自動切換狀態"))}
  function finish(){if(!session)return;const endedAt=new Date().toISOString();const next={...session,status:"completed" as const,endedAt,events:[event("end","Session 結算"),...session.events]};if(saveSession(next))router.push(`/summary/${id}`)}
  function switchMode(mode:SessionMode){if(!session||!machine)return;persist(changeSessionMode(session,mode));saveLastSessionMode(machine.id,mode);setLastMode(mode);setModeOpen(false);setMoreOpen(false)}
  function updateCustomRecords(definitions:CustomRecordDefinition[],saved?:CustomRecordDefinition,deleted?:CustomRecordDefinition){setCustoms(definitions);if(!session||!machine)return;if(saved){persist({...session,profileSnapshot:replaceCustomRecord(machine,saved)});return}if(deleted){setToast("已刪除日後使用；本 Session 保留此項以保護紀錄");window.setTimeout(()=>setToast(""),1800)}}
  if(!session)return <main className="page"><div className="empty"><span className="text-4xl">🕹️</span><p className="mt-4">找不到這筆 Session</p><Link href="/" className="secondary-button mt-5">回首頁</Link></div></main>;
  if(!machine||!uiModel)return null;
  const czLiveStat=initialHitStat("cz",session.czCount);
  const atLiveStat=initialHitStat("at",session.atCount);
  const observedTotal=metricValue("observedTotalGame");
  const guide=machine.sessionGuide;
  const showStateBar=uiModel.legacy||uiModel.gameStates.length>1;
  const renderQuickControl=(control:SessionRecordControl)=><article className={`quick-record-card ${control.counter?.type==="choice"?"is-choice":""}`} key={control.id}><button className="quick-record-main" onClick={()=>recordControl(control)}><small>{controlType(control)}</small><strong>{control.counter?.labelZh??control.capability.labelZh}</strong><span>{controlValue(control)}</span></button>{control.counter?.type!=="choice"&&<button className="quick-record-correct" onClick={()=>correctControl(control)} disabled={controlValue(control)==="0 次"}>−1 修正</button>}</article>;
  return <>
    <header className="session-header"><Link href="/" className="icon-button">×</Link><div><span>SESSION · 台號 {session.machineNumber}</span><h1>{machine.nameZh}</h1><small>{time(session.startedAt)} 開始</small></div><nav className="session-header-actions"><button className="session-guide-button" onClick={()=>setGuideOpen(true)}>指南</button><button className="session-guide-button" onClick={()=>setModeOpen(true)}>模式</button><button className="session-more" onClick={()=>setDrawer(true)}>AI</button></nav></header>
    <main className="page session-page">
      {guideUpdated&&<div className="observed-banner"><span>機台指南已更新</span><small>下一次建立 Session 時會套用新的記錄項目。</small></div>}
      {!uiModel.legacy&&uiModel.basicMode&&<div className="observed-banner"><span>基本記錄模式</span><small>目前只有總遊玩 G 可可靠記錄；不會自動補上 CZ／AT。</small><button className="secondary-button mt-2" onClick={()=>setCustomOpen(true)}>＋ 新增自訂記錄</button></div>}
      {showStateBar&&<section className="session-state-switcher" aria-label="目前遊戲狀態"><small>目前狀態</small><div>{uiModel.gameStates.map(state=><button key={state.value} className={session.gameState===state.value?"active":""} aria-pressed={session.gameState===state.value} onClick={()=>setGameState(state.value)}>{state.label}</button>)}</div></section>}
      <div className="observed-banner"><span>本 Session 已觀測</span><strong>{observedTotal.toLocaleString()} G</strong><small>依 baseline 後的實際增量</small></div>
      <section className="g-panel profile-trackers">{trackerDefinitions.map(definition=><button key={definition.key} onClick={()=>openTrackerEdit(definition.key,trackerValue(definition.key))}><span>{definition.labelZh}<small className="ja">{definition.labelJa}</small></span><strong>{trackerValue(definition.key).toLocaleString()}</strong><small>{session.trackerBaselines[definition.key]===undefined?"尚未設定 baseline":`起點 ${session.trackerBaselines[definition.key]}`}</small></button>)}</section>
      {primaryTracker&&<div className="game-actions"><button className="update-g-button" onClick={()=>openTrackerEdit(primaryTracker.key,trackerValue(primaryTracker.key))}><span>{session.trackerBaselines[primaryTracker.key]===undefined?"設定起始 ":"更新"}{primaryTracker.labelZh}</span><small>{session.trackerBaselines[primaryTracker.key]===undefined?"第一次輸入只保存 baseline":"輸入目前值以累加實際觀測 G"}</small></button>{primaryTracker.quickAdd&&<button className="quick-ten" disabled={session.trackerBaselines[primaryTracker.key]===undefined} onClick={()=>addTracker(primaryTracker.key,primaryTracker.quickAdd!)}>+{primaryTracker.quickAdd}<small>{session.trackerBaselines[primaryTracker.key]===undefined?"先設起點":"快捷"}</small></button>}</div>}
      <section className="stats-grid">
        <button onClick={()=>update({investmentYen:session.investmentYen+1000},event("investment","投入 +¥1,000",1000))}><span>投入</span><strong>¥{session.investmentYen.toLocaleString()}</strong><small>＋ ¥1,000</small></button>
        <button onClick={openMedalsEdit}><span>持枚</span><strong>{session.medals.toLocaleString()}</strong><small>點擊編輯</small></button>
        {uiModel.legacy&&<button onClick={()=>recordMode("cz")}><span>CZ</span><strong>{session.czCount}</strong><small>＋1 · 切換 CZ</small>{czLiveStat&&<em className="mode-live-stat">{czLiveStat.label} · {czLiveStat.ratio}</em>}</button>}
        {uiModel.legacy&&<button onClick={()=>recordMode("at")}><span>AT</span><strong>{session.atCount}</strong><small>＋1 · 切換 AT</small>{atLiveStat&&<em className="mode-live-stat">{atLiveStat.label} · {atLiveStat.ratio}</em>}</button>}
      </section>
      {!uiModel.legacy&&modeControls&&uiModel.recordControls.length>0&&<section className="section quick-record-section"><div className="section-title"><h2>{sessionMode==="full"?"完整記錄":"快速記錄"}</h2><span>{sessionMode==="full"?"全部可用項目":"最常用項目"}</span></div><div className="quick-record-grid">{modeControls.primary.map(renderQuickControl)}</div>{modeControls.overflow.length>0&&<><button className="more-records-button" aria-expanded={moreOpen} onClick={()=>setMoreOpen(value=>!value)}>更多記錄（{modeControls.overflow.length}）<span>{moreOpen?"收合":"展開"}</span></button>{moreOpen&&<div className="quick-record-grid more-records-grid">{modeControls.overflow.map(renderQuickControl)}</div>}</>}</section>}
      {uiModel.legacy&&uiModel.counterDefinitions.length>0&&<section className="section"><div className="section-title"><h2>Smart Counter</h2><span>舊 Session 相容模式</span></div><div className="counter-stack">{uiModel.counterDefinitions.map(def=>{const records=def.trialRelationshipId?session.trials[def.trialRelationshipId]??[]:[];const resolved=records.filter(record=>record.outcome!=="pending");const successes=resolved.filter(record=>record.outcome==="success").length;return <CounterCard key={def.key} definition={def} value={session.counters[def.key]} denominator={def.denominatorMetricKey?metricValue(def.denominatorMetricKey):undefined} relationshipStats={def.trialRelationshipId?{successes,total:resolved.length,pending:records.length-resolved.length}:undefined} onCount={delta=>adjustCounter(def,delta)} onEvent={()=>recordCounterEvent(def)} onOutcome={outcome=>recordTrialOutcome(def,outcome)} onChoice={(value,label)=>chooseCounter(def,value,label)} onPhoto={file=>addCounterPhoto(def,file)} onHelp={()=>setHelp(def)} />})}</div></section>}
      <SettingEstimator machine={machine} session={session} />
      <div className="session-secondary">{uiModel.legacy&&<button onClick={recordSpecial}>✦ 特殊畫面</button>}{!(uiModel.basicMode&&!uiModel.legacy)&&<button onClick={()=>setCustomOpen(true)}>＋ 自訂記錄</button>}<button onClick={()=>setDrawer(true)}>✣ 問 AI</button></div>
      <button className="danger-button mt-3" onClick={finish}>結算 Session</button>
    </main>
    {edit&&<div className="modal-backdrop" onClick={()=>setEdit(null)}><div className="modal" onClick={e=>e.stopPropagation()}><p className="eyebrow">CURRENT VALUE</p><h2>{edit.kind==="medals"?"編輯持枚":session.trackerBaselines[edit.key]===undefined?`設定${trackerDefinitions.find(item=>item.key===edit.key)?.labelZh??"Tracker"} baseline`:`更新${trackerDefinitions.find(item=>item.key===edit.key)?.labelZh??"Tracker"}`}</h2><p className="edit-hint">{edit.kind==="tracker"&&session.trackerBaselines[edit.key]===undefined?"第一次輸入只會保存坐下時的起始值，觀測量維持 0G。":"輸入目前顯示的完整數字；系統只把正向差值加入觀測量。"}</p><input autoFocus className="input mt-4" inputMode="numeric" value={editValue} onChange={e=>setEditValue(e.target.value)} /><button className="primary-button mt-3" onClick={commitEdit}>更新</button><button className="secondary-button mt-2" onClick={()=>setEdit(null)}>取消</button></div></div>}
    {help&&<div className="modal-backdrop" onClick={()=>setHelp(undefined)}><div className="modal" onClick={e=>e.stopPropagation()}><span className="text-4xl">{help.icon}</span><h2 className="mt-3">{help.labelZh}<small className="ja">{help.labelJa}</small></h2><dl className="help-list"><dt>簡短解釋</dt><dd>{help.description}</dd><dt>如何辨識</dt><dd>{help.recognition}</dd><dt>為什麼值得記</dt><dd>{help.reason}</dd></dl><button className="secondary-button mt-4" onClick={()=>setHelp(undefined)}>知道了</button></div></div>}
    {choiceTarget&&<div className="modal-backdrop" onClick={()=>setChoiceTarget(undefined)}><div className="modal quick-choice-modal" onClick={event=>event.stopPropagation()}><p className="eyebrow">CHOICE RECORD</p><h2>{choiceTarget.labelZh}<small className="ja">{choiceTarget.labelJa}</small></h2><div className="quick-choice-list">{choiceTarget.choices?.map(choice=><button className={session.counters[choiceTarget.key]===choice.value?"active":""} key={choice.value} onClick={()=>{chooseCounter(choiceTarget,choice.value,choice.labelZh);setChoiceTarget(undefined)}}><strong>{choice.labelZh}</strong><small>{choice.labelJa}</small></button>)}</div><button className="secondary-button mt-3" onClick={()=>setChoiceTarget(undefined)}>取消</button></div></div>}
    {modeOpen&&<div className="modal-backdrop" onClick={()=>setModeOpen(false)}><div className="modal" onClick={event=>event.stopPropagation()}><p className="eyebrow">DISPLAY MODE</p><h2>切換使用模式</h2><p className="conflict-copy">只改變畫面資訊量；G 數、投入、持枚與所有事件紀錄都會保留。</p><SessionModePicker lastMode={lastMode} currentMode={sessionMode} onSelect={switchMode}/><button className="secondary-button mt-3" onClick={()=>setModeOpen(false)}>取消</button></div></div>}
    {customOpen&&<div className="modal-backdrop" onClick={()=>setCustomOpen(false)}><div className="modal" onClick={event=>event.stopPropagation()}><CustomRecordEditor machineId={machine.id} definitions={customs} onChange={updateCustomRecords} onClose={()=>setCustomOpen(false)}/></div></div>}
    {guideOpen&&<SessionGuideDrawer guide={guide} machine={machine} state={session.gameState} recordControls={uiModel.recordControls} onClose={()=>setGuideOpen(false)}/>}
    {drawer&&<div className="drawer-backdrop" onClick={()=>setDrawer(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-handle"/><div className="drawer-head"><div><span>AI COMPANION</span><h2>陪你看懂現在這局</h2></div><button onClick={()=>setDrawer(false)}>×</button></div><div className="ai-summary"><span>{machine.nameZh}</span>{trackerDefinitions.map(def=><b key={def.key}>{def.labelZh} {trackerValue(def.key)}</b>)}<span>狀態 {uiModel.gameStates.find(state=>state.value===session.gameState)?.label??session.gameState}</span><span>投入 ¥{session.investmentYen.toLocaleString()}</span><span>持枚 {session.medals}</span><span>CZ {session.czCount} · AT {session.atCount}</span></div><div className="mock-reply">AI 功能將於下一階段接入。</div><div className="suggestions"><button>這個畫面是什麼？</button><button>現在在玩什麼？</button><button>這台怎麼玩？</button></div><div className="ai-input"><input placeholder="輸入想問的問題…"/><button>送出</button></div></aside></div>}
    {toast&&<div className="toast">{toast}</div>}
  </>;
}
