import { estimateSettings, getEstimatorReadiness } from "@/lib/settingEstimator";
import type { Machine, Session } from "@/types";
const pct=(value:number)=>`${(value*100).toFixed(1)}%`;
const confidenceLabel={low:"判斷力低",medium:"判斷力中",high:"判斷力高"} as const;
export function SettingEstimator({machine,session}:{machine:Machine;session:Session}){
  const result=estimateSettings(machine,session),readiness=getEstimatorReadiness(machine,session),guide=Boolean(machine.guideStatus),real=(guide||machine.profileStatus==="verified")&&machine.profile.benchmarks.some(item=>item.verified&&!item.testData);
  const sourceCopy=guide?"使用 P-WORLD 公開數值與本 Session 可觀測紀錄。":real?"使用已發布 Profile 中具來源且可觀測的資料。":"目前使用 TEST DATA，只供計算流程驗收。",safetyCopy=guide?"結果是參考推測，不代表準確設定或獲利保證。":real?"相對分布依已驗證來源與本 Session 實測計算。":"TEST DATA 不代表真實機種機率。";
  return <section className="section setting-estimator"><div className="setting-head"><div><span>SETTING ESTIMATOR</span><h2>設定參考</h2></div><b>僅供參考</b></div><div className="confidence-row"><div><small>目前判斷力</small><strong>{confidenceLabel[result.confidence]}</strong></div><span>{Math.round(result.confidenceScore*100)}%</span></div>
    {result.status==="not_started"?<div className="estimator-empty"><strong>{readiness.title}</strong><p>{readiness.summary}</p>{readiness.items.length>0&&<div className="estimator-readiness">{readiness.items.slice(0,3).map(item=><article key={item.id}><div><b>{item.label}</b><small>{item.sample}</small></div><span>{item.next}</span></article>)}</div>}</div>:<><div className="setting-bars">{([1,2,3,4,5,6] as const).map(setting=><div key={setting}><label><span>設定 {setting}</span><b>{pct(result.distribution[setting])}</b></label><i><em style={{width:pct(result.distribution[setting])}} /></i></div>)}</div><div className="setting-groups"><div><span>低設定側</span><b>{pct(result.groups.low)}</b><small>設定 1–2</small></div><div><span>中間</span><b>{pct(result.groups.mid)}</b><small>設定 3–4</small></div><div><span>高設定側</span><b>{pct(result.groups.high)}</b><small>設定 5–6</small></div></div></>}
    {result.evidence.length>0&&<details className="estimator-details"><summary>查看判斷依據（{result.evidence.length}）</summary><div className="evidence-list">{result.evidence.map(item=><article key={item.id}><div><strong>{item.label}</strong><small>{item.observation}</small></div><aside><b>{item.impact.toFixed(1)}%</b><small>{item.direction}</small></aside></article>)}</div></details>}
    <details className="estimator-details"><summary>資料與計算說明</summary><div><p>{sourceCopy}</p><p>{safetyCopy}</p></div></details></section>;
}
