"use client";
import Link from "next/link";
import Image from "next/image";
import { useEffect,useMemo,useRef,useState } from "react";
import type { MachineCatalogRecord } from "@/types/catalog";
import type { SlotSelectionGuideContext,SlotSelectionMode } from "@/lib/ai/slotSelection";
import { guideContextFromMachineGuide,japanSelectionMode } from "@/lib/ai/slotSelection";
import { loadCachedGuideAsync } from "@/lib/machine-guide/storage";
import { compressSelectionImage,type CompressedImage } from "@/lib/ai/imageCompression";
import { formatImageBytes } from "@/lib/ai/imageLimits";
import { formatCompanionAnswer } from "@/lib/ai/companionFormat";

type CandidateDraft={record:MachineCatalogRecord;currentGame:string;note:string;image?:CompressedImage;previewUrl?:string};
const modeCopy:Record<SlotSelectionMode,{label:string;title:string;description:string}>={morning:{label:"🌅 朝一模式",title:"先看這台值不值得確認",description:"一次看 1 台，只在指南有來源時談 Reset／天井。"},evening:{label:"🌙 晚間撿台",title:"把候選排出優先順序",description:"最多比較 5 台，搭配履歷照片、目前 G 與離店條件。"}};
function normalize(value:string){return value.toLocaleLowerCase().replace(/[\s・･\-‐－_]/g,"")}
function imageError(value:unknown){const code=value instanceof Error?value.message:"";if(code==="heic_decode_failed")return"此裝置無法讀取這張 HEIC，請改用 JPEG 或截圖。";if(code==="compressed_too_large")return"壓縮後圖片仍過大，請重新拍攝。";return"照片無法處理，請重新選擇。"}
function Answer({text}:{text:string}){return <div className="selection-answer">{formatCompanionAnswer(text).map((block,index)=><div className={`ai-answer-${block.kind}`} key={index}>{block.kind==="bullet"&&<span aria-hidden="true">•</span>}<p>{block.segments.map((segment,segmentIndex)=>segment.bold?<strong key={segmentIndex}>{segment.text}</strong>:<span key={segmentIndex}>{segment.text}</span>)}</p></div>)}</div>}

export function SlotSelectionAssistant({records}:{records:MachineCatalogRecord[]}){
  const[mode,setMode]=useState<SlotSelectionMode>("morning"),[autoMode,setAutoMode]=useState(true),[japanTime,setJapanTime]=useState(""),[query,setQuery]=useState(""),[candidates,setCandidates]=useState<CandidateDraft[]>([]),[guides,setGuides]=useState<Record<string,SlotSelectionGuideContext|null|undefined>>({}),[question,setQuestion]=useState(""),[answer,setAnswer]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[photoBusy,setPhotoBusy]=useState<number|null>(null);
  const previews=useRef(new Set<string>());
  useEffect(()=>{const now=new Date(),next=japanSelectionMode(now),urls=previews.current;setMode(next);setJapanTime(new Intl.DateTimeFormat("zh-TW",{timeZone:"Asia/Tokyo",hour:"2-digit",minute:"2-digit",hour12:false}).format(now));return()=>{for(const url of urls)URL.revokeObjectURL(url)}},[]);
  const results=useMemo(()=>{const term=normalize(query);if(!term)return[];return records.filter(record=>!candidates.some(candidate=>candidate.record.id===record.id)&&normalize([record.displayNameZh,record.officialNameJa,record.manufacturer,...record.aliases].join(" ")).includes(term)).slice(0,8)},[records,candidates,query]);
  async function ensureGuide(record:MachineCatalogRecord){if(record.id in guides)return;setGuides(current=>({...current,[record.id]:undefined}));const cached=await loadCachedGuideAsync(record.id);setGuides(current=>({...current,[record.id]:cached?guideContextFromMachineGuide(cached.guide):null}))}
  function add(record:MachineCatalogRecord){setAnswer("");setError("");setQuery("");setCandidates(current=>mode==="morning"?[{record,currentGame:"",note:""}]:current.length>=5?current:[...current,{record,currentGame:"",note:""}]);void ensureGuide(record)}
  function switchMode(next:SlotSelectionMode){setMode(next);setAutoMode(false);setAnswer("");setError("");if(next==="morning")setCandidates(current=>current.slice(0,1))}
  function update(index:number,patch:Partial<CandidateDraft>){setCandidates(current=>current.map((item,itemIndex)=>itemIndex===index?{...item,...patch}:item))}
  function remove(index:number){setCandidates(current=>{const target=current[index];if(target?.previewUrl){URL.revokeObjectURL(target.previewUrl);previews.current.delete(target.previewUrl)}return current.filter((_,itemIndex)=>itemIndex!==index)})}
  async function pickPhoto(index:number,file?:File){if(!file)return;setPhotoBusy(index);setError("");try{const compressed=await compressSelectionImage(file),previewUrl=URL.createObjectURL(compressed.file);previews.current.add(previewUrl);setCandidates(current=>current.map((item,itemIndex)=>{if(itemIndex!==index)return item;if(item.previewUrl){URL.revokeObjectURL(item.previewUrl);previews.current.delete(item.previewUrl)}return{...item,image:compressed,previewUrl}}))}catch(value){setError(imageError(value))}finally{setPhotoBusy(null)}}
  async function submit(){if(candidates.length===0||busy)return;setBusy(true);setError("");setAnswer("");try{const form=new FormData();form.set("mode",mode);form.set("question",question);form.set("candidates",JSON.stringify(candidates.map(candidate=>({catalogId:candidate.record.id,currentGame:candidate.currentGame?Number(candidate.currentGame):null,note:candidate.note}))));form.set("guides",JSON.stringify(candidates.flatMap(candidate=>guides[candidate.record.id]?[guides[candidate.record.id]]:[])));candidates.forEach((candidate,index)=>{if(candidate.image)form.set(`image-${index}`,candidate.image.file)});const response=await fetch("/api/ai/slot-selection",{method:"POST",body:form}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"AI 暫時無法分析");setAnswer(payload.answer)}catch(value){setError(value instanceof Error?value.message:"AI 暫時無法分析")}finally{setBusy(false)}}
  const max=mode==="morning"?1:5;
  return <main className="page slot-selection-page">
    <section className="selection-hero card"><span>SLOT AI SELECTOR</span><h2>{modeCopy[mode].title}</h2><p>{modeCopy[mode].description}</p>{japanTime&&<small>日本時間 {japanTime} {autoMode?`· 已自動切換為${mode==="morning"?"朝一":"晚間"}模式`:"· 已手動選擇模式"}</small>}</section>
    <nav className="selection-mode-tabs" aria-label="SLOT 選台模式">{(["morning","evening"] as SlotSelectionMode[]).map(item=><button key={item} className={mode===item?"active":""} aria-pressed={mode===item} onClick={()=>switchMode(item)}>{modeCopy[item].label}</button>)}</nav>
    <section className="selection-search card"><label htmlFor="slot-selection-search">加入候選機台</label><div><input id="slot-selection-search" className="input" value={query} onChange={event=>setQuery(event.target.value)} placeholder="輸入機種名稱或メーカー"/><span>{candidates.length} / {max}</span></div>{query&&<div className="selection-search-results">{results.length?results.map(record=><button key={record.id} disabled={candidates.length>=max} onClick={()=>add(record)}><strong>{record.displayNameZh||record.officialNameJa}</strong><small>{record.officialNameJa} · {record.manufacturer}</small></button>):<p>找不到符合的 SLOT 機種。</p>}</div>}</section>
    <div className="selection-candidates">{candidates.map((candidate,index)=>{const guide=guides[candidate.record.id];return <article className="selection-candidate card" key={candidate.record.id}><header><div><span>候選 {index+1}</span><h3>{candidate.record.displayNameZh||candidate.record.officialNameJa}</h3><small>{candidate.record.manufacturer} · {candidate.record.machineType}</small></div><button aria-label={`移除 ${candidate.record.officialNameJa}`} onClick={()=>remove(index)}>×</button></header><div className={`selection-guide-state ${guide===undefined?"loading":guide?"ready":"missing"}`}><strong>{guide===undefined?"正在找這台裝置的指南…":guide?"✓ 已帶入本機指南":"尚未建立本機指南"}</strong>{guide?<small>{guide.sourceName} · {guide.facts.length} 個可用段落</small>:guide===null?<Link href={`/catalog/${encodeURIComponent(candidate.record.id)}`}>先建立指南 →</Link>:null}</div><label>目前資料機／液晶 G（可略過）<input className="input" inputMode="numeric" value={candidate.currentGame} onChange={event=>update(index,{currentGame:event.target.value.replace(/\D/g,"").slice(0,5)})} placeholder="例如 420"/></label><label>履歷與現場條件（可略過）<textarea value={candidate.note} maxLength={600} onChange={event=>update(index,{note:event.target.value})} placeholder={mode==="morning"?"例如：前日最終 G、開店狀況、想確認的 Reset 畫面":"例如：最後當選、連續單發、剩餘預算、預計離店時間"}/></label><div className="selection-photo"><label className="secondary-button">{photoBusy===index?"壓縮照片中…":candidate.image?"更換履歷照片":"＋ 加入履歷照片"}<input hidden type="file" accept="image/*,.heic,.heif" disabled={photoBusy!==null} onChange={event=>void pickPhoto(index,event.target.files?.[0])}/></label>{candidate.image&&candidate.previewUrl&&<div><Image unoptimized src={candidate.previewUrl} width={candidate.image.width} height={candidate.image.height} alt={`${candidate.record.officialNameJa} 履歷照片`}/><small>{formatImageBytes(candidate.image.compressedBytes)} · 暫時使用，不保存</small><button onClick={()=>{if(candidate.previewUrl){URL.revokeObjectURL(candidate.previewUrl);previews.current.delete(candidate.previewUrl)}update(index,{image:undefined,previewUrl:undefined})}}>移除照片</button></div>}</div></article>})}</div>
    {candidates.length===0&&<div className="selection-empty"><span>{mode==="morning"?"🌅":"🌙"}</span><strong>{mode==="morning"?"先選一台今天想看的機種":"先加入現場看到的候選"}</strong><p>AI 不會只看作品名猜 Reset 或天井；有指南、履歷與 G 數時才有較完整的依據。</p></div>}
    <section className="selection-request card"><label>其他條件（可略過）<textarea maxLength={500} value={question} onChange={event=>setQuestion(event.target.value)} placeholder={mode==="morning"?"例如：今天 9:00 開店，只想玩到中午":"例如：剩餘預算 ¥10,000，最晚 22:30 離店"}/></label><button className="primary-button" disabled={busy||candidates.length===0||photoBusy!==null} onClick={()=>void submit()}>{busy?"正在整理候選…":mode==="morning"?"分析這台朝一條件":"比較這些候選"}</button><p>只使用本次資料；不建立 Session、不保存照片，也不保證獲利。</p></section>
    {error&&<div className="notice selection-error">{error}</div>}{answer&&<section className="card selection-result"><span>AI 選台建議</span><Answer text={answer}/><small>請以現場資料與自己的預算為準；缺少來源的條件不會被補猜。</small></section>}
  </main>
}
