"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import type { MachineCatalogRecord } from "@/types/catalog";
import type { CatalogImporterPresentation } from "@/lib/catalog/importerPresentation";
import { catalogLibraryOptions,catalogSummary,defaultCatalogLibraryFilters,profileForCatalog,queryCatalogLibrary,type CatalogLibraryFilters,type CatalogProfileLink } from "@/lib/catalog/library";
import { getGuideCacheState } from "@/lib/machine-guide/storage";
import { loadSessions } from "@/lib/storage";
import { loadPlayerLibrary,recentPlayedCatalogIds,setCatalogFavorite } from "@/lib/playerLibrary";

type LibraryMode="browse"|"favorites"|"recent";
const modeLabels:{value:LibraryMode;label:string}[]=[{value:"browse",label:"全部機種"},{value:"favorites",label:"我的收藏"},{value:"recent",label:"最近遊玩"}];
function visualNumber(id:string){return[...id].reduce((sum,char)=>sum+char.charCodeAt(0),0)%6}
function shortType(record:MachineCatalogRecord){if(/スマスロ|L/.test(record.machineType)||/^L/.test(record.officialNameJa))return"SMART SLOT";return"PACHISLOT"}

export function CatalogLibraryClient({records,profiles,importer}:{records:MachineCatalogRecord[];profiles:CatalogProfileLink[];importer:CatalogImporterPresentation}){
  const[filters,setFilters]=useState<CatalogLibraryFilters>({...defaultCatalogLibraryFilters,pageSize:24}),[mode,setMode]=useState<LibraryMode>("browse"),[favorites,setFavorites]=useState<string[]>([]),[recentIds,setRecentIds]=useState<string[]>([]),[guideStates,setGuideStates]=useState<Record<string,"current"|"stale"|"missing">>({}),[managementOpen,setManagementOpen]=useState(false);
  const summary=useMemo(()=>catalogSummary(records,profiles),[records,profiles]),options=useMemo(()=>catalogLibraryOptions(records),[records]);
  useEffect(()=>{const player=loadPlayerLibrary(),played=recentPlayedCatalogIds(loadSessions()),viewed=player.recentViews.map(item=>item.catalogId);setFavorites(player.favoriteCatalogIds);setRecentIds([...new Set([...played,...viewed])]);setGuideStates(Object.fromEntries(records.map(record=>[record.id,getGuideCacheState(record.id)])))},[records]);
  const visibleRecords=useMemo(()=>mode==="favorites"?records.filter(record=>favorites.includes(record.id)):mode==="recent"?records.filter(record=>recentIds.includes(record.id)):records,[records,mode,favorites,recentIds]);
  const result=useMemo(()=>queryCatalogLibrary(visibleRecords,profiles,filters),[visibleRecords,profiles,filters]);
  const displayItems=useMemo(()=>mode==="recent"?[...result.items].sort((a,b)=>recentIds.indexOf(a.id)-recentIds.indexOf(b.id)):result.items,[mode,result.items,recentIds]);
  const years=useMemo(()=>[...new Set(options.introducedMonths.map(value=>value.slice(0,4)))].sort().reverse(),[options.introducedMonths]),cachedCount=Object.values(guideStates).filter(value=>value==="current").length;
  function update(patch:Partial<CatalogLibraryFilters>){setFilters(current=>({...current,...patch,page:patch.page??1}))}
  function clear(){setFilters({...defaultCatalogLibraryFilters,pageSize:24})}
  function chooseMode(next:LibraryMode){setMode(next);setFilters(current=>({...current,page:1}))}
  function toggleFavorite(id:string){const next=setCatalogFavorite(id,!favorites.includes(id));setFavorites(next.favoriteCatalogIds)}
  if(records.length===0)return<main className="page catalog-library"><div className="empty card"><strong>目前尚未建立 Machine Catalog</strong><p>可稍後再回來查看已收錄的機種。</p></div></main>;
  return<main className="page catalog-library">
    <section className="catalog-management card"><div><span>MACHINE LIBRARY</span><strong>{summary.total} 台機種，隨時可查</strong><small>收藏常玩的機台，從指南直接開始記錄。</small></div>{importer.available?<Link className="secondary-button" href={importer.href}>{importer.label}</Link>:<div className="catalog-management-disabled"><button className="secondary-button" onClick={()=>setManagementOpen(true)}>{importer.label}</button><small>查看更新方式</small></div>}</section>
    <section className="catalog-player-overview"><div><b>{favorites.length}</b><span>已收藏</span></div><div><b>{recentIds.length}</b><span>最近看過／玩過</span></div><div><b>{cachedCount}</b><span>本機已有指南</span></div></section>
    <nav className="catalog-view-tabs" aria-label="機種資料庫顯示方式">{modeLabels.map(item=><button key={item.value} className={mode===item.value?"active":""} onClick={()=>chooseMode(item.value)}>{item.label}{item.value==="favorites"&&favorites.length>0?<small>{favorites.length}</small>:null}</button>)}</nav>
    <section className="catalog-search-panel"><div className="catalog-search-row"><input className="input" aria-label="搜尋機種" placeholder="搜尋機種、中文名或メーカー" value={filters.query} onChange={event=>update({query:event.target.value})}/><Link href="/glossary" className="catalog-glossary-link" aria-label="新手術語">術語</Link></div><div className="catalog-year-chips"><button className={!filters.introducedMonth?"active":""} onClick={()=>update({introducedMonth:""})}>全部</button>{years.slice(0,5).map(year=><button key={year} className={filters.introducedMonth===year?"active":""} onClick={()=>update({introducedMonth:year})}>{year}</button>)}</div><details className="catalog-advanced"><summary>更多篩選與排序</summary><div className="catalog-filter-grid"><select className="select" aria-label="メーカー" value={filters.manufacturer} onChange={event=>update({manufacturer:event.target.value})}><option value="">所有メーカー</option>{options.manufacturers.map(value=><option key={value}>{value}</option>)}</select><select className="select" aria-label="機種類型" value={filters.machineType} onChange={event=>update({machineType:event.target.value})}><option value="">所有類型</option>{options.machineTypes.map(value=><option key={value}>{value}</option>)}</select><select className="select" aria-label="導入年月" value={filters.introducedMonth} onChange={event=>update({introducedMonth:event.target.value})}><option value="">所有導入年月</option>{options.introducedMonths.map(value=><option key={value}>{value}</option>)}</select><select className="select" aria-label="排序" value={filters.sort} onChange={event=>update({sort:event.target.value as CatalogLibraryFilters["sort"]})}><option value="date-desc">新機優先</option><option value="date-asc">舊機優先</option><option value="name">名稱順序</option><option value="manufacturer">メーカー</option></select></div></details></section>
    <div className="section-title catalog-result-title"><h2>{mode==="favorites"?"我的收藏":mode==="recent"?"最近遊玩":"收錄機種"}</h2><span>{result.total} 台</span></div>
    {result.total===0?<div className="catalog-empty card"><strong>{mode==="favorites"?"還沒有收藏機台":mode==="recent"?"還沒有最近遊玩紀錄":"找不到符合條件的機種"}</strong><p>{mode==="favorites"?"點卡片右上角的星號，就能把常玩機台放在這裡。":mode==="recent"?"建立 Session 後，玩過的機台會自動出現在這裡。":"換個關鍵字或清除篩選再試一次。"}</p><button className="secondary-button" onClick={mode==="browse"?clear:()=>chooseMode("browse")}>{mode==="browse"?"清除篩選":"查看全部機種"}</button><Link className="primary-button" href="/identify">📷 拍機台辨識</Link></div>:<><div className="catalog-card-grid">{displayItems.map(record=>{const profile=profileForCatalog(record.id,profiles),guideState=guideStates[record.id]??"missing",favorite=favorites.includes(record.id);return<article className={`catalog-visual-card tone-${visualNumber(record.id)}`} key={record.id}><button className={`catalog-card-favorite ${favorite?"active":""}`} aria-label={favorite?`取消收藏 ${record.officialNameJa}`:`收藏 ${record.officialNameJa}`} aria-pressed={favorite} onClick={()=>toggleFavorite(record.id)}>{favorite?"★":"☆"}</button><Link href={`/catalog/${record.id}`}><div className="catalog-card-art"><span>{shortType(record)}</span><b>🎰</b><small>{record.introducedAt?.slice(0,7).replace("-"," / ")??"DATE TBD"}</small></div><div className="catalog-card-body"><h2>{record.displayNameZh||record.officialNameJa}</h2>{record.displayNameZh&&<p>{record.officialNameJa}</p>}<span>{record.manufacturer}</span><div className="catalog-card-status">{guideState==="current"?"✓ 已有指南":guideState==="stale"?"↻ 指南需更新":profile?"✓ 相容資料":"＋ 可建立指南"}</div></div></Link></article>})}</div><nav className="catalog-pagination" aria-label="Catalog 分頁"><button disabled={result.page<=1} onClick={()=>update({page:result.page-1})}>← 上一頁</button><span>{result.page} / {result.totalPages}</span><button disabled={result.page>=result.totalPages} onClick={()=>update({page:result.page+1})}>下一頁 →</button></nav></>}
    {!importer.available&&managementOpen&&<div className="modal-backdrop" onClick={()=>setManagementOpen(false)}><section className="modal catalog-update-help" role="dialog" aria-modal="true" aria-labelledby="catalog-update-title" onClick={event=>event.stopPropagation()}><p className="eyebrow">CATALOG UPDATE</p><h2 id="catalog-update-title">更新機種資料庫</h2><p>線上版目前不能永久寫入專案 Catalog，因此不會直接執行匯入。</p><ol><li>在本機開發環境開啟 Catalog Importer。</li><li>掃描 P-WORLD 月份並確認 Preview。</li><li>Approve 後將 Catalog 更新提交至 dev。</li><li>Vercel 重新部署後，所有裝置即可使用新機種。</li></ol><div className="notice">{importer.notice}。這項限制不影響搜尋現有 {summary.total} 台機種。</div><button className="primary-button mt-4" onClick={()=>setManagementOpen(false)}>知道了</button></section></div>}
  </main>
}
