"use client";

import Link from "next/link";
import { useMemo,useState } from "react";
import type { MachineCatalogRecord } from "@/types/catalog";
import type { CatalogImporterPresentation } from "@/lib/catalog/importerPresentation";
import { catalogLibraryOptions,catalogSummary,defaultCatalogLibraryFilters,profileForCatalog,queryCatalogLibrary,type CatalogLibraryFilters,type CatalogProfileLink } from "@/lib/catalog/library";

export function CatalogLibraryClient({records,profiles,importer}:{records:MachineCatalogRecord[];profiles:CatalogProfileLink[];importer:CatalogImporterPresentation}){
  const[filters,setFilters]=useState(defaultCatalogLibraryFilters),[managementOpen,setManagementOpen]=useState(false),summary=useMemo(()=>catalogSummary(records,profiles),[records,profiles]),options=useMemo(()=>catalogLibraryOptions(records),[records]),result=useMemo(()=>queryCatalogLibrary(records,profiles,filters),[records,profiles,filters]);
  function update(patch:Partial<CatalogLibraryFilters>){setFilters(current=>({...current,...patch,page:patch.page??1}))}
  function clear(){setFilters(defaultCatalogLibraryFilters)}
  if(records.length===0)return<main className="page catalog-library"><div className="empty card"><strong>目前尚未建立 Machine Catalog</strong><p>可稍後再回來查看已收錄的機種。</p></div></main>;
  return<main className="page catalog-library">
    <section className="catalog-management card"><div><span>MACHINE CATALOG</span><strong>目前收錄 {summary.total} 台</strong><small>搜尋機種，或更新 P-WORLD 機種清單。</small></div>{importer.available?<Link className="secondary-button" href={importer.href}>{importer.label}</Link>:<div className="catalog-management-disabled"><button className="secondary-button" onClick={()=>setManagementOpen(true)}>{importer.label}</button><small>查看更新方式</small></div>}</section>
    <section className="catalog-overview"><div><b>{summary.total}</b><span>Catalog 總數</span></div><div><b>{summary.profileReady}</b><span>相容 Profile</span></div><div><b>{summary.catalogOnly}</b><span>指南流程</span></div><div><b>{summary.imported}</b><span>Imported</span></div><div><b>{summary.reviewed}</b><span>Reviewed</span></div><div><b>{summary.verified}</b><span>Verified</span></div></section>
    <section className="catalog-controls card"><input className="input" aria-label="搜尋機種" placeholder="搜尋機種名稱、日文名稱、Alias、メーカー" value={filters.query} onChange={event=>update({query:event.target.value})}/><div className="catalog-filter-grid"><select className="select" aria-label="メーカー" value={filters.manufacturer} onChange={event=>update({manufacturer:event.target.value})}><option value="">所有メーカー</option>{options.manufacturers.map(value=><option key={value}>{value}</option>)}</select><select className="select" aria-label="機種類型" value={filters.machineType} onChange={event=>update({machineType:event.target.value})}><option value="">所有類型</option>{options.machineTypes.map(value=><option key={value}>{value}</option>)}</select><select className="select" aria-label="Catalog 狀態" value={filters.catalogStatus} onChange={event=>update({catalogStatus:event.target.value})}><option value="">所有 Catalog 狀態</option>{options.catalogStatuses.map(value=><option key={value}>{value}</option>)}</select><select className="select" aria-label="Profile 狀態" value={filters.profileStatus} onChange={event=>update({profileStatus:event.target.value as CatalogLibraryFilters["profileStatus"]})}><option value="all">全部相容狀態</option><option value="ready">既有 Profile</option><option value="catalog-only">Catalog only</option></select><select className="select" aria-label="導入年月" value={filters.introducedMonth} onChange={event=>update({introducedMonth:event.target.value})}><option value="">所有導入年月</option>{options.introducedMonths.map(value=><option key={value}>{value}</option>)}</select><select className="select" aria-label="排序" value={filters.sort} onChange={event=>update({sort:event.target.value as CatalogLibraryFilters["sort"]})}><option value="date-desc">導入日 新 → 舊</option><option value="date-asc">導入日 舊 → 新</option><option value="name">名稱 A → Z</option><option value="manufacturer">メーカー</option></select></div></section>
    <div className="section-title catalog-result-title"><h2>收錄機種</h2><span>{result.total} 台</span></div>
    {result.total===0?<div className="catalog-empty card"><strong>找不到符合條件的機種</strong><button className="secondary-button" onClick={clear}>清除篩選</button><Link className="primary-button" href="/identify">📷 拍機台辨識</Link></div>:<><div className="catalog-list">{result.items.map(record=>{const profile=profileForCatalog(record.id,profiles);return<Link href={`/catalog/${record.id}`} className="catalog-item card" key={record.id}><div className="catalog-item-head"><span className="badge">{record.catalogStatus}</span><small>{record.machineType}</small></div><h2>{record.officialNameJa}</h2>{record.displayNameZh&&<p>{record.displayNameZh}</p>}<dl><div><dt>メーカー</dt><dd>{record.manufacturer}</dd></div><div><dt>導入日</dt><dd>{record.introducedAt??"未設定"}</dd></div></dl>{profile?<div className="profile-ready">✅ 已有相容機台資料</div>:<div className="catalog-only">📚 可建立機台指南<small>從 P-WORLD 整理公開資料</small></div>}</Link>})}</div><nav className="catalog-pagination" aria-label="Catalog 分頁"><button disabled={result.page<=1} onClick={()=>update({page:result.page-1})}>← 上一頁</button><span>{result.page} / {result.totalPages}</span><button disabled={result.page>=result.totalPages} onClick={()=>update({page:result.page+1})}>下一頁 →</button></nav></>}
    {!importer.available&&managementOpen&&<div className="modal-backdrop" onClick={()=>setManagementOpen(false)}><section className="modal catalog-update-help" role="dialog" aria-modal="true" aria-labelledby="catalog-update-title" onClick={event=>event.stopPropagation()}><p className="eyebrow">CATALOG UPDATE</p><h2 id="catalog-update-title">更新機種資料庫</h2><p>線上版目前不能永久寫入專案 Catalog，因此不會直接執行匯入。</p><ol><li>在本機開發環境開啟 Catalog Importer。</li><li>掃描 P-WORLD 月份並確認 Preview。</li><li>Approve 後將 Catalog 更新提交至 dev。</li><li>Vercel 重新部署後，所有裝置即可使用新機種。</li></ol><div className="notice">{importer.notice}。這項限制不影響搜尋現有 {summary.total} 台機種。</div><button className="primary-button mt-4" onClick={()=>setManagementOpen(false)}>知道了</button></section></div>}
  </main>
}
