import { machines } from "../../data/machines.ts";
import type { MachineIdentificationCandidate,MachineIdentificationResult } from "../../types/index.ts";
import type { MachineCatalogRecord } from "../../types/catalog.ts";
import { normalizeCatalogName } from "../catalog/core.ts";

export type MachineCatalogEntry=Pick<MachineCatalogRecord,"id"|"officialNameJa"|"displayNameZh"|"manufacturer"|"brand"|"seriesName"|"aliases"|"machineType"|"introducedAt">&{searchScore?:number;searchMatchReasons?:string[]};
export const machineCatalog:MachineCatalogEntry[]=machines.map(item=>({id:item.catalogId??item.id,officialNameJa:item.nameJa,displayNameZh:item.nameZh,manufacturer:item.manufacturer||"不明",brand:"",seriesName:item.seriesName??"",aliases:item.aliases??[],machineType:item.category,introducedAt:null}));
export const normalizeMachineName=normalizeCatalogName;
function exactCatalogMatch(candidate:MachineIdentificationCandidate,catalog:MachineCatalogEntry[]){const names=[candidate.machineNameJa,candidate.machineNameZh].filter(Boolean).map(normalizeCatalogName);return catalog.find(item=>[item.officialNameJa,...item.aliases,item.displayNameZh].map(normalizeCatalogName).some(name=>names.includes(name)))}
function profileIdForCatalog(id:string){return machines.find(item=>(item.catalogId??item.id)===id)?.id}
export function catalogProfileStatus(candidate:Pick<MachineIdentificationCandidate,"matchedCatalogId"|"matchedMachineId">){if(!candidate.matchedCatalogId)return null;return candidate.matchedMachineId?"已匹配 Machine Catalog｜已建立攻略 Profile":"已匹配 Machine Catalog｜尚未建立攻略 Profile"}
export function matchMachineProfiles(result:MachineIdentificationResult,catalog:MachineCatalogEntry[]=machineCatalog):MachineIdentificationResult{let forcedUncertain=false;const candidates=result.candidates.slice(0,3).map(candidate=>{const explicit=candidate.matchedCatalogId?catalog.find(item=>item.id===candidate.matchedCatalogId):undefined;const exact=exactCatalogMatch(candidate,catalog);const matched=candidate.identityBasis==="catalog_match"?(explicit??exact):candidate.identityBasis==="official_title_visible"?exact:undefined;let identityBasis=candidate.identityBasis;if(identityBasis==="catalog_match"&&!matched){identityBasis="inferred";forcedUncertain=true}if(identityBasis==="visual_text"||identityBasis==="inferred")forcedUncertain=true;const confidence=identityBasis==="multi_visual_evidence"?Math.min(candidate.confidence,.79):candidate.confidence;if(matched){const matchedMachineId=profileIdForCatalog(matched.id);return{...candidate,identityBasis,confidence,machineNameJa:matched.officialNameJa,machineNameZh:matched.displayNameZh,manufacturer:matched.manufacturer||"不明",matchedCatalogId:matched.id,...(matchedMachineId?{matchedMachineId}:{matchedMachineId:undefined})}}return{...candidate,identityBasis,confidence,manufacturer:"不明",matchedCatalogId:null,matchedMachineId:undefined}});let status=result.status;if(status==="identified"&&(forcedUncertain||!candidates.some(item=>["catalog_match","official_title_visible","multi_visual_evidence"].includes(item.identityBasis))))status="uncertain";if(candidates.length===0||candidates.every(item=>item.identityBasis==="unknown"))status="unknown";return{...result,status,candidates}}
