import type { MachineCatalogRecord } from "@/types/catalog";
import { searchCatalogRecordsForLibrary } from "./core.ts";
export type CatalogProfileLink={catalogId:string;machineId:string;nameZh:string};
export type CatalogLibraryFilters={query:string;manufacturer:string;machineType:string;catalogStatus:string;profileStatus:"all"|"ready"|"catalog-only";introducedMonth:string;sort:"date-desc"|"date-asc"|"name"|"manufacturer";page:number;pageSize:number};
export const defaultCatalogLibraryFilters:CatalogLibraryFilters={query:"",manufacturer:"",machineType:"",catalogStatus:"",profileStatus:"all",introducedMonth:"",sort:"date-desc",page:1,pageSize:25};
export function catalogSummary(records:MachineCatalogRecord[],profiles:CatalogProfileLink[]){const profileIds=new Set(profiles.map(item=>item.catalogId)),profileReady=records.filter(item=>profileIds.has(item.id)).length;return{total:records.length,profileReady,catalogOnly:records.length-profileReady,imported:records.filter(item=>item.catalogStatus==="imported").length,reviewed:records.filter(item=>item.catalogStatus==="reviewed").length,verified:records.filter(item=>item.catalogStatus==="verified").length}}
export function profileForCatalog(id:string,profiles:CatalogProfileLink[]){return profiles.find(item=>item.catalogId===id)}
export function catalogLibraryOptions(records:MachineCatalogRecord[]){const values=(select:(record:MachineCatalogRecord)=>string)=>[...new Set(records.map(select).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ja"));return{manufacturers:values(item=>item.manufacturer),machineTypes:values(item=>item.machineType),catalogStatuses:values(item=>item.catalogStatus),introducedMonths:values(item=>item.introducedAt?.slice(0,7)??"").reverse()}}
export function queryCatalogLibrary(records:MachineCatalogRecord[],profiles:CatalogProfileLink[],filters:CatalogLibraryFilters){const profileIds=new Set(profiles.map(item=>item.catalogId)),searchIds=filters.query.trim()?new Set(searchCatalogRecordsForLibrary(records,filters.query).map(item=>item.id)):null;const filtered=records.filter(record=>(!searchIds||searchIds.has(record.id))&&(!filters.manufacturer||record.manufacturer===filters.manufacturer)&&(!filters.machineType||record.machineType===filters.machineType)&&(!filters.catalogStatus||record.catalogStatus===filters.catalogStatus)&&(!filters.introducedMonth||record.introducedAt?.startsWith(filters.introducedMonth))&&(filters.profileStatus==="all"||(filters.profileStatus==="ready"?profileIds.has(record.id):!profileIds.has(record.id))));const sorted=[...filtered].sort((a,b)=>{if(filters.sort==="date-asc")return(a.introducedAt??"9999").localeCompare(b.introducedAt??"9999");if(filters.sort==="name")return a.officialNameJa.localeCompare(b.officialNameJa,"ja");if(filters.sort==="manufacturer")return a.manufacturer.localeCompare(b.manufacturer,"ja")||a.officialNameJa.localeCompare(b.officialNameJa,"ja");return(b.introducedAt??"").localeCompare(a.introducedAt??"")});const totalPages=Math.max(1,Math.ceil(sorted.length/filters.pageSize)),page=Math.min(Math.max(1,filters.page),totalPages),start=(page-1)*filters.pageSize;return{items:sorted.slice(start,start+filters.pageSize),total:sorted.length,page,totalPages}}
