"use client";
import { useState } from "react";
import Link from "next/link";
import type { Machine } from "@/types";
import type { MachineCatalogRecord } from "@/types/catalog";
import type { DraftMetric,ProfileDraft,ProfileSourceEvidence } from "@/types/profileBuilder";
import type { PublishPreview } from "@/types/profilePromotion";

const labels:Record<string,string>={gameFlow:"Game Flow",czInitialRate:"CZ 初當率",atInitialRate:"AT 初當率",smallRoleSettingDifferences:"小役設定差",triggerSuccessRate:"契機成功率",ceiling:"天井",zone:"Zone",reset:"Reset",endScreenIndications:"結束畫面",trophySettingIndications:"獎盃／設定示唆",playGuide:"打ち方"};
const blocking=new Set(["conflict","incomparable","duplicate_source"]);

function EvidenceValue({item}:{item:ProfileSourceEvidence}){return item.tableHeaders?.length?<div className="evidence-table"><table><thead><tr>{item.tableHeaders.map((header,index)=><th key={`${header}-${index}`}>{header}</th>)}</tr></thead><tbody>{item.rows?.map((row,rowIndex)=><tr key={rowIndex}>{row.map((cell,cellIndex)=><td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>:<p>{Array.isArray(item.extractedValue)?item.extractedValue.join("、"):item.extractedValue}</p>}

function ResolutionDialog({metric,evidence,busy,note,setNote,onResolve,onClose}:{metric:DraftMetric;evidence:ProfileSourceEvidence[];busy:boolean;note:string;setNote:(value:string)=>void;onResolve:(type:"source_selected"|"merged"|"rejected",selectedIds:string[],rejectedIds?:string[])=>void;onClose:()=>void}){return <div className="resolution-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="resolution-dialog" role="dialog" aria-modal="true" aria-labelledby="resolution-title"><header><div><small>Evidence Conflict Resolution</small><h2 id="resolution-title">{labels[metric.metricKey]??metric.metricKey}</h2><p>{metric.verificationStatus.toUpperCase()} · {evidence.length} evidence</p></div><button className="dialog-close" onClick={onClose} aria-label="關閉">×</button></header><div className="resolution-evidence-list">{evidence.map(item=><article className="resolution-evidence" key={item.id}><div className="resolution-source"><div><strong>{item.sourceName}</strong><a href={item.sourceUrl} target="_blank" rel="noreferrer">查看來源 ↗</a></div><span>{(item.confidence*100).toFixed(0)}%</span></div><small>{item.rawLabel}</small><EvidenceValue item={item}/>{item.note&&<p className="evidence-note">{item.note}</p>}<div className="resolution-row-actions"><button disabled={busy} onClick={()=>onResolve("source_selected",[item.id])}>採用此來源</button><button className="reject-evidence" disabled={busy} onClick={()=>onResolve("rejected",[],[item.id])}>排除此 Evidence</button></div></article>)}</div><label className="resolution-note"><span>Resolution note</span><textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="記錄人工判斷理由（建議填寫）" rows={3}/></label><div className="resolution-actions"><button className="primary-button" disabled={busy||evidence.length<2} onClick={()=>onResolve("merged",evidence.map(item=>item.id))}>Merge / Combine</button><button className="secondary-button" disabled={busy} onClick={onClose}>保持 unresolved</button></div><p className="builder-help">Merge 僅會在表格結構可安全對齊時完成；原始 Evidence 永遠保留。</p></section></div>}

export function ProfileBuilderClient({catalog,machine,initialDraft}:{catalog:MachineCatalogRecord;machine:Machine|null;initialDraft:ProfileDraft|null}){
  const[draft,setDraft]=useState(initialDraft),[sourceUrl,setSourceUrl]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[reviewMetricKey,setReviewMetricKey]=useState<string|null>(null),[resolutionNote,setResolutionNote]=useState(""),[publishPreview,setPublishPreview]=useState<PublishPreview|null>(null);
  async function act(action:string,payload:Record<string,unknown>={}){setBusy(true);setMessage("");try{const response=await fetch(`/api/admin/profile-builder/${catalog.id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})}),data=await response.json();if(data.preview)setPublishPreview(data.preview);if(!response.ok)throw new Error(data.error??"操作失敗");if(data.draft)setDraft(data.draft);if(action==="resolve-metric")setReviewMetricKey(null);if(action==="publish")setPublishPreview(null);setMessage(action==="approve"?"Draft 已驗證。":action==="publish"?"Machine Profile 已發布。":action==="rollback"?"已 rollback 至前一版 Profile。":action==="publish-preview"?"Publish Preview 已建立。":action==="resolve-metric"?"Metric resolution 已保存。":"已更新 Draft。")}catch(error){setMessage(error instanceof Error?error.message:"操作失敗")}finally{setBusy(false)}}
  const pending=draft?.evidence.filter(item=>item.reviewStatus==="pending")??[],unresolved=draft?.metrics.filter(item=>blocking.has(item.verificationStatus)&&(!item.resolutionStatus||item.resolutionStatus==="unresolved"))??[],reviewMetric=draft?.metrics.find(item=>item.metricKey===reviewMetricKey),reviewEvidence=reviewMetric?draft?.evidence.filter(item=>reviewMetric.evidenceIds.includes(item.id))??[]:[];
  const resolve=(resolutionType:"source_selected"|"merged"|"rejected",selectedEvidenceIds:string[],rejectedEvidenceIds:string[]=[])=>reviewMetric&&act("resolve-metric",{metricKey:reviewMetric.metricKey,resolutionType,selectedEvidenceIds,rejectedEvidenceIds,note:resolutionNote});
  return <main className="page profile-builder">
    <section className="card builder-identity"><span className="badge">{catalog.catalogStatus}</span><h1>{catalog.officialNameJa}</h1><p>{catalog.displayNameZh||"尚未設定中文名"} · {catalog.manufacturer}</p><div className="builder-status"><span>現有 Profile</span><strong>{machine?.profileStatus??"catalog-only"}</strong><span>Draft</span><strong>{draft?.status??"尚未建立"}</strong></div></section>
    {machine?.profileStatus==="placeholder"&&<div className="notice">現有 Profile 是 placeholder；Smart Counter 與 TEST DATA 會繼續運作，直到新 Draft 完成人工核准。</div>}
    {!draft?<button className="primary-button" disabled={busy} onClick={()=>act("create")}>{machine?"重建／升級攻略 Profile":"建立 Profile Draft"}</button>:<>
      <section className="section card"><h2>Source Evidence</h2><p className="builder-help">人工貼上公開來源 URL。只保存結構化 evidence，不保存攻略全文。</p><div className="catalog-fetch"><input className="input" inputMode="url" placeholder="https://..." value={sourceUrl} onChange={event=>setSourceUrl(event.target.value)}/><button disabled={busy||!sourceUrl} onClick={()=>act("extract",{sourceUrl})}>{busy?"處理中":"加入並抽取"}</button></div>{draft.sources.map(source=><article className="builder-source" key={source.id}><div><strong>{source.sourceName}</strong><small>{source.sourceUrl}</small><small>{source.extractedEvidenceCount??draft.evidence.filter(item=>item.sourceUrl===source.sourceUrl).length} evidence</small></div><span className={source.status}>{source.status}</span>{source.error&&<p>{source.error}</p>}</article>)}</section>
      <section className="section card"><div className="builder-section-head"><h2>Draft Profile</h2><span>{draft.metrics.length} metrics</span></div>{draft.metrics.length===0?<p className="builder-empty">尚無可抽取資料；看不到的欄位維持 null，不會補猜。</p>:draft.metrics.map(metric=>{const needsReview=blocking.has(metric.verificationStatus),resolved=needsReview&&metric.resolutionStatus&&metric.resolutionStatus!=="unresolved";return <article className="builder-metric" key={metric.metricKey}><div><strong>{labels[metric.metricKey]??metric.metricKey}</strong><small>{metric.sourceCount??1} sources · {(metric.sourceNames??[]).join("、")||"來源待同步"}</small><small>{Array.isArray(metric.value)?metric.value.join("、"):metric.value}</small>{resolved&&<small className="resolution-summary">RESOLVED · {metric.resolutionType?.toUpperCase()}{metric.resolvedAt?` · ${new Date(metric.resolvedAt).toLocaleString("zh-TW")}`:""}{metric.resolutionNote?` · ${metric.resolutionNote}`:""}</small>}</div><aside className="metric-review"><span className={resolved?"resolved":metric.verificationStatus}>{resolved?`resolved · ${metric.resolutionType}`:metric.verificationStatus}</span>{needsReview&&<button className="mini-button" disabled={busy} onClick={()=>{setReviewMetricKey(metric.metricKey);setResolutionNote(metric.resolutionNote??"")}}>Review / Resolve</button>}</aside></article>})}</section>
      <section className="section card"><div className="builder-section-head"><h2>Evidence Review</h2><span>{pending.length} pending</span></div>{draft.evidence.map(item=><article className="builder-evidence" key={item.id}><div><strong>{item.sectionTitle??labels[item.metricKey]??item.metricKey}</strong><small>{item.sourceName} · {item.extractedFrom??"legacy"} · confidence {(item.confidence*100).toFixed(0)}%</small><EvidenceValue item={item}/>{item.note&&<p className="evidence-note">{item.note}</p>}</div><span className={item.reviewStatus}>{item.reviewStatus}</span></article>)}{draft.evidence.length>0&&<button className="secondary-button" disabled={busy||pending.length===0} onClick={()=>act("review",{approvedIds:pending.map(item=>item.id),rejectedIds:[]})}>人工確認目前 Evidence</button>}</section>
      {unresolved.length>0&&<div className="notice danger">尚有 {unresolved.length} 個未解決資料衝突：{unresolved.map(item=>labels[item.metricKey]??item.metricKey).join("、")}。完成 Resolution 前無法核准 Profile。</div>}
      <section className="section card"><h2>Smart Counter 建議</h2>{draft.smartCounterSuggestions.length===0?<p className="builder-empty">目前沒有建議。系統不會自動核准 Counter。</p>:draft.smartCounterSuggestions.map(item=><article className="builder-metric" key={item.id}><div><strong>{item.definition.labelZh} · {item.definition.type}</strong><small>{item.reason}</small></div><button className="mini-button" disabled={busy||item.approved} onClick={()=>act("review-counter",{reason:item.id})}>{item.approved?"已核准":"Review"}</button></article>)}</section>
      <div className="builder-actions">{draft.status!=="verified"?<button className="primary-button" disabled={busy||pending.length>0||unresolved.length>0||draft.evidence.length===0} onClick={()=>act("approve")}>Verify Draft</button>:<button className="primary-button" disabled={busy} onClick={()=>act("publish-preview")}>Publish Profile</button>}<button className="secondary-button" disabled={busy} onClick={()=>act("reject",{reason:"人工退回修改"})}>Reject / 退回 Draft</button>{draft.status==="verified"&&<button className="secondary-button" disabled={busy} onClick={()=>act("rollback")}>Rollback to Previous Profile</button>}</div>
      {publishPreview&&<section className="section card publish-preview"><div className="builder-section-head"><h2>Publish Preview / Diff</h2><span>v{publishPreview.currentVersion} → v{publishPreview.nextVersion}</span></div><dl><div><dt>Profile status</dt><dd>{publishPreview.currentStatus} → {publishPreview.nextStatus}</dd></div><div><dt>新增 Metrics</dt><dd>{publishPreview.addedMetrics.join("、")||"無"}</dd></div><div><dt>替換 Placeholder</dt><dd>{publishPreview.replacedPlaceholderFields.join("、")}</dd></div><div><dt>停用 TEST benchmarks</dt><dd>{publishPreview.disabledTestBenchmarkIds.join("、")||"無"}</dd></div><div><dt>新增 real benchmarks</dt><dd>{publishPreview.addedBenchmarkDrafts.map(item=>`${item.metricKey} · ${item.kind} · ${item.observation.type==="rate"?item.observation.denominatorMetricKey:item.observation.type}`).join("、")||"無"}</dd></div><div><dt>新增 Counters</dt><dd>{publishPreview.addedCounterKeys.join("、")||"無"}</dd></div><div><dt>移除 Counters</dt><dd>{publishPreview.removedCounterKeys.join("、")||"無"}</dd></div></dl>{publishPreview.blockers.length>0&&<div className="notice danger">{publishPreview.blockers.map(item=><p key={`${item.code}-${item.metricKey??""}`}>{item.message}</p>)}</div>}<button className="primary-button" disabled={busy||!publishPreview.canPublish} onClick={()=>act("publish")}>確認 Publish to Machine Profile</button><button className="secondary-button mt-2" disabled={busy} onClick={()=>setPublishPreview(null)}>取消</button></section>}
    </>}
    {message&&<p className="catalog-message">{message}</p>}<Link className="text-link" href={`/catalog/${catalog.id}`}>← 返回 Catalog Detail</Link>
    {reviewMetric&&<ResolutionDialog metric={reviewMetric} evidence={reviewEvidence} busy={busy} note={resolutionNote} setNote={setResolutionNote} onResolve={resolve} onClose={()=>setReviewMetricKey(null)}/>} 
  </main>
}
