import type { MachineGuide,MachineGuideSectionKey,PlayerGuideZh } from "@/types/machineGuide";

const sectionTitles:Partial<Record<MachineGuideSectionKey,string>>={features:"這台是什麼",play:"基本玩法",flow:"通常時怎麼玩",cz:"CZ 怎麼看",at_art:"AT／ART 怎麼看",bonus:"Bonus 怎麼看",ceiling:"天井與其他參考",setting_rates:"設定差參考",small_roles:"小役參考",special_events:"特殊演出與設定示唆"};
const kindMeaning:Record<string,string>={cz:"CZ：進入出玉狀態前的機會區間",at:"AT：輔助出玉狀態",art:"ART：Replay 輔助型出玉狀態",bonus:"Bonus 獎勵事件",indication:"可能帶有設定示唆的可選畫面",special:"值得另外留意的具名事件"};
function familyOverview(guide:MachineGuide,hasOperationalEvent:boolean){if(!hasOperationalEvent)return"目前可靠玩法資料有限，先使用基本記錄模式記總遊玩 G。";switch(guide.machineType){case"a_type":return"這台以 BIG／REG 等 Bonus 為主要記錄重點。先記總遊玩 G，再記每次 Bonus。";case"bonus_art":return"這台同時有 Bonus 與 ART。看到具名 Bonus、CZ 或 ART 時，使用各自的記錄按鈕。";case"cz_at":case"multi_zone_at":case"cycle_point_at":return"這台主要從通常遊戲進入具名 CZ，再進入 AT。只記錄指南中有明確名稱的事件。";case"set_based_at":return"這台以 AT 為主要出玉狀態；Set 等資料若沒有操作按鈕，只作參考。";case"bonus_loop":return"這台以 Bonus 或連續 Bonus 流程為主；只記錄指南中能明確辨認的事件。";default:return"先記總遊玩 G，並在機台明確顯示具名事件時記錄。"}}
export function buildRuleBasedChineseGuide(guide:MachineGuide):PlayerGuideZh{
  const operational=new Set((guide.controlManifest??[]).filter(item=>item.availability==="operational").map(item=>item.eventId));
  const events=guide.recordableEvents.filter(item=>operational.has(item.id)).slice(0,8);
  const selected=[] as typeof events;for(const group of [["cz"],["at","art"],["bonus"],["indication"],["special"]]){const item=events.find(event=>group.includes(event.category)&&!selected.includes(event));if(item)selected.push(item);if(selected.length===3)break}for(const item of events)if(selected.length<3&&!selected.includes(item))selected.push(item);
  const highlights=selected.map(item=>({id:item.id,label:item.labelZh,meaning:kindMeaning[item.category]??"可由玩家明確辨認的記錄事件",recordWhen:`機台明確顯示「${item.labelJa}」時，按「${item.labelZh}」記錄 1 次。`,sourceSectionKeys:[...new Set(item.controlEvidence.map(evidence=>evidence.sectionKey).filter((key):key is MachineGuideSectionKey=>Boolean(key)))]}));
  const sections=guide.sections.filter(section=>section.tables.length||section.paragraphsJa.length).map(section=>({key:section.key,title:sectionTitles[section.key]??section.titleZh,summary:section.summaryZh&& !/P-WORLD 在|結構化|下方保留/.test(section.summaryZh)?section.summaryZh:"目前可查看來源整理資料；詳細日文與表格收在原始資料。",points:[],sourceSectionKeys:[section.key]}));
  return{generator:"rules",overview:familyOverview(guide,events.length>0),goals:highlights.length?highlights.map(item=>`看到「${item.label}」時記錄`):["先記錄總遊玩 G","需要時新增個人自訂記錄"],highlights,sections,generatedAt:guide.retrievedAt};
}

export function chineseGuideInput(guide:MachineGuide){return{machine:{officialNameJa:guide.officialNameJa,manufacturer:guide.manufacturer,family:guide.machineType},controls:(guide.controlManifest??[]).filter(item=>item.availability==="operational"&&(item.controlType==="counter"||item.controlType==="choice")&&item.eventType!=="game").map(item=>({id:item.eventId??item.id,label:item.label,eventType:item.eventType,playerWhen:item.playerWhen,sourceSections:[...new Set(item.controlEvidence.map(evidence=>evidence.sectionKey).filter(Boolean))]})),sections:guide.sections.filter(section=>section.tables.length||section.paragraphsJa.length).map(section=>({key:section.key,titleJa:section.titleJa,paragraphsJa:section.paragraphsJa.slice(0,2).map(value=>value.slice(0,500)),tables:section.tables.slice(0,3).map(table=>({title:table.title,headers:table.headers,rows:table.rows.slice(0,8)}))}))};}

function numericTokens(value:string){return[...value.matchAll(/\d+(?:[.,]\d+)?/g)].map(match=>match[0].replace(",","."))}
export function validateChineseGuide(candidate:PlayerGuideZh,guide:MachineGuide){const keys=new Set(guide.sections.map(section=>section.key)),input=chineseGuideInput(guide),source=JSON.stringify(input),sourceNumbers=new Set(numericTokens(source)),allowedControls=new Map(input.controls.map(control=>[control.id,control])),playerText=JSON.stringify({overview:candidate.overview,goals:candidate.goals,highlights:candidate.highlights.map(item=>({label:item.label,meaning:item.meaning,recordWhen:item.recordWhen})),sections:candidate.sections.map(section=>({title:section.title,summary:section.summary,points:section.points}))});if(candidate.generator!=="openai"||!candidate.overview.trim()||candidate.highlights.length>3)return false;if(candidate.sections.some(section=>!keys.has(section.key)||section.sourceSectionKeys.some(key=>!keys.has(key)))||candidate.highlights.some(item=>{const control=allowedControls.get(item.id);return!control||item.label!==control.label||item.sourceSectionKeys.some(key=>!keys.has(key))}))return false;return numericTokens(playerText).every(value=>sourceNumbers.has(value));}
