import type { CounterDefinition, SettingBenchmark, SettingValues } from "@/types";
import type { GuideDenominator, GuideEvidenceReference, GuideMachineType, GuideStateType, MachineFamilyClassification, MachineGuide, MachineGuideEvent, MachineGuideMetric, MachineGuideSectionKey, MachineGuideState, ParsedMachineGuideFacts, SessionCapability, DenominatorCapability } from "@/types/machineGuide";
import { sessionModule } from "./modules.ts";
import { buildDenominatorCapabilities, buildSessionCapabilities, validateEstimatorDependency } from "./capabilities.ts";
import { buildControlManifest } from "./controlManifest.ts";
/* eslint-disable @typescript-eslint/no-unused-vars -- compiler materializes the manifest; the P-WORLD adapter attaches it to the guide for backwards-compatible callers. */

const missing=/^(調査中|未公開|不明|—|-)?$/;
const genericNames=new Set(["CZ","AT","ART","BONUS","ボーナス","期待度","当選時","非当選時","本前兆中","突入","濃厚"]);
function slug(value:string){return value.normalize("NFKC").toLowerCase().replace(/[^a-z0-9\p{L}\p{N}]+/gu,"-").replace(/^-|-$/g,"").slice(0,48)||"event"}
function allText(facts:ParsedMachineGuideFacts){return[facts.officialNameJa,...facts.sections.flatMap(s=>[...s.paragraphsJa,...s.tables.flatMap(t=>[t.title,...t.headers,...t.rows.flat()])])].join("\n")}
function legacyClassify(text:string):GuideMachineType{
  if(/Aタイプ|ノーマルタイプ/.test(text)&&!/\b(?:AT|ART)\b/.test(text))return"a_type";
  if(/リアルボーナス|ボーナス.*ART|ART.*ボーナス/.test(text)&&/ART/.test(text))return"bonus_art";
  if(/周期/.test(text)&&/ポイント/.test(text)&&/AT/.test(text))return"cycle_point_at";
  if((/擬似ボーナス/.test(text)&&/(ループ|連チャン)/.test(text))||(/ボーナスストック/.test(text)&&/ボーナス初当り/.test(text)))return"bonus_loop";
  const czNames=[...text.matchAll(/(?:CZ|チャンスゾーン)[「『]?([\p{L}\p{N}ー・]{3,24})[」』]?/gu)].map(m=>m[1]);
  if(new Set(czNames).size>=2&&/AT/.test(text))return"multi_zone_at";
  if((/セット数管理|1セット|セット継続/.test(text)&&/AT/.test(text))||(/ミリオンゴッド/.test(text)&&/AT/.test(text)&&/ループストック/.test(text)))return"set_based_at";
  return"generic";
}
function evidenceRef(input:{id:string;layer:GuideEvidenceReference["layer"];sourceUrl:string;sectionKey?:MachineGuideSectionKey|null;structure:GuideEvidenceReference["structure"];label:string;sufficient:boolean;reason:string}):GuideEvidenceReference{return{sectionKey:null,...input}}
function tableEvidence(facts:ParsedMachineGuideFacts,tableId:string,layer:GuideEvidenceReference["layer"],label:string,sufficient:boolean,reason:string,structure:GuideEvidenceReference["structure"]="table"){const section=facts.sections.find(item=>item.tables.some(table=>table.id===tableId));return evidenceRef({id:`${layer}:${tableId}:${slug(label)}`,layer,sourceUrl:facts.sourceUrl,sectionKey:section?.key??null,structure,label,sufficient,reason})}
function classify(facts:ParsedMachineGuideFacts):MachineFamilyClassification{const text=allText(facts),tables=facts.sections.flatMap(section=>section.tables),structured=tables.map(table=>[table.title,...table.headers].join(" ")).join("\n"),bonusTable=tables.find(table=>/設定/.test(table.headers[0]??"")&&table.headers.some(header=>/^(?:BB|BIG)/i.test(header.trim()))&&table.headers.some(header=>/^(?:RB|REG)/i.test(header.trim())));if(bonusTable&&!/\b(?:AT|ART|CZ)\b/.test(structured)){const label=`設定表「${bonusTable.title}」提供 BB／RB`;return{family:"a_type",confidence:"high",evidence:[label],familyEvidence:[tableEvidence(facts,bonusTable.id,"family",label,true,"結構化設定表可支持 A-type family 分類")],unsupportedReasons:[]}}const family=legacyClassify(text);if(family!=="generic"){const label="來源結構化玩法／表格符合共用 family";return{family,confidence:"medium",evidence:[label],familyEvidence:[evidenceRef({id:`family:${facts.catalogId}:${family}`,layer:"family",sourceUrl:facts.sourceUrl,structure:"derived",label,sufficient:true,reason:"只支持 family 分類，不授權任何 Session control"})],unsupportedReasons:[]}}if(/CZ/.test(structured)&&/AT/.test(structured)){const label="來源結構化表格同時提供 CZ 與 AT";return{family:"cz_at",confidence:"high",evidence:[label],familyEvidence:[evidenceRef({id:`family:${facts.catalogId}:cz-at-table`,layer:"family",sourceUrl:facts.sourceUrl,structure:"table",label,sufficient:true,reason:"機率表只支持 family 分類，不足以建立 CZ／AT control"})],unsupportedReasons:[]}}return{family:"generic",confidence:"low",evidence:[],familyEvidence:[],unsupportedReasons:["來源不足以可靠判定共用 family"]}}
export const classifyMachineFamily=classify;
function state(id:string,ja:string,type:GuideStateType,sourceUrl:string):MachineGuideState{return{id:`state:${id}`,displayNameZh:ja,originalNameJa:ja,type,sourceUrl}}
function event(ja:string,category:MachineGuideEvent["category"],sourceUrl:string,controlEvidence:GuideEvidenceReference[]):MachineGuideEvent{const id=`event:${slug(ja)}`;return{id,labelZh:ja,labelJa:ja,category,whatToSee:`機台顯示「${ja}」時`,countingRule:"每次明確進入或出現時計 1 次。",sessionModuleIds:[],affectsEstimator:false,sourceUrl,controlEvidence,unavailableReason:controlEvidence.some(item=>item.sufficient)?null:"缺少可追溯的事件名稱與記錄時機證據。"}}
function unique<T extends{id:string}>(items:T[]){return[...new Map(items.map(item=>[item.id,item])).values()]}
function observableName(name:string){const value=name.normalize("NFKC").replace(/^[\s「『【（(]+|[\s」』】）)]+$/g,"").trim();if(value.length<2||value.length>40||genericNames.has(value))return null;if(/^(?:の|へ|を|に|で|が|は|と|非当選時|当選時|本前兆中)|(?:の|へ|を|に|で|が|は|と|や|時|中|当選時|非当選時|期待度|濃厚|突入|獲得)$/.test(value))return null;if(/期待度|非当選時|当選時|当選で|本前兆中|セットストック獲得|突入濃厚|獲得濃厚/.test(value))return null;return value}
type NamedState={name:string;category:"cz"|"at"|"art";controlEvidence:GuideEvidenceReference[]};
function structuredStateNames(facts:ParsedMachineGuideFacts){const found:NamedState[]=[];const add=(name:string|null,category:NamedState["category"],reference:GuideEvidenceReference)=>{if(name)found.push({name,category,controlEvidence:[reference]})};for(const section of facts.sections){for(const table of section.tables){const titleMatch=table.title.match(/^(.{2,40}?)\s*\((CZ|AT|ART)\)(?:について|関連|中|$)/i);if(titleMatch)add(observableName(titleMatch[1]),titleMatch[2].toLowerCase() as NamedState["category"],tableEvidence(facts,table.id,"control",titleMatch[1],true,"具名 table heading 明確定義可觀察事件","heading"));const cells=[table.title,...table.headers,...table.rows.flat()];for(const value of cells)extractNamedStateMatches(value,(name,category)=>add(name,category,tableEvidence(facts,table.id,"control",name??category,true,"結構化表格明確標示具名事件"))) }for(const paragraph of section.paragraphsJa)extractNamedStateMatches(paragraph,(name,category)=>add(name,category,evidenceRef({id:`control:${facts.catalogId}:${section.key}:${slug(name??category)}`,layer:"control",sourceUrl:facts.sourceUrl,sectionKey:section.key,structure:"paragraph",label:name??category,sufficient:true,reason:"正文以引號明確標示事件名稱"})))}const merged=new Map<string,NamedState>();for(const item of found){const key=`${item.category}:${item.name}`,existing=merged.get(key);merged.set(key,existing?{...existing,controlEvidence:[...existing.controlEvidence,...item.controlEvidence]}:item)}return[...merged.values()]}
function extractNamedStateMatches(value:string,add:(name:string|null,category:NamedState["category"])=>void){for(const match of value.matchAll(/(?:CZ|AT|ART)\s*[「『]([^」』]{2,40})[」』]/giu)){const category=match[0].slice(0,3).match(/^ART/i)?"art":match[0].match(/^AT/i)?"at":"cz";add(observableName(match[1]),category)}for(const match of value.matchAll(/[「『]([^」』]{2,40})[」』]\s*(CZ|AT|ART)/giu))add(observableName(match[1]),match[2].toLowerCase() as NamedState["category"])}
function structuredBonusEvents(facts:ParsedMachineGuideFacts){const found:MachineGuideEvent[]=[];const add=(label:string,reference:GuideEvidenceReference)=>{const normalized=/^(?:BB|BIG)$/i.test(label)?"BIG BONUS":/^(?:RB|REG)$/i.test(label)?"REG BONUS":label.toUpperCase();found.push(event(normalized,"bonus",facts.sourceUrl,[reference]))};for(const section of facts.sections){for(const paragraph of section.paragraphsJa){if(!/搭載|当選|入賞|獲得|突入/.test(paragraph))continue;for(const match of paragraph.matchAll(/(?:^|[\s、／・])((?:(?:BB|RB|REG|BIG)(?:\s*BONUS)?|EPISODE\s*BONUS)|(?:[\p{Script=Katakana}ー]{2,16})ボーナス)/gimu)){const label=observableName(match[1]);if(label)add(label,evidenceRef({id:`control:${facts.catalogId}:${section.key}:${slug(label)}`,layer:"control",sourceUrl:facts.sourceUrl,sectionKey:section.key,structure:"paragraph",label,sufficient:true,reason:"正文明確記載具名 Bonus 並說明其搭載或發生"}))}}for(const table of section.tables)for(const header of table.headers){const value=header.trim();if(/^(?:BB|BIG(?: BONUS)?|RB|REG(?: BONUS)?)$/i.test(value))add(value,tableEvidence(facts,table.id,"control",value,true,"結構化 table header 明確定義 Bonus 記錄項目","table_header"))}}return unique(found)}
function indicationTables(facts:ParsedMachineGuideFacts){return facts.sections.filter(section=>section.key==="special_events").flatMap(section=>section.tables.map(table=>({section,table}))).filter(({table})=>{const value=[table.title,...table.headers].join(" ");return(/終了画面|設定示唆/.test(value)||/プレート/.test(value)&&/示唆/.test(value))&&table.rows.some(row=>row.filter(Boolean).length>=2)})}
function deriveIdentity(facts:ParsedMachineGuideFacts,type:GuideMachineType){const source=facts.sourceUrl,states=[state("normal","通常", "normal",source)],events:MachineGuideEvent[]=[];
  const structured=structuredStateNames(facts),czItems=structured.filter(item=>item.category==="cz"),atItems=structured.filter(item=>item.category==="at"),artItems=structured.filter(item=>item.category==="art");
  for(const item of czItems)events.push(event(item.name,"cz",source,item.controlEvidence));if(type!=="a_type"&&type!=="bonus_loop"&&type!=="bonus_art")for(const item of atItems)events.push(event(item.name,"at",source,item.controlEvidence));if(type==="bonus_art"||type==="generic")for(const item of artItems)events.push(event(item.name,"art",source,item.controlEvidence));
  events.push(...structuredBonusEvents(facts));
  const namedEvents=unique(events);for(const item of namedEvents){if(item.category==="cz")states.push(state(slug(item.labelJa),item.labelJa,"chance_zone",source));if(item.category==="at")states.push(state(slug(item.labelJa),item.labelJa,"at",source));if(item.category==="art")states.push(state(slug(item.labelJa),item.labelJa,"art",source));if(item.category==="bonus")states.push(state(slug(item.labelJa),item.labelJa,"bonus",source))}
  const tables=indicationTables(facts);if(tables.length)events.push(event("終了畫面／設定示唆","indication",source,tables.map(({table})=>tableEvidence(facts,table.id,"control",table.title,true,"具有效選項列的結構化示唆表"))));
  return{states:unique(states),events:unique(events)};
}
function parsedNumber(value:string){if(missing.test(value.trim()))return null;const ratio=value.replace(/／/g,"/").match(/1\s*\/\s*([\d.]+)/);if(ratio)return{mode:"oneIn" as const,value:Number(ratio[1])};const pct=value.replace(/％/g,"%").match(/([\d.]+)\s*%/);return pct?{mode:"probability" as const,value:Number(pct[1])/100}:null}
function settings(rows:string[][],column:number){const out:Partial<SettingValues>={};let mode:"oneIn"|"probability"|null=null;for(const row of rows){const s=row[0]?.match(/設定\s*([1-6])/);if(!s)continue;const parsed=parsedNumber(row[column]??"");if(!parsed)return null;if(mode&&mode!==parsed.mode)return null;mode=parsed.mode;out[Number(s[1]) as 1|2|3|4|5|6]=parsed.value}return Object.keys(out).length===6&&mode?{values:out as SettingValues,mode}:null}
function denominator(label:string,section:string):GuideDenominator|null{if(/CZ.*成功|当選率/.test(label))return"specific_trials";if(/CZ|AT|ART/.test(label))return"normal_games";if(/^(?:BB|RB)$|BIG|REG|BONUS|ボーナス/.test(label)||section==="small_roles")return"total_games";return null}
function metricKey(label:string){if(/CZ/.test(label))return"cz";if(/ART/.test(label))return"art";if(/AT/.test(label))return"at";if(/^(?:BB|BIG)/i.test(label))return"bigBonus";if(/^(?:RB|REG)/i.test(label))return"regBonus";if(/ボーナス合成|BONUS合成/i.test(label))return"bonusCombined";return`guide-${slug(label)}`}
function metricNumerator(key:string,capabilities:SessionCapability[]){let candidates:SessionCapability[]=[];if(key==="cz")candidates=capabilities.filter(c=>c.moduleKind==="named_cz");else if(key==="at")candidates=capabilities.filter(c=>c.moduleKind==="at");else if(key==="art")candidates=capabilities.filter(c=>c.moduleKind==="art");else if(key==="bigBonus")candidates=capabilities.filter(c=>c.moduleKind==="big_reg_bonus"&&/big/i.test(c.labelJa));else if(key==="regBonus")candidates=capabilities.filter(c=>c.moduleKind==="big_reg_bonus"&&/reg|regular/i.test(c.labelJa));return candidates.length===1?candidates[0].observationKey:null}
function deriveMetrics(facts:ParsedMachineGuideFacts,_events:MachineGuideEvent[],_states:MachineGuideState[],capabilities:SessionCapability[],denominators:DenominatorCapability[]){const metrics:MachineGuideMetric[]=[],benchmarks:SettingBenchmark[]=[];for(const section of facts.sections)for(const table of section.tables){if(!table.headers[0]?.includes("設定"))continue;for(let i=1;i<table.headers.length;i++){const label=table.headers[i],parsed=settings(table.rows,i);if(!parsed)continue;const key=metricKey(label),denom=denominator(label,section.key),numeratorId=metricNumerator(key,capabilities),minimumSample=600,validation=validateEstimatorDependency({settingValues:parsed.values,numeratorKey:numeratorId,denominator:denom,minimumSample,capabilities,denominators}),id=`metric:${slug(table.title)}:${slug(label)}`,estimatorEvidence=[tableEvidence(facts,table.id,"estimator",label,true,"設定 1～6 數值表；仍需獨立 control numerator 與可用 denominator")];metrics.push({id,metricKey:key,labelZh:label,numeratorEventId:numeratorId,denominator:denom,applicableStateIds:denom==="normal_games"?["state:normal"]:[],minimumSample,settingValues:parsed.values,sourceUrl:facts.sourceUrl,estimatorEvidence,observationContract:validation.contract,estimatorEligible:validation.eligible,unavailableReason:validation.reason});if(validation.eligible&&denom&&numeratorId)benchmarks.push({id,labelZh:label,labelJa:label,metricKey:key,kind:"rate",observation:{type:"rate",numeratorKey:numeratorId,denominatorMetricKey:validation.contract.denominatorObservationKey!,valueMode:parsed.mode},settingValues:parsed.values,minimumSample,source:`P-WORLD · ${facts.sourceUrl}`,updatedAt:facts.retrievedAt,verified:true,testData:false,evidenceIds:[table.id]})}}
  return{metrics,benchmarks};
}
function indicationChoices(facts:ParsedMachineGuideFacts){const choices=indicationTables(facts).flatMap(({section,table})=>table.rows.map(row=>{const label=row[0]?.normalize("NFKC").trim(),description=row.slice(1).filter(Boolean).join(" · ");if(!label||!description||missing.test(label)||missing.test(description))return null;const reference=tableEvidence(facts,table.id,"control",label,true,"結構化示唆表中的具名可選項");return{value:`choice:${slug(label)}`,labelZh:label,labelJa:label,sourceDescription:description,referenceOnly:false,sourceUrl:table.sourceUrl,sourceSectionKey:section.key,sourceTableId:table.id,sourceEvidenceId:reference.id}})).filter((choice):choice is NonNullable<typeof choice>=>Boolean(choice));return[...new Map(choices.map(choice=>[choice.value,choice])).values()];}
export function compileMachineGuide(facts:ParsedMachineGuideFacts):MachineGuide{const text=allText(facts),familyClassification=classify(facts),type=familyClassification.family,identity=deriveIdentity(facts,type);
  const smartCounters:CounterDefinition[]=identity.events.map(e=>{const choices=e.category==="indication"?indicationChoices(facts):undefined;return{id:`${facts.catalogId}-${slug(e.labelJa)}`,machineId:facts.catalogId,key:e.id,labelZh:e.labelZh,labelJa:e.labelJa,icon:e.category==="indication"?"🖼":"✦",description:"P-WORLD 公開資料中可辨識的事件。",recognition:e.whatToSee,reason:e.countingRule,type:e.category==="indication"?"choice":"event",...(choices?.length?{choices}:{})}});
  const modules=[sessionModule("total_games"),sessionModule("normal_games")];for(const e of identity.events.filter(e=>e.category==="bonus"))modules.push(sessionModule("big_reg_bonus",e.id,[e.labelZh,e.labelJa]));for(const e of identity.events.filter(e=>e.category==="cz"))modules.push(sessionModule("named_cz",e.id,[e.labelZh,e.labelJa]));for(const e of identity.events.filter(e=>e.category==="at"))modules.push(sessionModule("at",e.id,[e.labelZh,e.labelJa]));for(const e of identity.events.filter(e=>e.category==="art"))modules.push(sessionModule("art",e.id,[e.labelZh,e.labelJa]));if(type==="cycle_point_at")modules.push(sessionModule("cycle"),sessionModule("points"),sessionModule("cz_failures"));if(type==="set_based_at")modules.push(sessionModule("set"),sessionModule("role_streak"));if(/実ゲーム.*液晶ゲーム|液晶ゲーム.*実ゲーム/.test(text))modules.push(sessionModule("dual_games"));for(const e of identity.events.filter(e=>e.category==="indication"))modules.push(sessionModule("end_evidence",e.id,[e.labelZh,e.labelJa]));
  const sessionModules=unique(modules),sessionCapabilities=buildSessionCapabilities(sessionModules,smartCounters,identity.events),denominatorCapabilities=buildDenominatorCapabilities(sessionCapabilities),stats=deriveMetrics(facts,identity.events,identity.states,sessionCapabilities,denominatorCapabilities);for(const e of identity.events)e.affectsEstimator=stats.metrics.some(m=>m.estimatorEligible&&m.numeratorEventId===e.id);const controlManifest=buildControlManifest(sessionCapabilities,smartCounters,identity.events,identity.states);
  const useful=facts.sections.reduce((sum,s)=>sum+s.tables.length+(s.paragraphsJa.length?1:0),0),status=useful>=4?"usable":useful>0?"partial":"no_data",reasons:string[]=[];if(status==="no_data")reasons.push("來源沒有足夠結構化正文");if(!stats.benchmarks.length)reasons.push("尚無具備完整設定值、可靠分母及可記錄事件的推測指標");
  return{schemaVersion:2,catalogId:facts.catalogId,officialNameJa:facts.officialNameJa,displayNameZh:facts.displayNameZh,manufacturer:facts.manufacturer,machineType:type,introducedAt:facts.introducedAt,status,availability:{guide:status==="no_data"?"unavailable":status==="partial"?"partial":"available",sessionTemplate:status==="no_data"?"unavailable":sessionCapabilities.some(c=>c.status==="operational"&&c.moduleKind!=="total_games"&&c.moduleKind!=="normal_games")?"available":"partial",settingEstimator:stats.benchmarks.length?"available":"unavailable",reasons},beginnerGuide:{corePlay:facts.sections.find(s=>s.key==="play"||s.key==="flow")?.summaryZh??null,keyThings:identity.events.slice(0,5).map(e=>({id:e.id,labelZh:e.labelZh,labelJa:e.labelJa,meaning:`公開資料中的${e.category.toUpperCase()}事件`,recordWhen:e.countingRule})),glossary:[{termJa:"通常時",termZh:"一般遊戲狀態"},{termJa:"CZ",termZh:"進入 AT／ART 前的機會區間"},{termJa:"AT",termZh:"輔助出玉狀態"},{termJa:"ART",termZh:"Replay 輔助型出玉狀態"}],missingMessage:identity.events.length?null:"尚無資料"},states:identity.states,recordableEvents:identity.events,sessionModules,sessionCapabilities,denominatorCapabilities,estimatorMetrics:stats.metrics,sections:facts.sections,evidence:facts.evidence,missingSections:facts.missingSections,benchmarks:stats.benchmarks,smartCounters,sourceName:facts.sourceName,sourceUrl:facts.sourceUrl,retrievedAt:facts.retrievedAt};}
