import type { CounterDefinition, SettingBenchmark, SettingValues } from "@/types";
import type { GuideDenominator, GuideMachineType, GuideStateType, MachineFamilyClassification, MachineGuide, MachineGuideEvent, MachineGuideMetric, MachineGuideState, ParsedMachineGuideFacts, SessionCapability, DenominatorCapability } from "@/types/machineGuide";
import { sessionModule } from "./modules.ts";
import { buildDenominatorCapabilities, buildSessionCapabilities, validateEstimatorDependency } from "./capabilities.ts";
import { buildControlManifest } from "./controlManifest.ts";
/* eslint-disable @typescript-eslint/no-unused-vars -- compiler materializes the manifest; the P-WORLD adapter attaches it to the guide for backwards-compatible callers. */

const missing=/^(調査中|未公開|不明|—|-)?$/;
const genericNames=new Set(["CZ","AT","ART","BONUS","ボーナス","期待度","当選時","非当選時","本前兆中","突入","濃厚"]);
function slug(value:string){return value.normalize("NFKC").toLowerCase().replace(/[^a-z0-9\p{L}\p{N}]+/gu,"-").replace(/^-|-$/g,"").slice(0,48)||"event"}
function allText(facts:ParsedMachineGuideFacts){return[facts.officialNameJa,...facts.sections.flatMap(s=>[...s.paragraphsJa,...s.tables.flatMap(t=>[t.title,...t.headers,...t.rows.flat()])])].join("\n")}
function legacyClassify(text:string):GuideMachineType{
  if(/Aタイプ|ノーマルタイプ/.test(text)&&!/\b(?:AT|ART)\b/.test(text))return"a_type";
  if(/リアルボーナス|ボーナス.*ART|ART.*ボーナス/.test(text)&&/ART/.test(text))return"bonus_art";
  if(/周期/.test(text)&&/ポイント/.test(text)&&/AT/.test(text))return"cycle_point_at";
  if((/擬似ボーナス/.test(text)&&/(ループ|連チャン)/.test(text))||(/ボーナスストック/.test(text)&&/ボーナス初当り/.test(text)))return"bonus_loop";
  const czNames=[...text.matchAll(/(?:CZ|チャンスゾーン)[「『]?([\p{L}\p{N}ー・]{3,24})[」』]?/gu)].map(m=>m[1]);
  if(new Set(czNames).size>=2&&/AT/.test(text))return"multi_zone_at";
  if((/セット数管理|1セット|セット継続/.test(text)&&/AT/.test(text))||(/ミリオンゴッド/.test(text)&&/AT/.test(text)&&/ループストック/.test(text)))return"set_based_at";
  return"generic";
}
function classify(facts:ParsedMachineGuideFacts):MachineFamilyClassification{const text=allText(facts),tables=facts.sections.flatMap(section=>section.tables),structured=tables.map(table=>[table.title,...table.headers].join(" ")).join("\n"),bonusTable=tables.find(table=>/設定/.test(table.headers[0]??"")&&table.headers.some(header=>/^(?:BB|BIG)/i.test(header.trim()))&&table.headers.some(header=>/^(?:RB|REG)/i.test(header.trim())));if(bonusTable&&!/\b(?:AT|ART|CZ)\b/.test(structured))return{family:"a_type",confidence:"high",evidence:[`設定表「${bonusTable.title}」提供 BB／RB`],unsupportedReasons:[]};const family=legacyClassify(text);if(family!=="generic")return{family,confidence:"medium",evidence:["來源結構化玩法／表格符合共用 family"],unsupportedReasons:[]};if(/CZ/.test(structured)&&/AT/.test(structured))return{family:"cz_at",confidence:"high",evidence:["來源結構化表格同時提供 CZ 與 AT"],unsupportedReasons:[]};return{family:"generic",confidence:"low",evidence:[],unsupportedReasons:["來源不足以可靠判定共用 family"]}}
export const classifyMachineFamily=classify;
function state(id:string,ja:string,type:GuideStateType,sourceUrl:string):MachineGuideState{return{id:`state:${id}`,displayNameZh:ja,originalNameJa:ja,type,sourceUrl}}
function event(ja:string,category:MachineGuideEvent["category"],sourceUrl:string):MachineGuideEvent{const id=`event:${slug(ja)}`;return{id,labelZh:ja,labelJa:ja,category,whatToSee:`機台顯示「${ja}」時`,countingRule:"每次明確進入或出現時計 1 次。",sessionModuleIds:[],affectsEstimator:false,sourceUrl,unavailableReason:null}}
function unique<T extends{id:string}>(items:T[]){return[...new Map(items.map(item=>[item.id,item])).values()]}
function observableName(name:string){const value=name.normalize("NFKC").replace(/^[\s「『【（(]+|[\s」』】）)]+$/g,"").trim();if(value.length<2||value.length>40||genericNames.has(value))return null;if(/^(?:の|へ|を|に|で|が|は|と|や|非当選時|当選時|本前兆中)|(?:の|へ|を|に|で|が|は|と|や|時|中|当選時|非当選時|期待度|濃厚|突入|獲得)$/.test(value))return null;if(/期待度|非当選時|当選時|当選で|本前兆中|セットストック獲得|突入濃厚|獲得濃厚/.test(value))return null;return value}
function structuredStateNames(facts:ParsedMachineGuideFacts){const found:{name:string;category:"cz"|"at"|"art"}[]=[],text=allText(facts),titles=facts.sections.flatMap(section=>section.tables.map(table=>table.title));for(const title of titles){const match=title.match(/^(.{2,40}?)\s*\((CZ|AT|ART)\)(?:について|関連|中|$)/i),name=match&&observableName(match[1]);if(name&&match)found.push({name,category:match[2].toLowerCase() as "cz"|"at"|"art"})}for(const match of text.matchAll(/(?:CZ|AT|ART)\s*[「『]([^」』]{2,40})[」』]/giu)){const name=observableName(match[1]),category=match[0].slice(0,3).match(/^ART/i)?"art":match[0].match(/^AT/i)?"at":"cz";if(name)found.push({name,category})}for(const match of text.matchAll(/[「『]([^」』]{2,40})[」』]\s*(CZ|AT|ART)/giu)){const name=observableName(match[1]),category=match[2].toLowerCase() as "cz"|"at"|"art";if(name)found.push({name,category})}return[...new Map(found.map(item=>[`${item.category}:${item.name}`,item])).values()]}
function deriveIdentity(facts:ParsedMachineGuideFacts,type:GuideMachineType){const text=allText(facts),source=facts.sourceUrl,states=[state("normal","通常", "normal",source)],events:MachineGuideEvent[]=[];
  const bonusNames=[...text.matchAll(/(?:^|[\s、／・])((?:[A-Z][A-Z ]{1,18}|[\p{Script=Katakana}ー]{2,16})(?:BONUS|ボーナス))/gmu)].map(match=>observableName(match[1])).filter((name):name is string=>Boolean(name)),structured=structuredStateNames(facts),czNames=structured.filter(item=>item.category==="cz").map(item=>item.name),atNames=structured.filter(item=>item.category==="at").map(item=>item.name),artNames=structured.filter(item=>item.category==="art").map(item=>item.name);
  for(const name of bonusNames)events.push(event(name,"bonus",source));for(const name of czNames)events.push(event(name,"cz",source));if(type!=="a_type"&&type!=="bonus_loop"&&type!=="bonus_art")for(const name of atNames)events.push(event(name,"at",source));if(type==="bonus_art"||type==="generic")for(const name of artNames)events.push(event(name,"art",source));
  const headers=facts.sections.flatMap(section=>section.tables.flatMap(table=>table.headers));if(headers.some(header=>/^(?:BB|BIG(?: BONUS)?)$/i.test(header.trim())))events.push(event("BIG BONUS","bonus",source));if(headers.some(header=>/^(?:RB|REG(?: BONUS)?)$/i.test(header.trim())))events.push(event("REG BONUS","bonus",source));
  if((czNames.length>0||type==="multi_zone_at"||type==="cycle_point_at")&&/\bCZ\b|チャンスゾーン/.test(text))states.push(state("cz",czNames[0]??"CZ","chance_zone",source));
  if((atNames.length>0||type==="multi_zone_at"||type==="cycle_point_at"||type==="set_based_at")&&/\bAT\b/.test(text))states.push(state("at",atNames[0]??"AT","at",source));
  if((type==="bonus_art"||type==="generic")&&/\bART\b/.test(text))states.push(state("art",artNames[0]??"ART","art",source));
  if(bonusNames.length||/BIG|REG|ボーナス/.test(text))states.push(state("bonus",bonusNames[0]??"Bonus","bonus",source));
  const hasIndicationTable=facts.sections.some(section=>section.tables.some(table=>{const structured=[table.title,...table.headers].join(" ");return/終了画面|設定示唆/.test(structured)||/プレート/.test(structured)&&/示唆/.test(structured)}));if(hasIndicationTable)events.push(event("終了畫面／設定示唆","indication",source));
  return{states:unique(states),events:unique(events)};
}
function parsedNumber(value:string){if(missing.test(value.trim()))return null;const ratio=value.replace(/／/g,"/").match(/1\s*\/\s*([\d.]+)/);if(ratio)return{mode:"oneIn" as const,value:Number(ratio[1])};const pct=value.replace(/％/g,"%").match(/([\d.]+)\s*%/);return pct?{mode:"probability" as const,value:Number(pct[1])/100}:null}
function settings(rows:string[][],column:number){const out:Partial<SettingValues>={};let mode:"oneIn"|"probability"|null=null;for(const row of rows){const s=row[0]?.match(/設定\s*([1-6])/);if(!s)continue;const parsed=parsedNumber(row[column]??"");if(!parsed)return null;if(mode&&mode!==parsed.mode)return null;mode=parsed.mode;out[Number(s[1]) as 1|2|3|4|5|6]=parsed.value}return Object.keys(out).length===6&&mode?{values:out as SettingValues,mode}:null}
function denominator(label:string,section:string):GuideDenominator|null{if(/CZ.*成功|当選率/.test(label))return"specific_trials";if(/CZ|AT|ART/.test(label))return"normal_games";if(/^(?:BB|RB)$|BIG|REG|BONUS|ボーナス/.test(label)||section==="small_roles")return"total_games";return null}
function metricKey(label:string){if(/CZ/.test(label))return"cz";if(/ART/.test(label))return"art";if(/AT/.test(label))return"at";if(/^(?:BB|BIG)/i.test(label))return"bigBonus";if(/^(?:RB|REG)/i.test(label))return"regBonus";if(/ボーナス合成|BONUS合成/i.test(label))return"bonusCombined";return`guide-${slug(label)}`}
function metricNumerator(key:string,capabilities:SessionCapability[]){let candidates:SessionCapability[]=[];if(key==="cz")candidates=capabilities.filter(c=>c.moduleKind==="named_cz");else if(key==="at")candidates=capabilities.filter(c=>c.moduleKind==="at");else if(key==="art")candidates=capabilities.filter(c=>c.moduleKind==="art");else if(key==="bigBonus")candidates=capabilities.filter(c=>c.moduleKind==="big_reg_bonus"&&/big/i.test(c.labelJa));else if(key==="regBonus")candidates=capabilities.filter(c=>c.moduleKind==="big_reg_bonus"&&/reg|regular/i.test(c.labelJa));return candidates.length===1?candidates[0].observationKey:null}
function deriveMetrics(facts:ParsedMachineGuideFacts,_events:MachineGuideEvent[],_states:MachineGuideState[],capabilities:SessionCapability[],denominators:DenominatorCapability[]){const metrics:MachineGuideMetric[]=[],benchmarks:SettingBenchmark[]=[];for(const section of facts.sections)for(const table of section.tables){if(!table.headers[0]?.includes("設定"))continue;for(let i=1;i<table.headers.length;i++){const label=table.headers[i],parsed=settings(table.rows,i);if(!parsed)continue;const key=metricKey(label),denom=denominator(label,section.key),numeratorId=metricNumerator(key,capabilities),minimumSample=600,validation=validateEstimatorDependency({settingValues:parsed.values,numeratorKey:numeratorId,denominator:denom,minimumSample,capabilities,denominators}),id=`metric:${slug(table.title)}:${slug(label)}`;metrics.push({id,metricKey:key,labelZh:label,numeratorEventId:numeratorId,denominator:denom,applicableStateIds:denom==="normal_games"?["state:normal"]:[],minimumSample,settingValues:parsed.values,sourceUrl:facts.sourceUrl,estimatorEligible:validation.eligible,unavailableReason:validation.reason});if(validation.eligible&&denom&&numeratorId)benchmarks.push({id,labelZh:label,labelJa:label,metricKey:key,kind:"rate",observation:{type:"rate",numeratorKey:numeratorId,denominatorMetricKey:denominators.find(item=>item.key===denom)!.observationKey,valueMode:parsed.mode},settingValues:parsed.values,minimumSample,source:`P-WORLD · ${facts.sourceUrl}`,updatedAt:facts.retrievedAt,verified:true,testData:false,evidenceIds:[table.id]})}}
  return{metrics,benchmarks};
}
function indicationChoices(facts:ParsedMachineGuideFacts){const choices=facts.sections.flatMap(section=>section.tables).filter(table=>/終了画面|設定示唆|プレート/.test([table.title,...table.headers].join(" "))).flatMap(table=>table.rows.map(row=>{const label=row[0]?.normalize("NFKC").trim(),description=row.slice(1).filter(Boolean).join(" · ");if(!label||!description||missing.test(label)||missing.test(description))return null;return{value:`choice:${slug(label)}`,labelZh:label,labelJa:label,sourceDescription:description,referenceOnly:false}})).filter((choice):choice is NonNullable<typeof choice>=>Boolean(choice));return[...new Map(choices.map(choice=>[choice.value,choice])).values()];}
export function compileMachineGuide(facts:ParsedMachineGuideFacts):MachineGuide{const text=allText(facts),familyClassification=classify(facts),type=familyClassification.family,identity=deriveIdentity(facts,type);
  const smartCounters:CounterDefinition[]=identity.events.map(e=>{const choices=e.category==="indication"?indicationChoices(facts):undefined;return{id:`${facts.catalogId}-${slug(e.labelJa)}`,machineId:facts.catalogId,key:e.id,labelZh:e.labelZh,labelJa:e.labelJa,icon:e.category==="indication"?"🖼":"✦",description:"P-WORLD 公開資料中可辨識的事件。",recognition:e.whatToSee,reason:e.countingRule,type:e.category==="indication"?"choice":"event",...(choices?.length?{choices}:{})}});
  const modules=[sessionModule("total_games"),sessionModule("normal_games")];for(const e of identity.events.filter(e=>e.category==="bonus"))modules.push(sessionModule("big_reg_bonus",e.id,[e.labelZh,e.labelJa]));const namedCz=identity.events.filter(e=>e.category==="cz");if(namedCz.length)for(const e of namedCz)modules.push(sessionModule("named_cz",e.id,[e.labelZh,e.labelJa]));else if(identity.states.some(e=>e.type==="chance_zone"))modules.push(sessionModule("named_cz"));const namedAt=identity.events.filter(e=>e.category==="at");if(namedAt.length)for(const e of namedAt)modules.push(sessionModule("at",e.id,[e.labelZh,e.labelJa]));else if(identity.states.some(e=>e.type==="at"))modules.push(sessionModule("at"));for(const e of identity.events.filter(e=>e.category==="art"))modules.push(sessionModule("art",e.id,[e.labelZh,e.labelJa]));if(identity.states.some(e=>e.type==="art")&&!identity.events.some(e=>e.category==="art"))modules.push(sessionModule("art"));if(type==="cycle_point_at")modules.push(sessionModule("cycle"),sessionModule("points"),sessionModule("cz_failures"));if(type==="set_based_at")modules.push(sessionModule("set"),sessionModule("role_streak"));if(/実ゲーム.*液晶ゲーム|液晶ゲーム.*実ゲーム/.test(text))modules.push(sessionModule("dual_games"));for(const e of identity.events.filter(e=>e.category==="indication"))modules.push(sessionModule("end_evidence",e.id,[e.labelZh,e.labelJa]));
  const sessionModules=unique(modules),sessionCapabilities=buildSessionCapabilities(sessionModules,smartCounters),denominatorCapabilities=buildDenominatorCapabilities(sessionCapabilities),stats=deriveMetrics(facts,identity.events,identity.states,sessionCapabilities,denominatorCapabilities);for(const e of identity.events)e.affectsEstimator=stats.metrics.some(m=>m.estimatorEligible&&m.numeratorEventId===e.id);const controlManifest=buildControlManifest(sessionCapabilities,smartCounters,identity.events,identity.states,facts.sections.flatMap(section=>section.tables.map(table=>table.id)));
  const useful=facts.sections.reduce((sum,s)=>sum+s.tables.length+(s.paragraphsJa.length?1:0),0),status=useful>=4?"usable":useful>0?"partial":"no_data",reasons:string[]=[];if(status==="no_data")reasons.push("來源沒有足夠結構化正文");if(!stats.benchmarks.length)reasons.push("尚無具備完整設定值、可靠分母及可記錄事件的推測指標");
  return{schemaVersion:2,catalogId:facts.catalogId,officialNameJa:facts.officialNameJa,displayNameZh:facts.displayNameZh,manufacturer:facts.manufacturer,machineType:type,introducedAt:facts.introducedAt,status,availability:{guide:status==="no_data"?"unavailable":status==="partial"?"partial":"available",sessionTemplate:status==="no_data"?"unavailable":sessionCapabilities.some(c=>c.status==="operational"&&c.moduleKind!=="total_games"&&c.moduleKind!=="normal_games")?"available":"partial",settingEstimator:stats.benchmarks.length?"available":"unavailable",reasons},beginnerGuide:{corePlay:facts.sections.find(s=>s.key==="play"||s.key==="flow")?.summaryZh??null,keyThings:identity.events.slice(0,5).map(e=>({id:e.id,labelZh:e.labelZh,labelJa:e.labelJa,meaning:`公開資料中的${e.category.toUpperCase()}事件`,recordWhen:e.countingRule})),glossary:[{termJa:"通常時",termZh:"一般遊戲狀態"},{termJa:"CZ",termZh:"進入 AT／ART 前的機會區間"},{termJa:"AT",termZh:"輔助出玉狀態"},{termJa:"ART",termZh:"Replay 輔助型出玉狀態"}],missingMessage:identity.events.length?null:"尚無資料"},states:identity.states,recordableEvents:identity.events,sessionModules,sessionCapabilities,denominatorCapabilities,estimatorMetrics:stats.metrics,sections:facts.sections,evidence:facts.evidence,missingSections:facts.missingSections,benchmarks:stats.benchmarks,smartCounters,sourceName:facts.sourceName,sourceUrl:facts.sourceUrl,retrievedAt:facts.retrievedAt};}
