import type { CounterDefinition, SettingBenchmark, SettingValues } from "@/types";
import type { GuideDenominator, GuideMachineType, GuideStateType, MachineGuide, MachineGuideEvent, MachineGuideMetric, MachineGuideState, ParsedMachineGuideFacts } from "@/types/machineGuide";
import { sessionModule } from "./modules.ts";

const missing=/^(調査中|未公開|不明|—|-)?$/;
const genericNames=new Set(["CZ","AT","ART","BONUS","ボーナス"]);
function slug(value:string){return value.normalize("NFKC").toLowerCase().replace(/[^a-z0-9\p{L}\p{N}]+/gu,"-").replace(/^-|-$/g,"").slice(0,48)||"event"}
function allText(facts:ParsedMachineGuideFacts){return[facts.officialNameJa,...facts.sections.flatMap(s=>[s.titleJa,...s.paragraphsJa,...s.tables.flatMap(t=>[t.title,...t.headers,...t.rows.flat()])])].join("\n")}
function classify(text:string):GuideMachineType{
  if(/Aタイプ|ノーマルタイプ/.test(text)&&!/\b(?:AT|ART)\b/.test(text))return"a_type";
  if(/リアルボーナス|ボーナス.*ART|ART.*ボーナス/.test(text)&&/ART/.test(text))return"bonus_art";
  if(/周期/.test(text)&&/ポイント/.test(text)&&/AT/.test(text))return"cycle_point_at";
  if((/擬似ボーナス/.test(text)&&/(ループ|連チャン)/.test(text))||(/ボーナスストック/.test(text)&&/ボーナス初当り/.test(text)))return"bonus_loop";
  const czNames=[...text.matchAll(/(?:CZ|チャンスゾーン)[「『]?([\p{L}\p{N}ー・]{3,24})[」』]?/gu)].map(m=>m[1]);
  if(new Set(czNames).size>=2&&/AT/.test(text))return"multi_zone_at";
  if((/セット数管理|1セット|セット継続/.test(text)&&/AT/.test(text))||(/ミリオンゴッド/.test(text)&&/AT/.test(text)&&/ループストック/.test(text)))return"set_based_at";
  return"generic";
}
function state(id:string,ja:string,type:GuideStateType,sourceUrl:string):MachineGuideState{return{id:`state:${id}`,displayNameZh:ja,originalNameJa:ja,type,sourceUrl}}
function event(ja:string,category:MachineGuideEvent["category"],sourceUrl:string):MachineGuideEvent{const id=`event:${slug(ja)}`;return{id,labelZh:ja,labelJa:ja,category,whatToSee:`機台顯示「${ja}」時`,countingRule:"每次明確進入或出現時計 1 次。",sessionModuleIds:[],affectsEstimator:false,sourceUrl,unavailableReason:null}}
function unique<T extends{id:string}>(items:T[]){return[...new Map(items.map(item=>[item.id,item])).values()]}
function names(text:string,pattern:RegExp){return[...text.matchAll(pattern)].map(m=>(m[1]??"").trim()).filter(name=>name.length>=2&&!genericNames.has(name)&&!/について|終了画面|確率|関連/.test(name))}
function deriveIdentity(facts:ParsedMachineGuideFacts,type:GuideMachineType){const text=allText(facts),source=facts.sourceUrl,states=[state("normal","通常", "normal",source)],events:MachineGuideEvent[]=[];
  const bonusNames=names(text,/(?:^|[\s、／・])((?:[A-Z][A-Z ]{1,18}|[\p{Script=Katakana}ー]{2,16})(?:BONUS|ボーナス))/gmu);
  const czNames=names(text,/(?:CZ|チャンスゾーン)[「『:]?\s*([\p{L}\p{N}ー・]{3,24})/gu);
  const atNames=names(text,/(?:AT)[「『:]?\s*([\p{L}\p{N}ー・]{3,24})/gu);
  const artNames=names(text,/(?:ART)[「『:]?\s*([\p{L}\p{N}ー・]{3,24})/gu);
  for(const name of bonusNames)events.push(event(name,"bonus",source));for(const name of czNames)events.push(event(name,"cz",source));if(type!=="a_type"&&type!=="bonus_loop"&&type!=="bonus_art")for(const name of atNames)events.push(event(name,"at",source));if(type==="bonus_art"||type==="generic")for(const name of artNames)events.push(event(name,"art",source));
  if(/BIG/.test(text))events.push(event("BIG BONUS","bonus",source));if(/REG/.test(text))events.push(event("REG BONUS","bonus",source));
  if(type!=="a_type"&&type!=="bonus_loop"&&/\bCZ\b|チャンスゾーン/.test(text))states.push(state("cz",czNames[0]??"CZ","chance_zone",source));
  if(type!=="a_type"&&type!=="bonus_loop"&&type!=="bonus_art"&&/\bAT\b/.test(text))states.push(state("at",atNames[0]??"AT","at",source));
  if((type==="bonus_art"||type==="generic")&&/\bART\b/.test(text))states.push(state("art",artNames[0]??"ART","art",source));
  if(bonusNames.length||/BIG|REG|ボーナス/.test(text))states.push(state("bonus",bonusNames[0]??"Bonus","bonus",source));
  if(/終了画面|設定示唆/.test(text))events.push(event("終了畫面／設定示唆","indication",source));
  return{states:unique(states),events:unique(events)};
}
function parsedNumber(value:string){if(missing.test(value.trim()))return null;const ratio=value.replace(/／/g,"/").match(/1\s*\/\s*([\d.]+)/);if(ratio)return{mode:"oneIn" as const,value:Number(ratio[1])};const pct=value.replace(/％/g,"%").match(/([\d.]+)\s*%/);return pct?{mode:"probability" as const,value:Number(pct[1])/100}:null}
function settings(rows:string[][],column:number){const out:Partial<SettingValues>={};let mode:"oneIn"|"probability"|null=null;for(const row of rows){const s=row[0]?.match(/設定\s*([1-6])/);if(!s)continue;const parsed=parsedNumber(row[column]??"");if(!parsed)return null;if(mode&&mode!==parsed.mode)return null;mode=parsed.mode;out[Number(s[1]) as 1|2|3|4|5|6]=parsed.value}return Object.keys(out).length===6&&mode?{values:out as SettingValues,mode}:null}
function denominator(label:string,section:string):GuideDenominator|null{if(/CZ.*成功|当選率/.test(label))return"specific_trials";if(/CZ|AT|ART/.test(label))return"normal_games";if(/BIG|REG|BONUS|ボーナス/.test(label)||section==="small_roles")return"total_games";return null}
function metricKey(label:string){if(/CZ/.test(label))return"cz";if(/ART/.test(label))return"art";if(/AT/.test(label))return"at";if(/BIG/.test(label))return"bigBonus";if(/REG/.test(label))return"regBonus";return`guide-${slug(label)}`}
function deriveMetrics(facts:ParsedMachineGuideFacts,events:MachineGuideEvent[],states:MachineGuideState[]){const metrics:MachineGuideMetric[]=[],benchmarks:SettingBenchmark[]=[];for(const section of facts.sections)for(const table of section.tables){if(!table.headers[0]?.includes("設定"))continue;for(let i=1;i<table.headers.length;i++){const label=table.headers[i],parsed=settings(table.rows,i);if(!parsed)continue;const key=metricKey(label),denom=denominator(label,section.key),category=key==="cz"?"cz":key==="at"?"at":key==="art"?"art":"bonus",eventMatch=events.find(e=>e.category===category),stateMatch=states.find(s=>s.type===(category==="cz"?"chance_zone":category));const numeratorId=eventMatch?.id??stateMatch?.id??null,eligible=Boolean(denom&&numeratorId);const id=`metric:${slug(table.title)}:${slug(label)}`;metrics.push({id,metricKey:key,labelZh:label,numeratorEventId:numeratorId,denominator:denom,applicableStateIds:denom==="normal_games"?["state:normal"]:[],minimumSample:eligible?600:null,settingValues:parsed.values,sourceUrl:facts.sourceUrl,estimatorEligible:eligible,unavailableReason:eligible?null:denom?"Session 尚無可對應的事件或狀態":"無法確認可靠分母"});if(eligible)benchmarks.push({id,labelZh:label,labelJa:label,metricKey:key,kind:"rate",observation:{type:"rate",numeratorKey:key,denominatorMetricKey:denom==="normal_games"?"observedNormalGame":"observedTotalGame",valueMode:parsed.mode},settingValues:parsed.values,minimumSample:600,source:`P-WORLD · ${facts.sourceUrl}`,updatedAt:facts.retrievedAt,verified:true,testData:false,evidenceIds:[table.id]})}}
  return{metrics,benchmarks};
}
export function compileMachineGuide(facts:ParsedMachineGuideFacts):MachineGuide{const text=allText(facts),type=classify(text),identity=deriveIdentity(facts,type),stats=deriveMetrics(facts,identity.events,identity.states);for(const e of identity.events)e.affectsEstimator=stats.metrics.some(m=>m.estimatorEligible&&m.numeratorEventId===e.id);
  const modules=[sessionModule("total_games"),sessionModule("normal_games")];if(identity.events.some(e=>e.category==="bonus"))modules.push(sessionModule("big_reg_bonus"));for(const e of identity.events.filter(e=>e.category==="cz"))modules.push(sessionModule("named_cz",e.id,[e.labelZh,e.labelJa]));if(identity.states.some(e=>e.type==="at"))modules.push(sessionModule("at"));if(identity.states.some(e=>e.type==="art"))modules.push(sessionModule("art"));if(type==="cycle_point_at")modules.push(sessionModule("cycle"),sessionModule("points"),sessionModule("cz_failures"));if(type==="set_based_at")modules.push(sessionModule("set"),sessionModule("role_streak"));if(/実ゲーム.*液晶ゲーム|液晶ゲーム.*実ゲーム/.test(text))modules.push(sessionModule("dual_games"));if(identity.events.some(e=>e.category==="indication"))modules.push(sessionModule("end_evidence"));
  const smartCounters:CounterDefinition[]=identity.events.map(e=>({id:`${facts.catalogId}-${slug(e.labelJa)}`,machineId:facts.catalogId,key:e.id,labelZh:e.labelZh,labelJa:e.labelJa,icon:e.category==="indication"?"🖼":"✦",description:"P-WORLD 公開資料中可辨識的事件。",recognition:e.whatToSee,reason:e.countingRule,type:e.category==="indication"?"choice":"event"}));
  const useful=facts.sections.reduce((sum,s)=>sum+s.tables.length+(s.paragraphsJa.length?1:0),0),status=useful>=4?"usable":useful>0?"partial":"no_data",reasons:string[]=[];if(status==="no_data")reasons.push("來源沒有足夠結構化正文");if(!stats.benchmarks.length)reasons.push("尚無具備完整設定值、可靠分母及可記錄事件的推測指標");
  return{schemaVersion:2,catalogId:facts.catalogId,officialNameJa:facts.officialNameJa,displayNameZh:facts.displayNameZh,manufacturer:facts.manufacturer,machineType:type,introducedAt:facts.introducedAt,status,availability:{guide:status==="no_data"?"unavailable":status==="partial"?"partial":"available",sessionTemplate:status==="no_data"?"unavailable":modules.length>2?"available":"partial",settingEstimator:stats.benchmarks.length?"available":"unavailable",reasons},beginnerGuide:{corePlay:facts.sections.find(s=>s.key==="play"||s.key==="flow")?.summaryZh??null,keyThings:identity.events.slice(0,5).map(e=>({id:e.id,labelZh:e.labelZh,labelJa:e.labelJa,meaning:`公開資料中的${e.category.toUpperCase()}事件`,recordWhen:e.countingRule})),glossary:[{termJa:"通常時",termZh:"一般遊戲狀態"},{termJa:"CZ",termZh:"進入 AT／ART 前的機會區間"},{termJa:"AT",termZh:"輔助出玉狀態"},{termJa:"ART",termZh:"Replay 輔助型出玉狀態"}],missingMessage:identity.events.length?null:"尚無資料"},states:identity.states,recordableEvents:identity.events,sessionModules:unique(modules),estimatorMetrics:stats.metrics,sections:facts.sections,evidence:facts.evidence,missingSections:facts.missingSections,benchmarks:stats.benchmarks,smartCounters,sourceName:facts.sourceName,sourceUrl:facts.sourceUrl,retrievedAt:facts.retrievedAt};}
