import type { CounterDefinition } from "@/types";
import type { ControlManifestItem, MachineGuideEvent, MachineGuideState, SessionCapability } from "@/types/machineGuide";

const PRIORITY={named_cz:10,at:20,art:20,big_reg_bonus:30,end_evidence:40,small_role:50,total_games:0,normal_games:1,set:60,cycle:60,points:60,cz_failures:70,dual_games:70,role_streak:70,custom_event:80} as const;
function eventType(capability:SessionCapability):ControlManifestItem["eventType"]{if(capability.moduleKind==="named_cz")return"cz";if(capability.moduleKind==="at")return"at";if(capability.moduleKind==="art")return"art";if(capability.moduleKind==="big_reg_bonus")return"bonus";if(capability.moduleKind==="small_role")return"special";if(capability.moduleKind==="end_evidence")return"indication";if(capability.moduleKind==="total_games"||capability.moduleKind==="normal_games")return"game";return"numeric"}
function controlType(capability:SessionCapability):ControlManifestItem["controlType"]{if(capability.controlType==="choice")return"choice";if(capability.controlType==="tracker")return capability.moduleKind==="normal_games"?"derived_metric":"numeric_input";if(capability.controlType==="derived")return"derived_metric";return capability.status==="operational"?"counter":"numeric_input"}

export function buildControlManifest(capabilities:SessionCapability[],counters:CounterDefinition[],events:MachineGuideEvent[],states:MachineGuideState[]):ControlManifestItem[]{
  const counterByKey=new Map(counters.map(item=>[item.key,item]));
  const items:ControlManifestItem[]=capabilities.map(capability=>{const counter=counterByKey.get(capability.observationKey),event=events.find(item=>item.id===capability.eventId),type=controlType(capability);return{
    id:`control:${capability.moduleId}`,label:counter?.labelZh??capability.labelZh,eventType:eventType(capability),controlType:type,
    playerWhen:type==="numeric_input"?"更新機台目前顯示的數值":counter?.recognition??event?.whatToSee??`機台明確顯示「${capability.labelZh}」時`,
    observationKey:capability.observationKey,stateEffect:capability.stateEffect,estimatorUsable:capability.estimatorUsable,
    numerator:capability.numeratorDependency,denominator:capability.denominatorDependency,sourceEvidence:capability.sourceEvidence??[],controlEvidence:capability.controlEvidence??[],evidenceGate:capability.evidenceGate??(capability.moduleKind==="total_games"||capability.moduleKind==="normal_games"?"not_applicable":"blocked"),
    availability:capability.status,unavailableReason:capability.reason,quickPriority:PRIORITY[capability.moduleKind],moduleKind:capability.moduleKind,
    ...(capability.eventId?{eventId:capability.eventId}:{}),...(counter?.choices?{choices:counter.choices}:{})
  } satisfies ControlManifestItem});
  for(const guideState of states){const value=guideState.type==="chance_zone"?"cz":guideState.type,event=events.find(item=>item.labelJa===guideState.originalNameJa),controlEvidence=guideState.type==="normal"?[]:event?.controlEvidence??[],passed=guideState.type==="normal"||controlEvidence.some(item=>item.sufficient);items.push({id:`control:state:${guideState.id}`,label:guideState.displayNameZh,eventType:"state",controlType:"state_switch",playerWhen:`目前進入「${guideState.originalNameJa}」時`,observationKey:`state:${value}`,stateEffect:value==="entry"||value==="end"||value==="beginner"||value==="source"?null:value,estimatorUsable:false,numerator:null,denominator:null,sourceEvidence:controlEvidence.map(item=>item.id),controlEvidence,evidenceGate:guideState.type==="normal"?"not_applicable":passed?"passed":"blocked",availability:passed?"operational":"unavailable",unavailableReason:passed?null:"缺少可追溯的狀態證據。",quickPriority:5})}
  const bonusItems=items.filter(item=>item.availability==="operational"&&item.eventType==="bonus"&&item.controlType==="counter");if(bonusItems.some(item=>/BIG|BB/i.test(item.label))&&bonusItems.some(item=>/REG|RB/i.test(item.label)))items.push({id:"control:derived:bonus-total",label:"Bonus 合成",eventType:"derived",controlType:"derived_metric",playerWhen:"由 BIG BONUS 與 REG BONUS 自動計算",observationKey:"bonusTotal",stateEffect:null,estimatorUsable:false,numerator:null,denominator:"total_games",sourceEvidence:[...new Set(bonusItems.flatMap(item=>item.sourceEvidence))],controlEvidence:bonusItems.flatMap(item=>item.controlEvidence),evidenceGate:"passed",availability:"operational",unavailableReason:null,quickPriority:90});
  return items;
}
