import type { InitialHitMetric } from "@/types";
import type { GuideMachineSnapshot, MachineGuide } from "@/types/machineGuide";
import { buildControlManifest } from "./controlManifest.ts";

function initialHitMetrics(guide:MachineGuide):InitialHitMetric[]{const found=new Map<"cz"|"at",InitialHitMetric>();for(const benchmark of guide.benchmarks){const observation=benchmark.observation;if(observation.type!=="rate"||(observation.numeratorKey!=="cz"&&observation.numeratorKey!=="at")||found.has(observation.numeratorKey))continue;found.set(observation.numeratorKey,{metricKey:benchmark.metricKey,counterKey:observation.numeratorKey,labelZh:benchmark.labelZh,labelJa:benchmark.labelJa,denominatorMetricKey:observation.denominatorMetricKey})}return[...found.values()]}
export function machineFromGuide(guide:MachineGuide):GuideMachineSnapshot{
  if(guide.status==="no_data")throw new Error("尚無足夠資料建立 Session");
  const flow=guide.sections.filter(section=>section.key==="flow"||section.key==="play").flatMap(section=>section.paragraphsJa),controlManifest=guide.controlManifest??buildControlManifest(guide.sessionCapabilities,guide.smartCounters,guide.recordableEvents,guide.states);
  const chinese=guide.playerGuideZh,keyThings=chinese?.highlights.map(item=>({id:item.id,labelZh:item.label,labelJa:item.label,meaning:item.meaning,recordWhen:item.recordWhen}))??guide.beginnerGuide.keyThings;
  return{id:`guide:${guide.catalogId}`,catalogId:guide.catalogId,nameZh:guide.displayNameZh||guide.officialNameJa,nameJa:guide.officialNameJa,manufacturer:guide.manufacturer,category:guide.machineType,accent:"#f2c84b",profileStatus:"reviewed",guideStatus:guide.status,guideSourceUrl:guide.sourceUrl,sessionGuide:{corePlay:chinese?.overview??guide.beginnerGuide.corePlay,flow:structuredClone(flow),events:structuredClone(guide.recordableEvents),keyThings:structuredClone(keyThings),glossary:structuredClone(guide.beginnerGuide.glossary),sourceName:guide.sourceName,sourceUrl:guide.sourceUrl,retrievedAt:guide.retrievedAt,missingSections:structuredClone(guide.missingSections),evidence:structuredClone(guide.evidence)},journey:[],watchPoints:[],milestones:[],funPoints:[],pitfalls:[],playGuide:"請依機台提示與 P-WORLD 公開參考資料操作。",profile:{smartCounters:structuredClone(guide.smartCounters),gameTrackers:[{key:"dataGame",labelZh:"目前 G",labelJa:"現在 G",primary:true,quickAdd:10}],nightHunterFields:[],initialHitMetrics:initialHitMetrics(guide),measurementMetrics:[{key:"observedTotalGame",labelZh:"本 Session 已觀測",labelJa:"セッション観測 G",source:{type:"observedTotalGame"}},{key:"observedNormalGame",labelZh:"通常狀態觀測",labelJa:"通常時観測 G",source:{type:"observedNormalGame"}},{key:"dataGameDelta",labelZh:"目前 G 差值",labelJa:"現在 G 差分",source:{type:"trackerDelta",trackerKey:"dataGame"}}],trialRelationships:[],benchmarks:structuredClone(guide.benchmarks),sessionCapabilities:structuredClone(guide.sessionCapabilities),denominatorCapabilities:structuredClone(guide.denominatorCapabilities),guideStates:structuredClone(guide.states),controlManifest:structuredClone(controlManifest),...(guide.familyClassification?{familyClassification:structuredClone(guide.familyClassification)}:{})}};
}
